/**
 * @file services/reportCatalog.ts
 * @description Master catalog and configuration registry for all 29 Enterprise Reports.
 *
 * Categorized into 5 core business groups:
 * 1. Repair Operations (10)
 * 2. Quality & Diagnostics (2)
 * 3. Technician KPIs (2)
 * 4. Sales & CRM (7)
 * 5. Spare Parts & Stock (8)
 * Total: 29 Reports.
 *
 * Each report contains:
 * - ❓ របាយការណ៍នេះប្រើដើម្បីអ្វី? (Purpose / Why it exists)
 * - 📋 ពន្យល់ជួរឈរ (Columns Meaning Breakdown)
 * - 💡 ឧទាហរណ៍សាមញ្ញជាក់ស្តែង (Practical Real-world Example)
 */

export type ReportCategory =
  | "operations"
  | "diagnostics"
  | "kpis"
  | "sales"
  | "stock";

export interface ReportColumnConfig {
  key: string;
  label: string;
  labelKm?: string;
  field: string;
  widthPx: number;
  type: "text" | "number" | "date" | "currency" | "badge";
  align?: "left" | "center" | "right";
  visible: boolean;
  aggregation?: "none" | "sum" | "count" | "avg";
  bold?: boolean;
  explanationKm?: string;
  explanationEn?: string;
}

export interface ReportDefinition {
  id: string;
  name: string;
  nameKm: string;
  category: ReportCategory;
  categoryName: string;
  categoryNameKm: string;
  type: "form" | "excel";
  description: string;
  descriptionKm: string;
  databaseSource: string;
  databaseSourceKm: string;
  businessPurpose: string;
  businessPurposeKm: string;
  columnsExplanationKm?: string[];
  columnsExplanationEn?: string[];
  exampleKm?: string;
  exampleEn?: string;
  href?: string;
  columns: ReportColumnConfig[];
  defaultSort?: { field: string; direction: "asc" | "desc" };
}

export const REPORT_CATEGORIES: {
  id: ReportCategory;
  name: string;
  nameKm: string;
  count: number;
  icon: string;
}[] = [
  { id: "operations", name: "Repair Operations", nameKm: "ប្រតិបត្តិការជួសជុល", count: 10, icon: "Wrench" },
  { id: "diagnostics", name: "Quality & Diagnostics", nameKm: "គុណភាព & វិភាគបញ្ហា", count: 2, icon: "AlertCircle" },
  { id: "kpis", name: "Technician KPIs", nameKm: "សូចនាករ KPI ជាង", count: 2, icon: "Award" },
  { id: "sales", name: "Sales & CRM", nameKm: "ផ្នែកលក់ & អតិថិជន", count: 7, icon: "TrendingUp" },
  { id: "stock", name: "Spare Parts & Stock", nameKm: "គ្រឿងបន្លាស់ & ស្តុក", count: 8, icon: "Package" },
];

export const ALL_REPORTS: ReportDefinition[] = [
  // ── 1. REPAIR OPERATIONS (10 Reports) ──
  {
    id: "technical-service-report",
    name: "Technical Service Report",
    nameKm: "Technical Service Report (A4 Form)",
    category: "operations",
    categoryName: "Repair Operations",
    categoryNameKm: "ប្រតិបត្តិការជួសជុល",
    type: "form",
    description: "Official customer-facing A4 printable service certificate with diagnostic boxes, parts, and signatures.",
    descriptionKm: "ទម្រង់ប័ណ្ណ A4 ផ្លូវការបោះពុម្ពជូនអតិថិជនជាវិញ្ញាបនបត្របញ្ជាក់ការជួសជុល និងមានប្រអប់ហត្ថលេខាទទួលម៉ាស៊ីន។",
    databaseSource: "Single Ticket ID, Customer, Serial No, Problem, Inspection, Solution, Spareparts Used, Signatures (Inspector, Tech, Supervisor)",
    databaseSourceKm: "ព័ត៌មានលម្អិតនៃសំបុត្រតែមួយ (Ticket ID, Customer, Serial No, Problem, Inspection, Solution, Spareparts Used, ហត្ថលេខា ៣ ប្រអប់)",
    businessPurpose: "Official A4 handover certificate signed by both parties validating warranty and repair scope.",
    businessPurposeKm: "ជា «ប័ណ្ណ A4 បញ្ជាក់ការជួសជុល» បោះពុម្ពចេញពេលជួសជុលរួច ដើម្បីឱ្យអតិថិជនចុះហត្ថលេខាទទួលម៉ាស៊ីន និងទុកជាភស្តុតាងធានា។",
    columnsExplanationKm: [
      "• Report No ៖ លេខកូដសំបុត្រសម្គាល់ការជួសជុលតែមួយគត់ (ឧ. 20260817-1695)",
      "• Customer / Company ៖ ឈ្មោះក្រុមហ៊ុន ឬម្ចាស់ឧបករណ៍",
      "• Item Name / Model ៖ ម៉ាក និងម៉ូដែលឧបករណ៍ដែលយកមកជួសជុល (ឧ. Canon IR-2520)",
      "• Serial Number ៖ លេខកូដសម្គាល់ម៉ាស៊ីនពីរោងចក្រ ដើម្បីកុំឱ្យច្រឡំម៉ាស៊ីនគ្នា",
      "• Problem Symptom ៖ រោគសញ្ញាដែលអតិថិជនបានប្រាប់ពេលយកមកផ្ញើ (ឧ. ព្រីនចេញខ្មៅ)",
      "• Diagnostic Finding ៖ មូលហេតុពិតប្រាកដដែលរកឃើញដោយជាង (ឧ. រហែក Fuser Film)",
      "• Spareparts Replaced ៖ បញ្ជីគ្រឿងបន្លាស់ SKU, បរិមាណ និងតម្លៃដែលបានប្តូរ",
      "• Signatures ៖ ប្រអប់ហត្ថលេខា ៣ (ជាងជួសជុល, Supervisor ត្រួតពិនិត្យ QA, និងអតិថិជនចុះហត្ថលេខាទទួល)",
    ],
    columnsExplanationEn: [
      "• Report No: Unique ticket tracking identifier (e.g. 20260817-1695)",
      "• Customer / Company: Corporate or individual equipment owner",
      "• Item Name / Model: Hardware brand and model name (e.g. Canon IR-2520)",
      "• Serial Number: Factory unique serial number verifying warranty",
      "• Problem Symptom: Initial defect reported by customer at intake",
      "• Diagnostic Finding: Actual root-cause determined by technician",
      "• Spareparts Replaced: Table of parts SKU, quantity, and unit prices",
      "• Signatures: Triple sign-off boxes (Technician, QA Supervisor, Customer)",
    ],
    exampleKm: "ធនាគារ ABA យកម៉ាស៊ីនព្រីន Canon IR-2520 មកជួសជុល ➔ ពេលជួសជុលរួចរាល់ យើងបោះពុម្ពសន្លឹក A4 នេះឱ្យតំណាងធនាគារចុះហត្ថលេខាទទួល និងកត់ត្រាគ្រឿងបន្លាស់ដែលបានប្តូរ (Fuser Film Sleeve $35) ទុកជាភស្តុតាងធានា ៣០ ថ្ងៃ។",
    exampleEn: "ABA Bank services Canon IR-2520 -> Print official A4 handover sheet with replaced Fuser Film ($35) and triple signatures (Tech, QA, ABA Rep) for 30-day warranty.",
    href: "/templates-settings",
    columns: [],
  },
  {
    id: "daily-report",
    name: "Daily Operations Report",
    nameKm: "Daily Operations Report",
    category: "operations",
    categoryName: "Repair Operations",
    categoryNameKm: "ប្រតិបត្តិការជួសជុល",
    type: "excel",
    description: "Full breakdown of daily received tickets, work in progress, and delivered items.",
    descriptionKm: "តាមដានលំហូរការងារប្រចាំថ្ងៃរបស់រោងជាង ថាតើថ្ងៃនេះមានម៉ាស៊ីនចូលប៉ុន្មាន កំពុងពិនិត្យប៉ុន្មាន កំពុងជួសជុលប៉ុន្មាន និងចេញបានប៉ុន្មាន។",
    databaseSource: "Services table filtered by selected date across all StatusDate columns",
    databaseSourceKm: "សំបុត្រទាំងអស់ដែលមានសកម្មភាពក្នុងថ្ងៃជ្រើសរើស (តាម StatusDate គ្រប់ដំណាក់កាល)",
    businessPurpose: "Track daily intake, active inspections, ongoing repairs, and completed delivery volumes.",
    businessPurposeKm: "ជា «សៀវភៅតាមដានការងារប្រចាំថ្ងៃ» មើលថាថ្ងៃនេះមានម៉ាស៊ីនចូលថ្មីប៉ុន្មាន កំពុងធ្វើប៉ុន្មាន និងចេញបានប៉ុន្មាន។",
    columnsExplanationKm: [
      "• Received Date ៖ កាលបរិច្ឆេទទទួលម៉ាស៊ីនចូលដំបូង (dd/MM/yyyy)",
      "• Days ៖ រយៈពេលចំណាយគិតជាថ្ងៃ (Days Taken / Aging)",
      "• Finished Date ៖ កាលបរិច្ឆេទជួសជុលរួចរាល់ (dd/MM/yyyy)",
      "• Company Name ៖ ឈ្មោះក្រុមហ៊ុន ឬស្ថាប័នអតិថិជន",
      "• Item Name ៖ ម៉ាក និងម៉ូដែលម៉ាស៊ីន",
      "• Serial Number ៖ លេខកូដសម្គាល់ម៉ាស៊ីនពីរោងចក្រ",
      "• Sparepart Items ៖ បញ្ជីឈ្មោះគ្រឿងបន្លាស់ដែលបានប្រើប្រាស់ (ឬ N/A បើគ្មាន)",
      "• អ្នកជួសជុល ៖ ឈ្មោះពេញរបស់ជាងបច្ចេកទេសទទួលខុសត្រូវជួសជុល",
    ],
    columnsExplanationEn: [
      "• Received Date: Machine intake date (dd/MM/yyyy)",
      "• Days: Duration in days taken for repair / turnaround",
      "• Finished Date: Date repair completed (dd/MM/yyyy)",
      "• Company Name: Customer company or organization name",
      "• Item Name: Device brand and model",
      "• Serial Number: Hardware serial number",
      "• Sparepart Items: Replaced spare parts list (or N/A)",
      "• អ្នកជួសជុល (Technician): Full name of the repairing technician",
    ],
    exampleKm: "ប្រធានរោងជាងបើកមើលនៅម៉ោង ៥ ល្ងាច ➔ ឃើញថាថ្ងៃនេះទទួលម៉ាស៊ីនថ្មី ៨ គ្រឿង, ជាងកំពុងជួសជុល ៥ គ្រឿង, QA អនុម័តរួចរាល់ ៦ គ្រឿង, និងអតិថិជនមកទទួលយកត្រឡប់ ៤ គ្រឿង។",
    exampleEn: "Workshop manager checks at 5 PM -> 8 new tickets received, 5 in active repair, 6 QA passed, 4 delivered to clients.",
    href: "/daily-report",
    columns: [],
  },
  {
    id: "monthly-report",
    name: "Monthly Performance Report",
    nameKm: "Monthly Performance Report",
    category: "operations",
    categoryName: "Repair Operations",
    categoryNameKm: "ប្រតិបត្តិការជួសជុល",
    type: "excel",
    description: "Monthly aggregation of repair volume, service types, and completion rates.",
    descriptionKm: "ផ្តល់ទិដ្ឋភាពទូទៅនៃបរិមាណការងារប្រចាំខែ ចំនួនម៉ាស៊ីនជួសជុលរួច/មិនរួច និងចំណាយសរុបតាមអតិថិជននីមួយៗ។",
    databaseSource: "Monthly aggregated tickets grouped by customer company, DaysTaken, and spare parts total costs",
    databaseSourceKm: "សំបុត្រសរុបប្រចាំខែ បែងចែកតាមឈ្មោះក្រុមហ៊ុនអតិថិជន, រយៈពេលជួសជុល, តម្លៃគ្រឿងបន្លាស់សរុប",
    businessPurpose: "Comprehensive overview of monthly volume, resolved vs unresolved jobs, and customer costs.",
    businessPurposeKm: "ជា «សង្ខេបលទ្ធផលប្រចាំខែ» មើលថាក្នុងមួយខែៗរោងជាងជួសជុលបានសរុបប៉ុន្មានគ្រឿង និងអត្រាជោគជ័យប៉ុន្មាន %។",
    columnsExplanationKm: [
      "• Date ៖ ថ្ងៃខែឆ្នាំដែលទទួលម៉ាស៊ីនក្នុងខែនោះ",
      "• Report # ៖ លេខកូដសំបុត្រជួសជុល",
      "• Item Name ៖ ឈ្មោះម៉ូដែលម៉ាស៊ីន",
      "• Serial Number ៖ លេខកូដសម្គាល់ម៉ាស៊ីន",
      "• Engineer ៖ ឈ្មោះជាងបច្ចេកទេសទទួលបន្ទុកការជួសជុល",
      "• Status ៖ ស្ថានភាពចុងក្រោយ (Fixed រួចរាល់, Delivered ប្រគល់រួច, Rejected មិនជួសជុល, Unrepairable ខូចធ្ងន់)",
    ],
    columnsExplanationEn: [
      "• Date: Intake date within the selected month",
      "• Report #: Repair ticket code",
      "• Item Name: Device brand and model",
      "• Serial Number: Hardware serial number",
      "• Engineer: Assigned / repairing technician name",
      "• Status: Final resolution state (Fixed, Delivered, Rejected, Unrepairable)",
    ],
    exampleKm: "សរុបខែសីហា ទទួលម៉ាស៊ីន ១២០ គ្រឿង ➔ ជួសជុលរួច ១១២ គ្រឿង (ជោគជ័យ ៩៣.៣%), មិនរួច ៨ គ្រឿង, រយៈពេលជួសជុលមធ្យម ២.១ ថ្ងៃក្នុងមួយគ្រឿង, ចំណូលសេវាសរុប $4,850។",
    exampleEn: "August summary: 120 total intake -> 112 repaired (93.3% success rate), 8 unresolved, 2.1 days avg turnaround, $4,850 total revenue.",
    href: "/monthly-report",
    columns: [],
  },
  {
    id: "monthly-technical-matrix",
    name: "Monthly Technical Matrix",
    nameKm: "Monthly Technical Matrix",
    category: "operations",
    categoryName: "Repair Operations",
    categoryNameKm: "ប្រតិបត្តិការជួសជុល",
    type: "excel",
    description: "Annual 12-Month technical performance summary & technician forecast matrix.",
    descriptionKm: "តារាងម៉ាទ្រីសផ្លូវការ ១២ ខែរបស់ផ្នែកបច្ចេកទេស សម្រាប់ប្រជុំថ្នាក់គ្រប់គ្រង និងព្យាករណ៍ការងារឆ្នាំបន្ទាប់។",
    databaseSource: "12-month aggregate data from /annual-matrix endpoint (Intake, Out, Unrepairable, Waiting Confirm, Third-Party)",
    databaseSourceKm: "ទិន្នន័យ Aggregate ១២ ខែពី /annual-matrix (ម៉ាស៊ីនចូល, ម៉ាស៊ីនចេញ, ជួសជុលមិនបាន, រង់ចាំយល់ព្រម, សេវាខាងក្រៅ)",
    businessPurpose: "Official executive 12-month KPI table used in management meetings and annual forecasting.",
    businessPurposeKm: "ជា «តារាងប្រៀបធៀប ១២ ខែ (Jan-Dec)» សម្រាប់ថ្នាក់ដឹកនាំមើលនិន្នាការការងារពេញមួយឆ្នាំ និងរៀបចំកម្លាំងជាងទុកជាមុន។",
    columnsExplanationKm: [
      "• Technical for Month ៖ ប្រភេទសូចនាករបច្ចេកទេស (ម៉ាស៊ីនចូល, ជួសជុលរួច, មិនអាចជួសជុលបាន, រង់ចាំភ្ញៀវ, ជួសជុលក្រៅ)",
      "• Jan ដល់ Dec ៖ ចំនួនម៉ាស៊ីនក្នុងខែនីមួយៗពីខែ មករា ដល់ ធ្នូ",
      "• Total / YTD ៖ ផលបូកសរុបពេញមួយឆ្នាំ (Year-to-Date)",
    ],
    columnsExplanationEn: [
      "• Technical for Month: Operational metric categories (Intake, Repaired, Unrepairable, Waiting Confirm, Outsourced)",
      "• Jan - Dec: Monthly counts recorded across the calendar year",
      "• Total / YTD: Cumulative full-year sum for executive forecasting",
    ],
    exampleKm: "មើលឃើញថាខែមេសា (ចូលឆ្នាំខ្មែរ) ម៉ាស៊ីនចូលធ្លាក់ចុះសល់តែ ៤៥ គ្រឿង តែដល់ខែតុលា (រដូវបិទបញ្ជី) ម៉ាស៊ីនចូលកើនដល់ ១៨០ គ្រឿង ➔ ប្រធានរោងជាងរៀបចំកម្លាំងជាង និងស្តុកគ្រឿងបន្លាស់ទុកជាមុន។",
    exampleEn: "Annual 12-month matrix forecast: April (Khmer New Year) drops to 45 units, October peaks at 180 units -> Pre-allocate workshop manpower.",
    href: "/monthly-technical-matrix",
    columns: [],
  },
  {
    id: "repair-report",
    name: "Repair Performance Audit",
    nameKm: "Repair Performance Audit",
    category: "operations",
    categoryName: "Repair Operations",
    categoryNameKm: "ប្រតិបត្តិការជួសជុល",
    type: "excel",
    description: "In-depth turnaround analysis comparing Free vs Charge service durations.",
    descriptionKm: "ធ្វើសវនកម្មលើល្បឿននៃការជួសជុល (Turnaround Time) ថាតើការងារ Free និងការងារ Charge ចំណាយពេលខុសគ្នាកម្រិតណា។",
    databaseSource: "Completed services partitioned by Free vs Charge, DaysTaken, and ServiceLocation",
    databaseSourceKm: "សំបុត្រដែលបានបញ្ចប់ ប្រៀបធៀបរវាងប្រភេទ Free និង Charge, DaysTaken, និងទីតាំងសេវា",
    businessPurpose: "Audits repair turnaround duration to see how free warranty jobs compare with billable charge jobs.",
    businessPurposeKm: "ជា «តារាងវាស់ទិន្នផលជួសជុលរបស់ជាងម្នាក់ៗប្រចាំខែ» មើលថាជាងណាធ្វើបានច្រើន និងលឿនជាងគេពេញមួយឆ្នាំ។",
    columnsExplanationKm: [
      "• Engineer ៖ ឈ្មោះជាងបច្ចេកទេសជួសជុល",
      "• Jan ដល់ Dec ៖ ចំនួនការងារដែលជាងម្នាក់នោះជួសជុលរួចក្នុងខែនីមួយៗ",
      "• Total ៖ ផលបូកចំនួនម៉ាស៊ីនសរុបដែលជាងបានបញ្ចប់ពេញមួយឆ្នាំ",
    ],
    columnsExplanationEn: [
      "• Engineer: Servicing technician name",
      "• Jan - Dec: Monthly completed repair counts across the year",
      "• Total: Total cumulative repaired jobs completed by engineer",
    ],
    exampleKm: "ជាង សុខ ជួសជុលបានសរុប ៤២០ គ្រឿងក្នុងមួយឆ្នាំ (មធ្យម ៣៥ គ្រឿង/ខែ) ➔ ជាប់ជាជាងឆ្នើមប្រចាំឆ្នាំ និងទទួលបានការដំឡើងប្រាក់លើកទឹកចិត្ត។",
    exampleEn: "Tech Sok finishes 420 jobs in the year (avg 35 jobs/month) -> Awarded Technician of the Year honors.",
    href: "/repair-report",
    columns: [],
  },
  {
    id: "stage-report",
    name: "Stage & Workflow Breakdown",
    nameKm: "Stage & Workflow Breakdown",
    category: "operations",
    categoryName: "Repair Operations",
    categoryNameKm: "ប្រតិបត្តិការជួសជុល",
    type: "excel",
    description: "Stage-by-stage ticket volume & bottleneck detection across the workflow.",
    descriptionKm: "ជួយអ្នកគ្រប់គ្រងរកឃើញចំណុចកកស្ទះ (Bottleneck) ថាតើសំបុត្រកំពុងគាំងនៅដំណាក់កាលណាជាងគេ។",
    databaseSource: "Real-time count and list of active tickets grouped by ServiceStatusId",
    databaseSourceKm: "ចំនួន និងបញ្ជីសំបុត្រដែលកំពុងស្ថិតនៅតាមដំណាក់កាលនីមួយៗ (Received, Inspecting, Repairing, Verified)",
    businessPurpose: "Identifies queue bottlenecks across all 11 lifecycle stages to reallocate technicians.",
    businessPurposeKm: "ជា «ឧបករណ៍ស្វែងរកចំណុចកកស្ទះ (Bottleneck)» មើលថាតើសំបុត្រកំពុងគាំងនៅកន្លែងណា ដើម្បីដោះស្រាយបានទាន់ពេល។",
    columnsExplanationKm: [
      "• Action Date ៖ ថ្ងៃខែឆ្នាំដែលសំបុត្របានផ្លាស់ប្តូរដំណាក់កាល",
      "• Report # ៖ លេខកូដសំបុត្រជួសជុល",
      "• Company ៖ ឈ្មោះក្រុមហ៊ុនអតិថិជន",
      "• Item Name ៖ ម៉ូដែលម៉ាស៊ីន",
      "• Serial Number ៖ លេខសម្គាល់ម៉ាស៊ីន",
      "• Performed By ៖ ឈ្មោះបុគ្គលិកដែលរុញការងារទៅមុខ",
      "• Current Status ៖ ដំណាក់កាលបច្ចុប្បន្ន (ឧ. Awaiting Customer Confirm, In-Progress Repair)",
    ],
    columnsExplanationEn: [
      "• Action Date: Timestamp when stage transition occurred",
      "• Report #: Repair ticket code",
      "• Company: Corporate client entity",
      "• Item Name: Device hardware model",
      "• Serial Number: Unique serial number",
      "• Performed By: Employee who executed the transition",
      "• Current Status: Live lifecycle stage",
    ],
    exampleKm: "ឃើញមានសំបុត្រចំនួន ១៥ កំពុងជាប់គាំងនៅ `Awaiting Customer Confirm` យូរថ្ងៃ (មធ្យម ៣.៥ ថ្ងៃ) ➔ ប្រធានរោងជាងជំរុញឱ្យផ្នែកលក់ទូរស័ព្ទទៅភ្ញៀវភ្លាមៗដើម្បីពន្យល់តម្លៃ និងជួយភ្ញៀវសម្រេចចិត្ត។",
    exampleEn: "15 tickets stalled in 'Awaiting Customer Confirm' (avg 3.5 days) -> Workshop head alerts sales to call customers immediately.",
    href: "/stage-report",
    columns: [],
  },
  {
    id: "third-party-repairs",
    name: "Third-Party Operations Log",
    nameKm: "Third-Party Operations Log",
    category: "operations",
    categoryName: "Repair Operations",
    categoryNameKm: "ប្រតិបត្តិការជួសជុល",
    type: "excel",
    description: "Outsourced repair tracking with third-party vendor costs and turnaround times.",
    descriptionKm: "តាមដានប្រសិទ្ធភាព ចំណាយ និងល្បឿននៃការផ្ញើការងារជួសជុលទៅដៃគូខាងក្រៅ។",
    databaseSource: "Services with ThirdPartyRepairBy, Outsource Partner Name, External Cost, Days Waiting",
    databaseSourceKm: "សំបុត្រដែលបញ្ជូនទៅ Outsource (Repair by Third-Party), ឈ្មោះជាងក្រៅ, ចំណាយថ្លៃជួសជុលក្រៅ, រយៈពេលរង់ចាំ",
    businessPurpose: "Tracks outsourcing efficiency, partner repair fees, and external turnaround durations.",
    businessPurposeKm: "សម្រាប់ «តាមដានម៉ាស៊ីនដែលផ្ញើទៅជាងខាងក្រៅ (Outsource)» ដឹងពីថ្លៃដើមជាងក្រៅ និងកាលបរិច្ឆេទយកត្រឡប់មកវិញ។",
    columnsExplanationKm: [
      "• Sent Date ៖ ថ្ងៃដែលផ្ញើម៉ាស៊ីនចេញទៅហាងក្រៅ",
      "• Report # ៖ លេខកូដសំបុត្រជួសជុល",
      "• Company ៖ ឈ្មោះក្រុមហ៊ុនម្ចាស់ម៉ាស៊ីន",
      "• Item Name ៖ ម៉ូដែលឧបករណ៍ដែលផ្ញើទៅ Outsource",
      "• Serial Number ៖ លេខកូដសម្គាល់ម៉ាស៊ីន",
      "• Days Out ៖ ចំនួនថ្ងៃដែលម៉ាស៊ីនស្ថិតនៅហាងជាងក្រៅ (Turnaround)",
      "• Handled By ៖ ឈ្មោះហាង ឬជាងក្រៅដែលទទួលការងារ (ឧ. Smart Tech)",
      "• Status ៖ ស្ថានភាពបច្ចុប្បន្ន (កំពុងជួសជុល ឬផ្ញើត្រឡប់មកវិញហើយ)",
    ],
    columnsExplanationEn: [
      "• Sent Date: Date dispatched to third-party vendor",
      "• Report #: Repair ticket code",
      "• Company: Customer company name",
      "• Item Name: Hardware model name",
      "• Serial Number: Factory serial number",
      "• Days Out: Elapsed turnaround days at external workshop",
      "• Handled By: Third-party vendor / partner name",
      "• Status: Current outsourced repair status",
    ],
    exampleKm: "ម៉ាស៊ីន Plotter ខូច Mainboard ពិសេស ផ្ញើទៅជាងក្រៅ (Smart Tech) អស់ ៥ ថ្ងៃ ថ្លៃដើមជាងក្រៅ $120 ➔ ក្រុមហ៊ុនគិតថ្លៃសេវាពីភ្ញៀវ $180 (ចំណេញបាន Gross Margin $60)។",
    exampleEn: "Plotter mainboard outsourced: Partner cost $120 (5 days turnaround), billed to client $180 ($60 gross profit retained).",
    href: "/third-party-repairs",
    columns: [],
  },
  {
    id: "contract-report",
    name: "Contract Service Matrix",
    nameKm: "Contract Service Matrix",
    category: "operations",
    categoryName: "Repair Operations",
    categoryNameKm: "ប្រតិបត្តិការជួសជុល",
    type: "excel",
    description: "Contract vs non-contract repair ratio and annual maintenance agreement delivery.",
    descriptionKm: "វាយតម្លៃសមាមាត្រនៃការផ្តល់សេវាជូនអតិថិជនកុងត្រាថែទាំប្រចាំឆ្នាំ ធៀបនឹងអតិថិជនទូទៅ។",
    databaseSource: "Services partitioned by HasContract boolean, customer agreements, and SLA compliance",
    databaseSourceKm: "សំបុត្រជួសជុលបែងចែករវាងម៉ាស៊ីនមានកុងត្រា (hasContract=true) និងម៉ាស៊ីនគ្មានកុងត្រា (Walk-in)",
    businessPurpose: "Evaluates service delivery for contracted annual maintenance clients vs ad-hoc walk-ins.",
    businessPurposeKm: "មើលថាតើ «អតិថិជនមានកុងត្រា (Contract) និងអតិថិជនទូទៅ (Walk-in) មួយណាប្រើសេវាច្រើនជាង» ដើម្បីរៀបចំធនធាន។",
    columnsExplanationKm: [
      "• Date ៖ ថ្ងៃខែឆ្នាំដែលចុះទៅផ្តល់សេវា",
      "• Report # ៖ លេខកូដសំបុត្រជួសជុល",
      "• Company ៖ ឈ្មោះក្រុមហ៊ុនអតិថិជន",
      "• Contract ៖ បញ្ជាក់ថា Under Contract (មានកុងត្រា) ឬ Non-Contract (ទូទៅ)",
      "• Service Type ៖ សេវាថែទាំកុងត្រា ឬជួសជុលគិតថ្លៃ",
      "• Item Name ៖ ម៉ូដែលឧបករណ៍ដែលបានថែទាំ",
      "• Serial Number ៖ លេខ Serial Number ម៉ាស៊ីន",
      "• Status ៖ ស្ថានភាពបញ្ចប់ការងារ",
    ],
    columnsExplanationEn: [
      "• Date: Service inspection timestamp",
      "• Report #: Repair ticket code",
      "• Company: Customer organization name",
      "• Contract: Under Contract vs Non-Contract flag",
      "• Service Type: Maintenance agreement vs Chargeable repair",
      "• Item Name: Equipment model",
      "• Serial Number: Hardware serial number",
      "• Status: Completion status",
    ],
    exampleKm: "ក្នុងចំណោមការជួសជុល ៨០ លើកក្នុងខែនេះ មាន ៥៥ លើក (៦៨%) ជារបស់ក្រុមហ៊ុនមានកុងត្រាប្រចាំឆ្នាំ (ចុះជួសជុលសម្រេចក្នុង ២៤ ម៉ោងតាម SLA) និង ២៥ លើកជារបស់ភ្ញៀវទូទៅ។",
    exampleEn: "80 service visits this month: 55 visits (68%) contract SLA clients resolved within 24h, 25 visits ad-hoc walk-ins.",
    href: "/contract-report",
    columns: [],
  },
  {
    id: "location-report",
    name: "Location & On-Site Log",
    nameKm: "Location & On-Site Log",
    category: "operations",
    categoryName: "Repair Operations",
    categoryNameKm: "ប្រតិបត្តិការជួសជុល",
    type: "excel",
    description: "On-site vs Workshop service ratio with geographical zone allocations.",
    descriptionKm: "វិភាគការបែងចែកភូមិសាស្ត្រនៃការផ្តល់សេវា និងរៀបចំកាលវិភាគបញ្ជូនជាងចុះទៅតាមតំបន់ឱ្យមានប្រសិទ្ធភាព។",
    databaseSource: "Services grouped by ServiceLocation (OnSite vs CompanyService), Address, Field Engineer",
    databaseSourceKm: "សំបុត្របែងចែកតាមទីតាំងសេវា (OnSite ចុះទៅកន្លែងអតិថិជន vs CompanyService ធ្វើនៅរោងជាង), អាសយដ្ឋាន, ជាងដែលចុះទៅ",
    businessPurpose: "Analyzes geographical distribution of on-site service calls to optimize field technician routing.",
    businessPurposeKm: "តាមដានថា «ជាងចុះទៅធ្វើដល់កន្លែងភ្ញៀវ (On-Site) ឬយកមកធ្វើនៅរោងជាង (Workshop)» ដើម្បីរៀបចំផ្លូវចុះទៅឱ្យលឿន។",
    columnsExplanationKm: [
      "• Date ៖ ថ្ងៃខែឆ្នាំនៃការផ្តល់សេវា",
      "• Report # ៖ លេខកូដសំបុត្រជួសជុល",
      "• Company ៖ ឈ្មោះក្រុមហ៊ុន ឬផ្ទះអតិថិជន",
      "• Location ៖ On-Site (ចុះទៅផ្ទាល់) ឬ Workshop (ធ្វើនៅរោងជាង)",
      "• Engineer ៖ ឈ្មោះជាងបច្ចេកទេសដែលបានចុះទៅទីតាំងផ្ទាល់",
      "• Item Name ៖ ម៉ូដែលម៉ាស៊ីន",
      "• Serial Number ៖ លេខ Serial Number",
      "• Status ៖ ស្ថានភាពបញ្ចប់ការងារ",
    ],
    columnsExplanationEn: [
      "• Date: Service date",
      "• Report #: Repair ticket code",
      "• Company: Customer organization name",
      "• Location: On-Site vs Workshop location",
      "• Engineer: Dispatched field engineer name",
      "• Item Name: Device model",
      "• Serial Number: Hardware serial number",
      "• Status: Lifecycle status",
    ],
    exampleKm: "ជាង ដារ៉ា ចុះទៅ On-Site នៅ ABA សាខាទួលគោក ២ គ្រឿង និងសាខាកណ្តាល ១ គ្រឿងក្នុងថ្ងៃតែមួយ ➔ ជួយសន្សំពេលវេលាធ្វើដំណើរ និងសាំងបានច្រើន។",
    exampleEn: "Tech Dara dispatched On-Site across ABA Toul Kork and Central branches in one optimized route, saving travel time.",
    href: "/location-report",
    columns: [],
  },
  {
    id: "history-report",
    name: "Ticket Audit & History Log",
    nameKm: "Ticket Audit & History Log",
    category: "operations",
    categoryName: "Repair Operations",
    categoryNameKm: "ប្រតិបត្តិការជួសជុល",
    type: "excel",
    description: "Complete chronological audit trail of who created, inspected, repaired, and approved every ticket.",
    descriptionKm: "សម្រាប់ធ្វើសវនកម្មលម្អិតលើប្រវត្តិសំបុត្រ ដើម្បីដឹងច្បាស់ថាបុគ្គលិកណាជាអ្នកទទួល ពិនិត្យ ជួសជុល និងអនុម័តចុងក្រោយ។",
    databaseSource: "CreatedBy, InspectBy, RepairBy, VerifiedBy, timestamps, and stage transition remarks",
    databaseSourceKm: "កាលប្បវត្តិនៃសំបុត្រ (CreatedBy, InspectBy, RepairBy, VerifiedBy, កាលបរិច្ឆេទកែប្រែ, Remarks)",
    businessPurpose: "Provides forensic accountability showing exact employee roles across every stage of the ticket.",
    businessPurposeKm: "ជា «កំណត់ត្រាសវនកម្មលម្អិត» ដឹងច្បាស់ថាបុគ្គលិកណាជាអ្នកទទួល ពិនិត្យ ជួសជុល និងអនុម័ត QA ការពារការប្រកែកគ្នា។",
    columnsExplanationKm: [
      "• Date ៖ ថ្ងៃខែឆ្នាំដែលទទួលសំបុត្រដំបូង",
      "• Report # ៖ លេខកូដសំបុត្រជួសជុល",
      "• Company ៖ ឈ្មោះក្រុមហ៊ុនអតិថិជន",
      "• Item Name ៖ ម៉ូដែលម៉ាស៊ីន",
      "• Inspection ៖ មូលហេតុខូចដែលជាងរកឃើញ",
      "• Solution ៖ វិធីដោះស្រាយ និងគ្រឿងបន្លាស់ដែលបានប្តូរ",
      "• Status ៖ ស្ថានភាពចុងក្រោយ",
    ],
    columnsExplanationEn: [
      "• Date: Ticket intake creation date",
      "• Report #: Repair ticket code",
      "• Company: Customer company name",
      "• Item Name: Device model",
      "• Inspection: Root cause diagnostic findings",
      "• Solution: Technical remedy and parts installed",
      "• Status: Final ticket lifecycle state",
    ],
    exampleKm: "សំបុត្រ #SR-089 ទទួលដោយ សុខា, ពិនិត្យដោយ ដារ៉ា, Approve តម្លៃដោយ វិច្ឆិកា, និង QA ដោយ Manager រិទ្ធ ➔ មានតម្លាភាព ១០០% ពេលភ្ញៀវសួរនាំ។",
    exampleEn: "Forensic audit for #SR-089: Created by Sokha, inspected by Dara, confirmed by Vicheka, QA verified by Manager Rith.",
    href: "/history-report",
    columns: [],
  },

  // ── 2. QUALITY & DIAGNOSTICS (2 Reports) ──
  {
    id: "faults-report",
    name: "Common Faults & Diagnostics",
    nameKm: "Common Faults & Diagnostics",
    category: "diagnostics",
    categoryName: "Quality & Diagnostics",
    categoryNameKm: "គុណភាព & វិភាគបញ្ហា",
    type: "excel",
    description: "Knowledge base of recurring hardware defects, root causes, and recommended solutions.",
    descriptionKm: "បង្កើតជា Knowledge Base សម្រាប់ជាងមើលជាគំរូបញ្ហាដែលកើតឡើងដដែលៗលើម៉ូដែលនីមួយៗ និងវិធីដោះស្រាយរហ័ស។",
    databaseSource: "ItemName (Model), CustomerRequest (Symptom), Inspection (Root Cause), Solution",
    databaseSourceKm: "ប្រមូលផ្តុំ ItemName (ម៉ូដែល), CustomerRequest (រោគសញ្ញា), Inspection (មូលហេតុពិត), Solution (វិធីដោះស្រាយ)",
    businessPurpose: "Creates an actionable diagnostic reference library for technicians to troubleshoot faster.",
    businessPurposeKm: "ជា «បណ្ណាល័យគន្លឹះដោះស្រាយបញ្ហា (Knowledge Base)» ប្រាប់ពីបញ្ហាដែលកើតឡើងដដែលៗលើម៉ូដែលនីមួយៗ និងវិធីដោះស្រាយរហ័ស។",
    columnsExplanationKm: [
      "• Date ៖ ថ្ងៃខែឆ្នាំដែលបានកត់ត្រាបញ្ហា",
      "• Report # ៖ លេខកូដសំបុត្រជួសជុល",
      "• Item Name ៖ ឈ្មោះម៉ូដែលម៉ាស៊ីន (ឧ. HP LaserJet M404)",
      "• Serial Number ៖ លេខ Serial Number ម៉ាស៊ីន",
      "• Reported Fault ៖ រោគសញ្ញាដែលភ្ញៀវប្រាប់ពេលយកមកផ្ញើ (ឧ. ស្ទះក្រដាស)",
      "• Inspection Finding ៖ មូលហេតុបច្ចេកទេសពិតប្រាកដដែលរកឃើញ (ឧ. Pickup Roller សឹក)",
      "• Applied Solution ៖ វិធីដោះស្រាយ និងគ្រឿងបន្លាស់ដែលត្រូវប្តូរ (ឧ. ប្តូរ Pickup Roller RM2-5452)",
    ],
    columnsExplanationEn: [
      "• Date: Diagnostic record date",
      "• Report #: Repair ticket code",
      "• Item Name: Device brand and model",
      "• Serial Number: Hardware serial number",
      "• Reported Fault: Customer reported problem symptom",
      "• Inspection Finding: True underlying technical defect discovered",
      "• Applied Solution: Verified repair procedure and replacement SKU",
    ],
    exampleKm: "ជាងថ្មីចូលធ្វើការ ឃើញម៉ាស៊ីន HP M404 ស្ទះក្រដាស ➔ បើកមើលរបាយការណ៍នេះដឹងភ្លាមថា ៨៥% បណ្តាលមកពី Pickup Roller សឹក មិនបាច់ចំណាយពេលរុះរើរាវរកយូរ ដូរ Roller ថ្មីជាការស្រេច។",
    exampleEn: "New technician sees HP M404 paper jam -> Checks knowledge base, finds 85% caused by worn roller -> Replaces RM2-5452 in 10 minutes.",
    href: "/faults-report",
    columns: [],
  },
  {
    id: "rejected-report",
    name: "Rejected Tickets & Returns Log",
    nameKm: "Rejected Tickets & Returns Log",
    category: "diagnostics",
    categoryName: "Quality & Diagnostics",
    categoryNameKm: "គុណភាព & វិភាគបញ្ហា",
    type: "excel",
    description: "Root-cause analysis for quotation declines, unrepairable units, and scrap inventory.",
    descriptionKm: "វិភាគរកមូលហេតុដែលអតិថិជនមិនព្រមជួសជុល (ឧ. ថ្លៃគ្រឿងបន្លាស់ខ្ពស់ពេក) និងម៉ាស៊ីនដែលខូចហួសពីលទ្ធភាពជួសជុល។",
    databaseSource: "Tickets with CustomerRejected or Unrepairable status, rejection reasons, and decider names",
    databaseSourceKm: "សំបុត្រដែល Customer Rejected ឬ Unrepairable, មូលហេតុបដិសេធ, ឈ្មោះអ្នកសម្រេចចិត្ត",
    businessPurpose: "Pinpoints why customers refuse repair quotes (e.g. high part costs) and logs dead hardware.",
    businessPurposeKm: "វិភាគមើលថា «ហេតុអ្វីបានជាអតិថិជនមិនព្រមជួសជុល ឬម៉ាស៊ីនណាដែលខូចជួសជុលលែងកើត» ដើម្បីកែលម្អតម្លៃ ឬបញ្ជូនឱ្យផ្នែកលក់។",
    columnsExplanationKm: [
      "• Date ៖ ថ្ងៃដែលភ្ញៀវបដិសេធមិនជួសជុល",
      "• Report # ៖ លេខកូដសំបុត្រ",
      "• Company ៖ ឈ្មោះក្រុមហ៊ុន ឬម្ចាស់ម៉ាស៊ីន",
      "• Item Name ៖ ម៉ូដែលម៉ាស៊ីនដែលខូច",
      "• Serial Number ៖ លេខកូដសម្គាល់ម៉ាស៊ីន",
      "• Customer Request ៖ រោគសញ្ញាដើមដែលភ្ញៀវយកមកផ្ញើ",
      "• Inspection / Reason ៖ មូលហេតុបដិសេធ (ឧ. តម្លៃគ្រឿងបន្លាស់ថ្លៃលើស ៥០% នៃម៉ាស៊ីនថ្មី, គ្រឿងបន្លាស់លែងមាន)",
      "• Decided By ៖ ឈ្មោះបុគ្គល ឬតំណាងដែលបានសម្រេចចិត្តបដិសេធ",
      "• Status ៖ Customer Rejected (ភ្ញៀវបដិសេធ) ឬ Unrepairable (ខូចធ្ងន់ធ្ងរ)",
    ],
    columnsExplanationEn: [
      "• Date: Decline timestamp",
      "• Report #: Repair ticket code",
      "• Company: Customer company name",
      "• Item Name: Failed equipment model",
      "• Serial Number: Factory serial number",
      "• Customer Request: Initial customer problem request",
      "• Inspection / Reason: Customer rationale for declining quotation or scrap reason",
      "• Decided By: Person who confirmed decline",
      "• Status: Customer Rejected or Unrepairable status",
    ],
    exampleKm: "ក្នុងចំណោម ៦ គ្រឿងដែលបដិសេធ មាន ៤ គ្រឿងភ្ញៀវមិនជួសជុលព្រោះថ្លៃប្តូរក្បាលព្រីន $160 ថ្លៃពេក ➔ បញ្ជូនទិន្នន័យនេះទៅឱ្យផ្នែកលក់ចុះទៅលក់ម៉ាស៊ីនថ្មី $199 ធានា ១ ឆ្នាំជូនភ្ញៀវវិញ។",
    exampleEn: "4 out of 6 declined repairs refused $160 printhead quote -> Sales routes hot lead offering new $199 printer with 1-year warranty.",
    href: "/rejected-report",
    columns: [],
  },

  // ── 3. TECHNICIAN KPIS (2 Reports) ──
  {
    id: "engineer-kpi-report",
    name: "Technician KPI & Efficiency Matrix",
    nameKm: "Technician KPI & Efficiency Matrix",
    category: "kpis",
    categoryName: "Technician KPIs",
    categoryNameKm: "សូចនាករ KPI ជាង",
    type: "excel",
    description: "Engineer scorecards with turnaround speed, fix success rates, active WIP, and performance grades.",
    descriptionKm: "វាយតម្លៃសមត្ថភាព និងប្រសិទ្ធភាពការងាររបស់ជាងបច្ចេកទេសម្នាក់ៗ ដើម្បីផ្តល់ការលើកទឹកចិត្ត (Incentives) ឬបណ្តុះបណ្តាលបន្ថែម។",
    databaseSource: "Aggregated by technician: Assigned, Finished, AvgDays, SuccessRate %, Active WIP, Grade A+/A/B/C",
    databaseSourceKm: "បូកសរុបតាមជាងម្នាក់ៗ៖ ចំនួនសំបុត្រដែលបានប្រគល់, ចំនួនជួសជុលរួច, រយៈពេលមធ្យម, អត្រាជោគជ័យ %, បន្ទុកការងារសកម្ម, និទ្ទេស Grade",
    businessPurpose: "Grades individual technician speed and success rates objectively for incentive programs.",
    businessPurposeKm: "ជា «តារាងពិន្ទុវាស់ស្ទង់សមត្ថភាពជាង (Scorecard)» ដើម្បីផ្តល់ប្រាក់រង្វាន់លើកទឹកចិត្ត (Incentive Bonus) ឬបណ្តុះបណ្តាលបន្ថែម។",
    columnsExplanationKm: [
      "• Rank ៖ ចំណាត់ថ្នាក់លេខរៀងជាងឆ្នើម (#1, #2, #3...)",
      "• Engineer Name ៖ ឈ្មោះជាងបច្ចេកទេស",
      "• Assigned Jobs ៖ ចំនួនសំបុត្រសរុបដែលបានប្រគល់ឱ្យធ្វើក្នុងខែ",
      "• Finished Jobs ៖ ចំនួនម៉ាស៊ីនដែលជួសជុលបានជោគជ័យ",
      "• MTTR / Avg Days ៖ រយៈពេលមធ្យមដែលជាងម្នាក់ៗចំណាយលើម៉ាស៊ីនមួយ (ល្បឿនជួសជុល)",
      "• Success Rate % ៖ ភាគរយជោគជ័យ (Finished / Assigned * 100)",
      "• Active WIP Load ៖ ចំនួនការងារសកម្មដែលកំពុងស្ថិតក្នុងដៃជាងនៅពេលនេះ",
      "• KPI Grade ៖ និទ្ទេសវាយតម្លៃ (Grade A+, A, B, C) សម្រាប់ផ្តល់ប្រាក់រង្វាន់",
    ],
    columnsExplanationEn: [
      "• Rank: Engineer leaderboard performance ranking",
      "• Engineer Name: Technician full name",
      "• Assigned Jobs: Total tickets dispatched to engineer",
      "• Finished Jobs: Tickets successfully repaired and verified",
      "• MTTR / Avg Days: Mean time to repair in days per ticket",
      "• Success Rate %: Completion rate percentage (Finished / Assigned)",
      "• Active WIP Load: Current active jobs in progress preventing overload",
      "• KPI Grade: Objective grading (A+, A, B, C) for incentive bonuses",
    ],
    exampleKm: "ជាង សុខ ទទួល ៤៥ គ្រឿង ជួសជុលរួច ៤៤ (ជោគជ័យ ៩៨%), ធ្វើលឿនត្រឹម ១.២ ថ្ងៃក្នុងមួយគ្រឿង ➔ ទទួលបាន Grade A+ 🌟 និងប្រាក់រង្វាន់លើកទឹកចិត្តពេញ។",
    exampleEn: "Tech Sok: 45 assigned, 44 finished (98% success rate), 1.2 days avg turnaround -> Awarded Grade A+ bonus.",
    href: "/engineer-kpi-report",
    columns: [],
  },
  {
    id: "engineer-report",
    name: "Engineer Workload & Job Ledger",
    nameKm: "Engineer Workload & Job Ledger",
    category: "kpis",
    categoryName: "Technician KPIs",
    categoryNameKm: "សូចនាករ KPI ជាង",
    type: "excel",
    description: "Active work-in-progress queue per technician to prevent task overload.",
    descriptionKm: "មើលទំហំបន្ទុកការងារជាក់ស្តែងរបស់ជាង ដើម្បីបែងចែកការងារថ្មីៗកុំឱ្យមានការកកស្ទះលើជាងតែម្នាក់។",
    databaseSource: "Active tickets in Repairing/Inspecting statuses grouped by assigned technician ID",
    databaseSourceKm: "បញ្ជីសំបុត្រសកម្មទាំងអស់ដែលកំពុងកាន់កាប់ដោយជាងម្នាក់ៗ និងស្ថានភាពបច្ចុប្បន្ន",
    businessPurpose: "Real-time workbench overview ensuring fair and balanced task distribution among engineers.",
    businessPurposeKm: "មើលថា «ជាងម្នាក់ៗកំពុងកាន់ការងារប៉ុន្មានក្នុងដៃជាក់ស្តែង» ដើម្បីកុំឱ្យការងារកកស្ទះលើជាងតែម្នាក់។",
    columnsExplanationKm: [
      "• Date ៖ ថ្ងៃខែឆ្នាំដែលទទួលសំបុត្រ",
      "• Report # ៖ លេខកូដសំបុត្រជួសជុល",
      "• Company ៖ ឈ្មោះក្រុមហ៊ុន ឬអតិថិជន",
      "• Item Name ៖ ម៉ូដែលឧបករណ៍",
      "• Serial Number ៖ លេខកូដសម្គាល់ម៉ាស៊ីន",
      "• Days ៖ ចំនួនថ្ងៃដែលសំបុត្រនេះកំពុងស្ថិតក្នុងដៃជាង",
      "• Status ៖ ដំណាក់កាលការងារបច្ចុប្បន្ន (Inspecting, Repairing, Awaiting Sparepart)",
    ],
    columnsExplanationEn: [
      "• Date: Ticket intake timestamp",
      "• Report #: Repair ticket code",
      "• Company: Customer company name",
      "• Item Name: Hardware device model",
      "• Serial Number: Factory unique serial number",
      "• Days: Elapsed days currently held by engineer",
      "• Status: Active workbench status",
    ],
    exampleKm: "ជាង ដារ៉ា កំពុងកាន់ការងារ ៨ គ្រឿង (Overload កកស្ទះ) ខណៈជាង វិបុល កំពុងកាន់តែ ២ គ្រឿង ➔ ប្រធានរោងជាងបង្វែរសំបុត្រថ្មីទៅឱ្យជាង វិបុល ភ្លាម។",
    exampleEn: "Tech Dara holds 8 WIP tickets (overloaded), Tech Vibul holds 2 -> Supervisor distributes incoming orders to Vibul.",
    href: "/engineer-report",
    columns: [],
  },

  // ── 4. SALES & CRM (7 Reports) ──
  {
    id: "customer-report",
    name: "Customer Analytics & Service Ledger",
    nameKm: "Customer Analytics & Service Ledger",
    category: "sales",
    categoryName: "Sales & CRM",
    categoryNameKm: "ផ្នែកលក់ & អតិថិជន",
    type: "excel",
    description: "Historical repair volumes, spending totals, and lifecycle metrics per corporate account.",
    descriptionKm: "ផ្តល់ទិដ្ឋភាពប្រវត្តិសេវាកម្មទាំងមូលរបស់អតិថិជនម្នាក់ៗ (Customer Lifetime Service Value)។",
    databaseSource: "Customer companies, contact persons, phones, ticket volume, lifetime service spend",
    databaseSourceKm: "ឈ្មោះក្រុមហ៊ុនអតិថិជន, អ្នកទំនាក់ទំនង, លេខទូរស័ព្ទ, ចំនួនសំបុត្រសរុប, ចំណាយសរុបលើការជួសជុល",
    businessPurpose: "Measures customer lifetime service value and long-term maintenance engagement.",
    businessPurposeKm: "មើល «ប្រវត្តិជួសជុល និងទំហំចំណាយសរុបរបស់អតិថិជនម្នាក់ៗ (Customer Lifetime Value)»។",
    columnsExplanationKm: [
      "• Date ៖ ថ្ងៃខែឆ្នាំដែលទទួលសេវា",
      "• Report # ៖ លេខកូដសំបុត្រជួសជុល",
      "• Contact ៖ ឈ្មោះអ្នកទំនាក់ទំនងនៅក្រុមហ៊ុនអតិថិជន",
      "• Phone ៖ លេខទូរស័ព្ទទំនាក់ទំនង",
      "• Item Name ៖ ម៉ូដែលឧបករណ៍ដែលបានជួសជុល",
      "• Serial Number ៖ លេខ Serial Number សម្គាល់ម៉ាស៊ីន",
      "• Status ៖ ស្ថានភាពសំបុត្រ",
    ],
    columnsExplanationEn: [
      "• Date: Service date timestamp",
      "• Report #: Repair ticket code",
      "• Contact: Contact person at customer organization",
      "• Phone: Direct contact phone number",
      "• Item Name: Device model",
      "• Serial Number: Hardware serial number",
      "• Status: Ticket lifecycle state",
    ],
    exampleKm: "ធនាគារ Canadia យកម៉ាស៊ីនមកជួសជុលសរុប ៤៨ លើកក្នុងមួយឆ្នាំ ចំណាយសរុប $3,650 (ម៉ាស៊ីនជួសជុលញឹកញាប់ជាងគេគឺ Passbook Printer)។",
    exampleEn: "Canadia Bank logged 48 repair tickets this year totaling $3,650 spend (mostly passbook printers).",
    href: "/customer-report",
    columns: [],
  },
  {
    id: "top-customers-report",
    name: "Top Revenue Customers Ranking",
    nameKm: "Top Revenue Customers Ranking",
    category: "sales",
    categoryName: "Sales & CRM",
    categoryNameKm: "ផ្នែកលក់ & អតិថិជន",
    type: "excel",
    description: "VIP Tier rankings (Platinum, Gold, Silver) based on repair billing revenue.",
    descriptionKm: "កំណត់អត្តសញ្ញាណអតិថិជនធំៗ (Key Accounts) ដែលនាំចំណូលច្រើនជាងគេ ដើម្បីផ្តល់ការថែទាំពិសេស។",
    databaseSource: "Companies ranked by service revenue, ticket volume, parts consumed, VIP Tier",
    databaseSourceKm: "ចំណាត់ថ្នាក់ក្រុមហ៊ុនតាមចំណូលសេវា, ចំនួនសំបុត្រ, ចំនួនគ្រឿងបន្លាស់ដែលបានប្រើ, ចំណាត់ថ្នាក់ Tier",
    businessPurpose: "Identifies key accounts driving the majority of service revenues for dedicated VIP support.",
    businessPurposeKm: "រៀបចំណាត់ថ្នាក់ «អតិថិជន VIP ធំៗដែលនាំចំណូលច្រើនជាងគេ (Key Accounts)» ដើម្បីផ្តល់ការថែទាំពិសេស។",
    columnsExplanationKm: [
      "• Rank ៖ ចំណាត់ថ្នាក់លេខរៀងក្រុមហ៊ុននាំចំណូលច្រើន (#1, #2, #3...)",
      "• Company Name ៖ ឈ្មោះក្រុមហ៊ុនអតិថិជនធំៗ",
      "• Customer Type ៖ ប្រភេទអតិថិជនពី Customer Master (ឧ. Bank, Ministry, Insurance...)",
      "• Total Jobs ៖ ចំនួនសំបុត្រជួសជុលសរុបដែលបានកត់ត្រា",
      "• Finished ៖ ចំនួនម៉ាស៊ីនដែលជួសជុលបានជោគជ័យ",
      "• Chargeable Jobs ៖ ចំនួនការងារដែលគិតថ្លៃសេវា (Charge)",
      "• Parts Used ៖ ចំនួនគ្រាប់គ្រឿងបន្លាស់ដែលបានប្រើប្រាស់",
      "• Account Tier ៖ កម្រិត VIP (Platinum, Gold, Silver, Bronze)",
    ],
    columnsExplanationEn: [
      "• Rank: Revenue rank leaderboard order",
      "• Company Name: Enterprise key account name",
      "• Customer Type: Client category from Customer Master (e.g. Bank, Ministry, Insurance...)",
      "• Total Jobs: Total historical repair orders",
      "• Finished: Successfully repaired tickets",
      "• Chargeable Jobs: Billed service order count",
      "• Parts Used: Volume of replacement parts consumed",
      "• Account Tier: Loyalty tier classification (Platinum, Gold, Silver)",
    ],
    exampleKm: "#1 ធនាគារ ABA ($8,500/ឆ្នាំ - Platinum VIP) ➔ ទទួលបានសិទ្ធិអាទិភាពជួសជុលលឿនជាងគេ និងមានអ្នកមើលថែផ្ទាល់។",
    exampleEn: "#1 ABA Bank ($8,500/year - Platinum VIP) receives priority turnaround SLA and designated account manager.",
    href: "/top-customers-report",
    columns: [],
  },
  {
    id: "sales-conversion-report",
    name: "Sales Conversion & Win Rate",
    nameKm: "Sales Conversion & Win Rate",
    category: "sales",
    categoryName: "Sales & CRM",
    categoryNameKm: "ផ្នែកលក់ & អតិថិជន",
    type: "excel",
    description: "Quotation conversion efficiency (Sale Confirmed vs Customer Rejected) and deal closing speed.",
    descriptionKm: "វាស់វែងអត្រាជោគជ័យរបស់ផ្នែកលក់ (Win/Loss Rate) ក្នុងការបញ្ចុះបញ្ចូលអតិថិជនឱ្យយល់ព្រមលើសម្រង់តម្លៃជួសជុល។",
    databaseSource: "Quotations with Sale Confirmed vs Customer Rejected status, quotation values, closing days",
    databaseSourceKm: "សំបុត្រដែលមានស្ថានភាព Sale Confirmed vs Customer Rejected, តម្លៃ Quotation, រយៈពេលសម្រេចចិត្ត",
    businessPurpose: "Measures sales team win rate in converting diagnostic quotes into billable repair orders.",
    businessPurposeKm: "វាស់ «អត្រាជោគជ័យក្នុងការបិទការលក់របស់ផ្នែកលក់ (Win/Loss Rate)» លើសម្រង់តម្លៃជួសជុល។",
    columnsExplanationKm: [
      "• Decision Date ៖ ថ្ងៃខែឆ្នាំដែលអតិថិជនឆ្លើយតបលើសម្រង់តម្លៃ",
      "• Report # ៖ លេខកូដសំបុត្រ",
      "• Company ៖ ឈ្មោះក្រុមហ៊ុនអតិថិជន",
      "• Item Name ៖ ម៉ូដែលម៉ាស៊ីន",
      "• Sales Rep ៖ ឈ្មោះបុគ្គលិកផ្នែកលក់ដែលកាន់ការងារសម្រង់តម្លៃនេះ",
      "• Closing Days ៖ ចំនួនថ្ងៃគិតចាប់ពីថ្ងៃផ្ញើ Quote រហូតដល់ភ្ញៀវឆ្លើយតប",
      "• Outcome ៖ ជោគជ័យ (Won / Sale Confirmed) ឬបរាជ័យ (Lost / Rejected)",
      "• Status ៖ ស្ថានភាពសំបុត្រជាក់ស្តែង",
    ],
    columnsExplanationEn: [
      "• Decision Date: Timestamp of quotation confirmation or rejection",
      "• Report #: Repair ticket code",
      "• Company: Customer organization name",
      "• Item Name: Hardware model",
      "• Sales Rep: Account sales representative",
      "• Closing Days: Duration in days from quote dispatch to decision",
      "• Outcome: Won (Sale Confirmed) vs Lost (Customer Rejected)",
      "• Status: Live lifecycle status",
    ],
    exampleKm: "ក្នុងខែសីហា ផ្ញើសម្រង់តម្លៃ ៥០ សំបុត្រ ➔ ភ្ញៀវយល់ព្រម ៤២ សំបុត្រ (Sale Confirmed) និងបដិសេធ ៨ សំបុត្រ (Win Rate = 84%)។",
    exampleEn: "August conversion: 50 quotes submitted -> 42 confirmed, 8 declined (84% win rate).",
    href: "/sales-conversion-report",
    columns: [],
  },
  {
    id: "sales-leads-report",
    name: "Sales Leads & New Machine Inquiries",
    nameKm: "Sales Leads & New Machine Inquiries",
    category: "sales",
    categoryName: "Sales & CRM",
    categoryNameKm: "ផ្នែកលក់ & អតិថិជន",
    type: "excel",
    description: "Hot leads generated from unrepairable and quote-rejected devices for new machine sales reps.",
    descriptionKm: "ប្រភពទិន្នន័យនាំមុខ (Hot Leads) សម្រាប់ផ្នែកលក់ ក្នុងការទាក់ទងទៅអតិថិជនដើម្បីស្នើលក់ម៉ាស៊ីនថ្មីជំនួសម៉ាស៊ីនចាស់ដែលខូចជួសជុលលែងកើត។",
    databaseSource: "Tickets with Unrepairable and Customer Rejected statuses, broken machine specs, customer contacts",
    databaseSourceKm: "សំបុត្រដែលមានស្ថានភាព Unrepairable និង Customer Rejected, ព័ត៌មានម៉ាស៊ីនខូច, ព័ត៌មានទំនាក់ទំនង",
    businessPurpose: "Feeds hot replacement sales opportunities to hardware account executives immediately.",
    businessPurposeKm: "ផ្តល់ «ឱកាសលក់ម៉ាស៊ីនថ្មី (Hot Leads)» ពីម៉ាស៊ីនចាស់ៗដែលខូចជួសជុលលែងកើត ជូនដល់ផ្នែកលក់ភ្លាមៗ។",
    columnsExplanationKm: [
      "• Date ៖ ថ្ងៃខែឆ្នាំដែលសំបុត្រត្រូវបានកំណត់ថាខូចធ្ងន់ធ្ងរ",
      "• Report # ៖ លេខកូដសំបុត្រ",
      "• Company ៖ ឈ្មោះក្រុមហ៊ុន ឬអតិថិជនម្ចាស់ម៉ាស៊ីន",
      "• Contact Person ៖ ឈ្មោះតំណាងអតិថិជន",
      "• Phone Number ៖ លេខទំនាក់ទំនងសម្រាប់ឱ្យផ្នែកលក់ទូរស័ព្ទទៅភ្លាមៗ",
      "• Item Model ៖ ម៉ាក និងម៉ូដែលម៉ាស៊ីនចាស់ដែលខូច",
      "• Diagnosis / Reason ៖ មូលហេតុខូចធ្ងន់ធ្ងរ ឬតម្លៃជួសជុលថ្លៃពេក",
      "• Status ៖ Unrepairable (ជួសជុលមិនកើត) ឬ Customer Rejected (ភ្ញៀវបដិសេធ)",
    ],
    columnsExplanationEn: [
      "• Date: Lead generation timestamp",
      "• Report #: Repair ticket code",
      "• Company: Customer company name",
      "• Contact Person: Primary client representative",
      "• Phone Number: Direct phone number for immediate outreach",
      "• Item Model: Failed equipment model",
      "• Diagnosis / Reason: Heavy damage reason or quote rejection justification",
      "• Status: Unrepairable or Customer Rejected",
    ],
    exampleKm: "ម៉ាស៊ីនព្រីនចាស់របស់សាលារៀនខូច Mainboard រកគ្រឿងបន្លាស់លែងបាន ➔ ផ្នែកលក់ទូរស័ព្ទទៅស្នើលក់ម៉ាស៊ីនស៊េរីថ្មី $199 ធានា ១ ឆ្នាំ បិទការលក់បានភ្លាមៗ!",
    exampleEn: "School's old printer mainboard obsolete -> Sales calls offering new $199 unit with 1-year warranty, closing deal immediately.",
    href: "/sales-leads-report",
    columns: [],
  },
  {
    id: "contract-renewal-report",
    name: "Contract Renewal & Expiry Tracker",
    nameKm: "Contract Renewal & Expiry Tracker",
    category: "sales",
    categoryName: "Sales & CRM",
    categoryNameKm: "ផ្នែកលក់ & អតិថិជន",
    type: "excel",
    description: "Upcoming maintenance contract expirations and frequent walk-in customers ready for annual SLA.",
    descriptionKm: "ជូនដំណឹងដល់ផ្នែកលក់ឱ្យចុះទៅបន្តកិច្ចសន្យាថែទាំ ឬស្នើកិច្ចសន្យាប្រចាំឆ្នាំថ្មីដល់អតិថិជនដែលមកជួសជុលញឹកញាប់។",
    databaseSource: "Expiring service contracts (within 30/60 days) and frequent walk-in accounts (>=3 visits)",
    databaseSourceKm: "ក្រុមហ៊ុនដែលមានកុងត្រាជិតផុតកំណត់ និងក្រុមហ៊ុនដែលយកម៉ាស៊ីនមកជួសជុលញឹកញាប់",
    businessPurpose: "Prevents maintenance contract churn and converts frequent ad-hoc repair customers into SLA retainers.",
    businessPurposeKm: "ដាស់តឿនឱ្យផ្នែកលក់ «ចុះទៅបន្តកិច្ចសន្យាថែទាំប្រចាំឆ្នាំមុនថ្ងៃផុតកំណត់» ការពារកុំឱ្យបាត់បង់អតិថិជន។",
    columnsExplanationKm: [
      "• Company Name ៖ ឈ្មោះក្រុមហ៊ុនអតិថិជន",
      "• Customer Type ៖ ប្រភេទអតិថិជនពី Customer Master (ឧ. Bank, Ministry, Insurance...)",
      "• Contact Person ៖ ឈ្មោះតំណាងទំនាក់ទំនង",
      "• Phone Number ៖ លេខទូរស័ព្ទទំនាក់ទំនង",
      "• Contract Status ៖ Active (សកម្ម), Expiring Soon (ជិតផុត <= 30 ថ្ងៃ), ឬ Expired (ផុតកំណត់)",
      "• Total Repairs ៖ ចំនួនដងសរុបដែលធ្លាប់យកម៉ាស៊ីនមកជួសជុល",
      "• Last Service Date ៖ កាលបរិច្ឆេទជួសជុលចុងក្រោយបំផុត",
      "• Suggested Action ៖ សកម្មភាពណែនាំ (ឧ. Renew SLA Contract / Pitch Maintenance SLA)",
    ],
    columnsExplanationEn: [
      "• Company Name: Customer organization name",
      "• Customer Type: Client category from Customer Master (e.g. Bank, Ministry, Insurance...)",
      "• Contact Person: Client representative name",
      "• Phone Number: Phone contact",
      "• Contract Status: Active, Expiring Soon, or Expired",
      "• Total Repairs: Cumulative repair frequency",
      "• Last Service Date: Most recent maintenance visit",
      "• Suggested Action: Recommended sales pitch (Renew SLA / Pitch Contract)",
    ],
    exampleKm: "កុងត្រាថែទាំម៉ាស៊ីន ៣០ គ្រឿងរបស់ក្រសួងរៀបចំដែនដី នៅសល់ ២៥ ថ្ងៃទៀតផុតកំណត់ ➔ ប្រព័ន្ធ Alert ឱ្យផ្នែកលក់ចុះទៅបន្តកុងត្រាថ្មីមុនថ្ងៃផុតកំណត់បានជោគជ័យ។",
    exampleEn: "Ministry SLA for 30 printers expiring in 25 days -> Automated alert prompts sales manager to secure contract renewal.",
    href: "/contract-renewal-report",
    columns: [],
  },
  {
    id: "confirmed-sale",
    name: "Confirmed Repair Sales & Orders",
    nameKm: "Confirmed Repair Sales & Orders",
    category: "sales",
    categoryName: "Sales & CRM",
    categoryNameKm: "ផ្នែកលក់ & អតិថិជន",
    type: "excel",
    description: "Approved repair work orders ready for accounting invoice billing and parts fulfillment.",
    descriptionKm: "បញ្ជីការងារដែលបានអនុម័ត សម្រាប់ផ្នែកគណនេយ្យរៀបចំចេញវិក្កយបត្រ (Invoice Billing)។",
    databaseSource: "Tickets in Sale Confirmed status, total approved quote amounts, confirmation dates",
    databaseSourceKm: "សំបុត្រដែលបានបញ្ជាក់តម្លៃរួចរាល់ (Sale Confirmed), តម្លៃសរុប, កាលបរិច្ឆេទបញ្ជាក់",
    businessPurpose: "Enables accounting to invoice approved repair jobs and track accounts receivable.",
    businessPurposeKm: "ជា «បញ្ជីការងារដែលភ្ញៀវយល់ព្រមតម្លៃរួច» សម្រាប់គណនេយ្យចេញវិក្កយបត្រ (Invoice Billing) និងកាត់កម្រៃជើងសារ។",
    columnsExplanationKm: [
      "• Report No ៖ លេខកូដសំបុត្រដែលភ្ញៀវបានបញ្ជាក់យល់ព្រម",
      "• Service Date ៖ ថ្ងៃខែឆ្នាំដែលទទួលម៉ាស៊ីន",
      "• Customer Name ៖ ឈ្មោះក្រុមហ៊ុន ឬម្ចាស់ឧបករណ៍",
      "• Phone Number ៖ លេខទំនាក់ទំនងអតិថិជន",
      "• Item Name ៖ ម៉ាក និងម៉ូដែលឧបករណ៍",
      "• Serial Number ៖ លេខ Serial Number ម៉ាស៊ីន",
      "• Status ៖ Sale Confirmed (ភ្ញៀវយល់ព្រមតម្លៃ)",
      "• Total Price ($) ៖ ទឹកប្រាក់សរុបដែលបានយល់ព្រម សម្រាប់ឱ្យគណនេយ្យចេញ Invoice",
    ],
    columnsExplanationEn: [
      "• Report No: Confirmed service ticket code",
      "• Service Date: Machine intake date",
      "• Customer Name: Customer corporate name",
      "• Phone Number: Client phone contact",
      "• Item Name: Device brand and model",
      "• Serial Number: Hardware serial number",
      "• Status: Sale Confirmed status badge",
      "• Total Price ($): Total confirmed billing amount for accounts receivable",
    ],
    exampleKm: "ថ្ងៃនេះមានសំបុត្រចំនួន ១២ ដែលភ្ញៀវទើបនឹង Confirm សរុបទឹកប្រាក់ $1,450 ➔ គណនេយ្យទាញយកបញ្ជីនេះចេញវិក្កយបត្រទារប្រាក់បានភ្លាមៗ។",
    exampleEn: "12 approved tickets today totaling $1,450 -> Accounting exports list to generate invoices immediately.",
    href: "/confirmed-sale",
    columns: [],
  },
  {
    id: "waiting-confirm",
    name: "Waiting Customer Approval Aging",
    nameKm: "Waiting Customer Approval Aging",
    category: "sales",
    categoryName: "Sales & CRM",
    categoryNameKm: "ផ្នែកលក់ & អតិថិជន",
    type: "excel",
    description: "Pending quotations ranked by aging days to prioritize urgent sales follow-up calls.",
    descriptionKm: "ជួយផ្នែកលក់តាមដានសម្រង់តម្លៃដែលរង់ចាំយូរថ្ងៃ (Aging) ដើម្បីទូរស័ព្ទទៅ Follow-up អតិថិជនឱ្យបានទាន់ពេល។",
    databaseSource: "Pending quotations in Awaiting Customer Confirm status with calculated Pending Days",
    databaseSourceKm: "សម្រង់តម្លៃដែលកំពុងរង់ចាំការឆ្លើយតបពីអតិថិជន គិតជាចំនួនថ្ងៃរង់ចាំ (Pending Days)",
    businessPurpose: "Prevents quote stagnation by prompting sales reps to call clients whose approvals have stalled.",
    businessPurposeKm: "តាមដាន «សម្រង់តម្លៃដែលផ្ញើទៅហើយតែភ្ញៀវមិនទាន់ឆ្លើយតប (Aging)» ដើម្បីឱ្យផ្នែកលក់ទូរស័ព្ទទៅ Follow-up។",
    columnsExplanationKm: [
      "• Report No ៖ លេខកូដសំបុត្រដែលកំពុងរង់ចាំការឆ្លើយតប",
      "• Service Date ៖ ថ្ងៃខែឆ្នាំដែលទទួលម៉ាស៊ីន",
      "• Customer Name ៖ ឈ្មោះក្រុមហ៊ុន ឬអតិថិជន",
      "• Phone Number ៖ លេខទំនាក់ទំនងសម្រាប់ទូរស័ព្ទទៅ Follow-up",
      "• Item Name ៖ ម៉ូដែលឧបករណ៍",
      "• Serial Number ៖ លេខ Serial Number",
      "• Status ៖ Awaiting Customer Confirm (រង់ចាំភ្ញៀវយល់ព្រម)",
      "• Quoted Price ($) ៖ ទឹកប្រាក់ដែលបានសម្រង់ជូនភ្ញៀវ",
      "• Days Waiting ៖ ចំនួនថ្ងៃរង់ចាំ (បើលើស ៣ ថ្ងៃ ឡើងពណ៌ក្រហម Flag Alert)",
    ],
    columnsExplanationEn: [
      "• Report No: Pending quote ticket number",
      "• Service Date: Intake timestamp",
      "• Customer Name: Customer entity name",
      "• Phone Number: Phone contact for follow-up call",
      "• Item Name: Device model",
      "• Serial Number: Hardware serial number",
      "• Status: Awaiting Customer Confirm badge",
      "• Quoted Price ($): Quoted service fee",
      "• Days Waiting: Elapsed waiting days (red alert if >3 days)",
    ],
    exampleKm: "សំបុត្រ #SR-045 ផ្ញើតម្លៃ $85 ទៅភ្ញៀវ ៥ ថ្ងៃហើយនៅស្ងាត់ (Days Waiting = 5) ➔ ផ្នែកលក់ទូរស័ព្ទទៅសួរនាំ និងពន្យល់បន្ថែមដើម្បីជំរុញការសម្រេចចិត្ត។",
    exampleEn: "Ticket #SR-045 quote ($85) pending for 5 days -> Red alert triggers sales rep follow-up call.",
    href: "/waiting-confirm",
    columns: [],
  },

  // ── 5. SPARE PARTS & STOCK (8 Reports) ──
  {
    id: "sparepart-usage-report",
    name: "Spare Parts Consumption & Usage",
    nameKm: "Spare Parts Consumption & Usage",
    category: "stock",
    categoryName: "Spare Parts & Stock",
    categoryNameKm: "គ្រឿងបន្លាស់ & ស្តុក",
    type: "excel",
    description: "Quantity and cost of spare parts consumed in repair jobs vs manual shop consumption.",
    descriptionKm: "តាមដានបរិមាណគ្រឿងបន្លាស់ដែលបានប្រើប្រាស់ជាក់ស្តែងក្នុងអំឡុងពេលណាមួយ និងចំណាយដើមសរុប។",
    databaseSource: "Endpoint /spareparts/usage: PartCode, serviceUsedQty, manualUsedQty, totalCost",
    databaseSourceKm: "ទិន្នន័យពី /spareparts/usage៖ កូដគ្រឿងបន្លាស់, បរិមាណប្រើក្នុងសេវា, បរិមាណដកដោយដៃ, ចំណាយសរុប",
    businessPurpose: "Audits actual physical part consumption and total cost of goods across all repair jobs.",
    businessPurposeKm: "ដឹងពី «ចំនួនគ្រឿងបន្លាស់ដែលបានដកប្រើប្រាស់ពិតប្រាកដក្នុងខែ» និងចំណាយថ្លៃដើមសរុប។",
    columnsExplanationKm: [
      "• Spare Part ៖ ឈ្មោះ និងមុខងាររបស់គ្រឿងបន្លាស់",
      "• Serial Number ៖ លេខកូដសម្គាល់គ្រឿងបន្លាស់ (Part SKU)",
      "• Stock Qty ៖ ចំនួនស្តុកដែលមានក្នុងឃ្លាំងបច្ចុប្បន្ន",
      "• Used Qty ៖ ចំនួនគ្រាប់សរុបដែលបានដកប្រើប្រាស់",
      "• From Service ៖ ចំនួនគ្រាប់ដែលបានដកយកទៅប្រើលើសំបុត្រជួសជុលជាក់ស្តែង",
      "• Manual Out ៖ ចំនួនគ្រាប់ដែលដកចេញក្រៅសេវាជួសជុល (Internal usage)",
      "• Usage Count ៖ ចំនួនលើកសរុបដែលមានការដកគ្រឿងបន្លាស់នេះ",
    ],
    columnsExplanationEn: [
      "• Spare Part: Part item name and specifications",
      "• Serial Number: Unique part SKU or serial number",
      "• Stock Qty: Live warehouse shelf quantity",
      "• Used Qty: Total cumulative quantity consumed",
      "• From Service: Quantity consumed across repair work orders",
      "• Manual Out: Quantity issued for manual non-ticket operations",
      "• Usage Count: Total frequency count of part issuances",
    ],
    exampleKm: "Fuser Film Sleeve ត្រូវបានដកប្រើចំនួន ៣១ គ្រាប់ (តម្លៃដើមសរុប $465) លើសំបុត្រជួសជុលជាក់ស្តែងចំនួន ២៨ សំបុត្រ។",
    exampleEn: "31 Fuser Film Sleeves consumed ($465 total COGS) across 28 active repair tickets.",
    href: "/sparepart-usage",
    columns: [],
  },
  {
    id: "sparepart-hold-report",
    name: "Spare Parts on Hold & Allocation",
    nameKm: "Spare Parts on Hold & Allocation",
    category: "stock",
    categoryName: "Spare Parts & Stock",
    categoryNameKm: "គ្រឿងបន្លាស់ & ស្តុក",
    type: "excel",
    description: "Reserved inventory allocated to open jobs that must not be re-issued.",
    descriptionKm: "ដឹងពីចំនួនស្តុកដែលត្រូវបានកក់ទុក ជៀសវាងការច្រឡំថាស្តុកនៅសល់អាចយកទៅប្រើលើសំបុត្រផ្សេងទៀតបាន។",
    databaseSource: "Endpoint /spareparts/hold: Parts reserved in active tickets with OnHold quantities",
    databaseSourceKm: "ទិន្នន័យពី /spareparts/hold៖ គ្រឿងបន្លាស់ដែលកំពុងត្រូវបានកក់ទុកសម្រាប់សំបុត្រដែលភ្ញៀវ Confirm រួច",
    businessPurpose: "Prevents double-allocation of parts by quarantining units assigned to confirmed jobs.",
    businessPurposeKm: "ដឹងពី «ចំនួនស្តុកដែលត្រូវបានកក់ទុក (Hold)» កុំឱ្យច្រឡំយកទៅប្រើលើការងារផ្សេង។",
    columnsExplanationKm: [
      "• Spare Part ៖ ឈ្មោះគ្រឿងបន្លាស់",
      "• Serial Number ៖ លេខកូដសម្គាល់គ្រឿងបន្លាស់ (SKU)",
      "• Current Stock ៖ ចំនួនគ្រាប់សរុបដែលមាននៅលើធ្នើរឃ្លាំង",
      "• Hold Qty ៖ ចំនួនដែលត្រូវបានកក់ទុក (Reserved) សម្រាប់សំបុត្រដែលភ្ញៀវបាន Approve រួច",
      "• Effective Stock ៖ ចំនួនស្តុកពិតប្រាកដដែលនៅទំនេរ អាចសន្យាជាមួយភ្ញៀវថ្មីបាន (Current Stock ដក Hold Qty)",
      "• Hold Jobs ៖ ចំនួនសំបុត្រជួសជុលដែលកំពុងកក់គ្រឿងបន្លាស់នេះ",
    ],
    columnsExplanationEn: [
      "• Spare Part: Part description",
      "• Serial Number: Stock SKU / Serial identifier",
      "• Current Stock: Total units sitting on warehouse shelf",
      "• Hold Qty: Reserved allocation quantity locked for confirmed jobs",
      "• Effective Stock: Truly available free stock (Current Stock minus Hold Qty)",
      "• Hold Jobs: Count of active repair orders holding this item",
    ],
    exampleKm: "Pickup Roller មានលើធ្នើរ ៨ គ្រាប់ ប៉ុន្តែ ៥ គ្រាប់ត្រូវបានកក់ទុក (Hold) ➔ ស្តុកទំនេរពិតប្រាកដ (Effective Stock) សល់តែ ៣ គ្រាប់ប៉ុណ្ណោះ។",
    exampleEn: "Pickup Roller: 8 on shelf, but 5 are on hold -> Effective available stock for new tickets is 3 units.",
    href: "/sparepart-hold",
    columns: [],
  },
  {
    id: "stock-transactions-report",
    name: "Stock Transaction Ledger",
    nameKm: "Stock Transaction Ledger",
    category: "stock",
    categoryName: "Spare Parts & Stock",
    categoryNameKm: "គ្រឿងបន្លាស់ & ស្តុក",
    type: "excel",
    description: "Immutable double-entry audit trail for every In, Out, and Reversal stock movement.",
    descriptionKm: "តាមដានប្រវត្តិនាំចូល ដកចេញ និងការប្រគល់ត្រឡប់នៃគ្រឿងបន្លាស់គ្រប់គ្រាប់យ៉ាងលម្អិត ១០០%។",
    databaseSource: "SparepartStockAuditLog: TransactionType, BalanceBefore, BalanceAfter, QtyChange, Authorizer",
    databaseSourceKm: "សៀវភៅកត់ត្រាចលនាស្តុកគ្រប់ប្រភេទ (SparepartStockAuditLog)៖ In, Out, Balance Before, Balance After, Authorizer, Reversals",
    businessPurpose: "Guarantees 100% financial and physical inventory auditability, eliminating shrinkage.",
    businessPurposeKm: "ជា «សៀវភៅកត់ត្រាចលនាស្តុកគ្រប់ជំហាន» មិនឱ្យបាត់បង់គ្រឿងបន្លាស់សូម្បីតែ ១ គ្រាប់។",
    columnsExplanationKm: [
      "• Date / Time ៖ ថ្ងៃខែឆ្នាំ និងម៉ោងនាទីជាក់ស្តែងនៃចលនាស្តុក",
      "• Spare Part ៖ ឈ្មោះគ្រឿងបន្លាស់",
      "• Serial Number ៖ លេខកូដសម្គាល់គ្រឿងបន្លាស់",
      "• Type ៖ IN (នាំចូល), OUT (ដកចេញជួសជុល), REVERSAL (បង្វិលចូលវិញ), ADJUST (កែតម្រូវ)",
      "• Source ៖ Service (សេវាជួសជុល), Purchase (ទិញចូល), ឬ Manual (កែដោយដៃ)",
      "• Qty ៖ ចំនួនគ្រាប់ដែលបានបូកបន្ថែម (+) ឬដកចេញ (- ឧ. -1)",
      "• Balance ៖ ចំនួនស្តុកចុងក្រោយបន្ទាប់ពីចលនាបានបញ្ចប់",
      "• Report No ៖ លេខកូដសំបុត្រដែលទាក់ទងនឹងការដកគ្រឿងបន្លាស់នេះ",
      "• Company ៖ ឈ្មោះក្រុមហ៊ុនម្ចាស់ម៉ាស៊ីន",
      "• Reason ៖ ការកត់ត្រាបន្ថែមលើមូលហេតុនៃការដក/ដាក់",
    ],
    columnsExplanationEn: [
      "• Date / Time: Real-time date and time of warehouse action",
      "• Spare Part: Stock part name",
      "• Serial Number: Stock SKU or serial number",
      "• Type: Transaction category (IN, OUT, REVERSAL, ADJUSTMENT)",
      "• Source: Trigger origin (Service, Purchase, Manual)",
      "• Qty: Signed quantity delta (+ added, - subtracted)",
      "• Balance: Resulting physical shelf balance",
      "• Report No: Related repair ticket number",
      "• Company: Customer name associated with ticket",
      "• Reason: Contextual transaction remarks",
    ],
    exampleKm: "ថ្ងៃ 05/08 ម៉ោង 10:30 AM ➔ ជាង សុខ ដក Mainboard 1 គ្រាប់ (OUT -1) ➔ ស្តុកដើម 10 ធ្លាក់មកសល់ 9 កត់ត្រាចូល Ledger ភ្លាមដោយស្វ័យប្រវត្តិ។",
    exampleEn: "On 05/08 at 10:30 AM: Tech Sok issues 1 Mainboard (OUT -1), shelf balance drops from 10 to 9, logged to immutable ledger.",
    href: "/stock-transactions",
    columns: [],
  },
  {
    id: "stock-movement-report",
    name: "Stock Movement & Velocity",
    nameKm: "Stock Movement & Velocity",
    category: "stock",
    categoryName: "Spare Parts & Stock",
    categoryNameKm: "គ្រឿងបន្លាស់ & ស្តុក",
    type: "excel",
    description: "Opening, In, Out, and Closing stock balances with fast-moving inventory analytics.",
    descriptionKm: "វិភាគល្បឿននៃការចរាចរស្តុក (Inventory Turnover Velocity) ដើម្បីដឹងថាគ្រឿងបន្លាស់ណាជាទំនិញលក់ដាច់/ប្រើច្រើន (Fast-Moving)។",
    databaseSource: "Endpoint /spareparts/movement-summary: Opening Balance, Total In, Total Out, Closing Balance",
    databaseSourceKm: "ទិន្នន័យពី /spareparts/movement-summary៖ ចំនួនស្តុកដើមគ្រា (Opening), នាំចូល (Total In), ចេញ (Total Out), ចុងគ្រា (Closing)",
    businessPurpose: "Identifies fast-moving vs slow-moving parts to streamline reorder points and warehouse storage.",
    businessPurposeKm: "វិភាគល្បឿនចរាចរស្តុក ដើម្បីដឹងថា «គ្រឿងបន្លាស់ណាជាទំនិញប្រើច្រើន (Fast-Moving)» ដើម្បីត្រៀមទិញស្តុកទុកជាប្រចាំ។",
    columnsExplanationKm: [
      "• Spare Part ៖ ឈ្មោះគ្រឿងបន្លាស់",
      "• Serial Number ៖ លេខកូដសម្គាល់គ្រឿងបន្លាស់",
      "• Opening ៖ ចំនួនស្តុកដែលមាននៅដើមខែ/ដើមគ្រា",
      "• Stock In ៖ ចំនួនគ្រាប់ដែលបានទិញចូល ឬផ្ទេរចូលក្នុងគ្រានោះ (+In)",
      "• Stock Out ៖ ចំនួនគ្រាប់ដែលបានដកយកទៅជួសជុល ឬលក់ចេញ (-Out)",
      "• Net ៖ ផលសងសុទ្ធ (In ដក Out) បង្ហាញថាស្តុកកើន (+) ឬថយ (- ឧ. +195)",
      "• Closing ៖ ចំនួនស្តុកជាក់ស្តែងដែលនៅសល់នៅចុងគ្រា (Opening + In - Out)",
      "• Current Stock ៖ ចំនួនស្តុកផ្ទាល់នៅលើប្រព័ន្ធ Live DB",
      "• Movements ៖ ចំនួនដងសរុបដែលមានការដក/ដាក់ ដើម្បីវាស់ល្បឿន Fast-Moving Inventory",
    ],
    columnsExplanationEn: [
      "• Spare Part: Part item name",
      "• Serial Number: Stock part identifier",
      "• Opening: Inventory count at the beginning of the period",
      "• Stock In: Cumulative stock purchases and returns (+In)",
      "• Stock Out: Cumulative stock issued to repair jobs (-Out)",
      "• Net: Net inventory change (In minus Out)",
      "• Closing: Ending inventory count (Opening + In - Out)",
      "• Current Stock: Real-time active database stock balance",
      "• Movements: Number of stock events measuring velocity (Fast vs Slow Moving)",
    ],
    exampleKm: "Fuser Film Sleeve ដើមគ្រា 38, នាំចូល +226, ដកចេញ -31 ➔ ចុងគ្រាសល់ 233 (មានចលនា 34 ដង = Fast-Moving ត្រូវស្តុកទុកជាប្រចាំ)។",
    exampleEn: "Fuser Film Sleeve: Opening 38 + In 226 - Out 31 = Net +195 -> Closing 233 (34 movements = Fast-Moving SKU).",
    href: "/stock-movement",
    columns: [],
  },
  {
    id: "stock-adjustments-report",
    name: "Stock Adjustments & Variance Audit",
    nameKm: "Stock Adjustments & Variance Audit",
    category: "stock",
    categoryName: "Spare Parts & Stock",
    categoryNameKm: "គ្រឿងបន្លាស់ & ស្តុក",
    type: "excel",
    description: "Manual stock count adjustment records with variance reasons and supervisor sign-offs.",
    descriptionKm: "ធ្វើសវនកម្មលើការកែប្រែស្តុកដោយដៃ ដើម្បីទប់ស្កាត់ការបាត់បង់ ឬភាពមិនប្រក្រតីក្នុងឃ្លាំង។",
    databaseSource: "Manual adjustments log: Part ID, +/- Variance, Reason Description, Authorizer",
    databaseSourceKm: "កំណត់ត្រានៃការកែប្រែចំនួនស្តុកដោយដៃ, ចំនួនខុសគ្នា (+/- Variance), មូលហេតុ និងអ្នកអនុញ្ញាត",
    businessPurpose: "Audits manual stock quantity adjustments to detect theft, breakage, or counting mistakes.",
    businessPurposeKm: "ធ្វើសវនកម្មលើ «ការកែប្រែចំនួនស្តុកដោយដៃ» ការពារការលួច ឬបាត់បង់ក្នុងឃ្លាំង។",
    columnsExplanationKm: [
      "• Date / Time ៖ ថ្ងៃខែឆ្នាំ និងម៉ោងនៃការកែតម្រូវស្តុក",
      "• Spare Part ៖ ឈ្មោះគ្រឿងបន្លាស់",
      "• Serial Number ៖ លេខកូដគ្រឿងបន្លាស់",
      "• Type ៖ កើនឡើង (Increase) ឬថយចុះ (Decrease)",
      "• Qty ៖ ចំនួនគ្រាប់ដែលបានកែតម្រូវ (ឧ. +5 ឬ -2)",
      "• Before ៖ ចំនួនស្តុកមុនពេលកែសម្រួល",
      "• After ៖ ចំនួនស្តុកក្រោយពេលកែសម្រួលរួច",
      "• Reason ៖ មូលហេតុនៃការកែសម្រួល (ឧ. បែកបាក់ពេលដឹកជញ្ជូន, រាប់ខុសពីមុន)",
    ],
    columnsExplanationEn: [
      "• Date / Time: Adjustment execution timestamp",
      "• Spare Part: Part item name",
      "• Serial Number: Stock SKU / serial code",
      "• Type: Adjustment direction (Increase / Decrease)",
      "• Qty: Adjusted quantity change (e.g. +5 or -2)",
      "• Before: Shelf quantity prior to adjustment",
      "• After: Shelf quantity after adjustment applied",
      "• Reason: Documented justification (transit breakage, cycle count correction)",
    ],
    exampleKm: "រាប់ស្តុកផ្ទាល់ឃើញ Drum សល់ 8 គ្រាប់ តែក្នុងប្រព័ន្ធបង្ហាញ 10 ➔ ប្រធានឃ្លាំងកែសម្រួល (-2) ដោយកត់ត្រាមូលហេតុ 'បែកបាក់ពេលដឹកជញ្ជូន' អនុម័តដោយ Manager។",
    exampleEn: "Physical count found 8 drums vs system record 10 (-2 delta) -> Supervisor applied adjustment (-2) citing 'Transit breakage' with manager sign-off.",
    href: "/stock-adjustments",
    columns: [],
  },
  {
    id: "stock-reconciliation-report",
    name: "Stock Reconciliation Matrix",
    nameKm: "Stock Reconciliation Matrix",
    category: "stock",
    categoryName: "Spare Parts & Stock",
    categoryNameKm: "គ្រឿងបន្លាស់ & ស្តុក",
    type: "excel",
    description: "Cross-checks notification alerts against ledger transactions and physical shelf balances.",
    descriptionKm: "ស្វែងរក និងដោះស្រាយភាពមិនស៊ីគ្នារវាងចំនួនដែលបានដក និងចំនួនដែលបានបង្វិលត្រឡប់ចូលស្តុកវិញ (Reversed Pairs)។",
    databaseSource: "Endpoint /spareparts/reconciliation: Notifications, Ledger Transactions, Actual Usage, Reversals",
    databaseSourceKm: "ទិន្នន័យពី /spareparts/reconciliation៖ ផ្ទៀងផ្ទាត់រវាងការជូនដំណឹង, ចំនួនដកចេញក្នុង Ledger, និងការប្រើប្រាស់ពិតប្រាកដ",
    businessPurpose: "Reconciles discrepancies between requested allocations and actual issued inventory.",
    businessPurposeKm: "ផ្ទៀងផ្ទាត់ «ការបង្វិលគ្រឿងបន្លាស់ចូលឃ្លាំងវិញ (Reversals)» កុំឱ្យបាត់បង់ ឬច្រឡំស្តុក។",
    columnsExplanationKm: [
      "• Spare Part ៖ ឈ្មោះគ្រឿងបន្លាស់",
      "• Serial Number ៖ លេខកូដគ្រឿងបន្លាស់",
      "• Qty ៖ ចំនួនគ្រាប់ដែលបានដកចេញពីឃ្លាំង",
      "• Went out ៖ កាលបរិច្ឆេទ និងម៉ោងដែលគ្រឿងបន្លាស់ត្រូវបានដកចេញ",
      "• Returned ៖ កាលបរិច្ឆេទ និងម៉ោងដែលបានយកមកប្រគល់ត្រឡប់ចូលឃ្លាំងវិញ (Reversal)",
      "• Out for ៖ រយៈពេលសរុបដែលគ្រឿងបន្លាស់នៅក្រៅឃ្លាំងមុនពេលបង្វិលចូល (ឧ. 45 min, 2 hours)",
      "• Why ៖ មូលហេតុដែលបង្វិលត្រឡប់ចូលវិញ (ឧ. គ្រឿងបន្លាស់ចាស់នៅល្អមិនបាច់ប្តូរ)",
      "• Report No ៖ លេខកូដសំបុត្រជួសជុលដែលពាក់ព័ន្ធ",
      "• In ledger? ៖ ស្ថានភាពបញ្ជាក់ថាតើចលនានេះត្រូវបានកត់ត្រាក្នុង Stock Ledger ត្រឹមត្រូវឬនៅ",
    ],
    columnsExplanationEn: [
      "• Spare Part: Stock part name",
      "• Serial Number: Stock SKU / Serial",
      "• Qty: Issued quantity",
      "• Went out: Timestamp when part left warehouse",
      "• Returned: Timestamp when part was returned (Reversal)",
      "• Out for: Duration elapsed outside before return (e.g. 45 min)",
      "• Why: Return explanation (e.g. Salvaged existing drum)",
      "• Report No: Related service ticket number",
      "• In ledger?: Verification flag confirming double-entry ledger match",
    ],
    exampleKm: "ជាងដក Drum ថ្មី ១ គ្រាប់ តែពេលជួសជុលឃើញថា Drum ចាស់គ្រាន់តែប្រឡាក់ ជូតស្អាតប្រើបានវិញ ➔ ជាងយក Drum ថ្មីមកបង្វិលចូលឃ្លាំងវិញ (Reversal) របាយការណ៍នេះធានាថាស្តុកត្រូវគ្នា ១០០%។",
    exampleEn: "Tech requisitioned 1 drum but salvaged existing drum -> Returned new drum to stock (Reversal) matching 100% with zero phantom shrinkage.",
    href: "/stock-reconciliation",
    columns: [],
  },
  {
    id: "stock-health",
    name: "Inventory Health & Data Integrity",
    nameKm: "Inventory Health & Data Integrity",
    category: "stock",
    categoryName: "Spare Parts & Stock",
    categoryNameKm: "គ្រឿងបន្លាស់ & ស្តុក",
    type: "excel",
    description: "Safety stock breach alerts, negative balance flags, and suggested purchase quantities.",
    descriptionKm: "ផ្តល់សញ្ញាអាសន្នជាបន្ទាន់ លើភាពមិនប្រក្រតីនៃទិន្នន័យស្តុក ដូចជាការជូនដំណឹងដែលគ្មានចលនាក្នុង Ledger, សមតុល្យអវិជ្ជមាន, ឬឈ្មោះគ្រឿងបន្លាស់ស្ទួន។",
    databaseSource: "Endpoint /spareparts/health: Items below SafetyStock threshold, Negative Balances, Duplicate SKUs",
    databaseSourceKm: "ទិន្នន័យពី /spareparts/health៖ គ្រឿងបន្លាស់ដែលធ្លាក់ចុះក្រោមចំនួនសុវត្ថិភាពអប្បបរមា, ស្តុកអវិជ្ជមាន, ទិន្នន័យស្ទួន",
    businessPurpose: "Issues automated procurement alerts and pinpoints data integrity anomalies across warehouse records.",
    businessPurposeKm: "ផ្តល់ «សញ្ញាអាសន្នលើភាពមិនប្រក្រតីនៃទិន្នន័យស្តុក (Data Conflicts)» ដូចជាមានសារ Telegram តែគ្មានប្រតិបត្តិក្នុង Ledger ឬសមតុល្យខុស។",
    columnsExplanationKm: [
      "• Severity ៖ កម្រិតអាសន្ន (ខ្ពស់ = ក្រហម, មធ្យម = លឿង, ទាប = ខៀវ)",
      "• Issue ៖ ប្រភេទបញ្ហាមិនប្រក្រតី (ឧ. មានសារ គ្មានប្រតិបត្តិ, សមតុល្យមិនត្រឹមត្រូវ, ឈ្មោះគ្រឿងបន្លាស់ស្ទួន)",
      "• Spare Part ៖ ឈ្មោះគ្រឿងបន្លាស់ដែលរងផលប៉ះពាល់",
      "• Serial / Entries ៖ លេខ Serial Number ឬបញ្ជី Entries ដែលស្ទួនគ្នា",
      "• Report No ៖ លេខកូដសំបុត្រជួសជុលដែលទាក់ទងនឹងបញ្ហានោះ (បើមាន)",
      "• When ៖ ថ្ងៃខែឆ្នាំ និងម៉ោងដែលបញ្ហានេះបានកើតឡើង",
      "• What is wrong ៖ ការពន្យល់បច្ចេកទេសលម្អិតពីមូលហេតុនៃបញ្ហា និងវិធីដោះស្រាយ",
    ],
    columnsExplanationEn: [
      "• Severity: Risk severity badge (High Red, Medium Yellow, Low Blue)",
      "• Issue: Anomaly category (Notification without ledger movement, negative balance, duplicate name)",
      "• Spare Part: Affected spare part item name",
      "• Serial / Entries: Serial number or duplicate SKU entry list",
      "• Report No: Associated repair ticket number (if applicable)",
      "• When: Timestamp when anomaly occurred",
      "• What is wrong: Detailed diagnosis explaining why the data conflict occurred",
    ],
    exampleKm: "Fuser Film Sleeve (កម្រិតខ្ពស់) ➔ បញ្ហា 'មានសារ គ្មានប្រតិបត្តិ' ៖ មានការផ្ញើសារ Telegram ថាទិញចូល (STOCK_IN +1) តែក្នុង Audit Ledger គ្មានប្រតិបត្តិនោះទេ (ត្រូវឱ្យប្រធានឃ្លាំងពិនិត្យមើលជាបន្ទាន់)។",
    exampleEn: "Fuser Film Sleeve (High Severity) -> Telegram notification sent (STOCK_IN +1) but audit ledger has no matching movement record.",
    href: "/stock-health",
    columns: [],
  },
  {
    id: "stock-dead",
    name: "Dead Stock & Obsolete Inventory",
    nameKm: "Dead Stock & Obsolete Inventory",
    category: "stock",
    categoryName: "Spare Parts & Stock",
    categoryNameKm: "គ្រឿងបន្លាស់ & ស្តុក",
    type: "excel",
    description: "Parts with zero movement for 90+ or 180+ days tying up working capital.",
    descriptionKm: "ជួយក្រុមហ៊ុនគ្រប់គ្រងដើមទុនបង្វិល (Working Capital) ដោយកំណត់អត្តសញ្ញាណគ្រឿងបន្លាស់ដែលលែងប្រើ ដើម្បីរៀបចំផែនការលក់បញ្ចុះតម្លៃ ឬទូទាត់ចោល។",
    databaseSource: "Endpoint /spareparts/dead-stock: Items with no In/Out transactions for >90 or >180 days + Tied Capital",
    databaseSourceKm: "ទិន្នន័យពី /spareparts/dead-stock៖ គ្រឿងបន្លាស់ដែលគ្មានចលនាក្នុងរយៈពេលលើសពី ៩០ ឬ ១៨០ ថ្ងៃឡើងទៅ",
    businessPurpose: "Frees trapped working capital by identifying obsolete inventory for discount sales or write-offs.",
    businessPurposeKm: "រកមើល «គ្រឿងបន្លាស់ដែលដេកស្តុកយូរខែគ្មានចលនាដកប្រើ (>90 ឬ >180 ថ្ងៃ)» ដើម្បីរំដោះដើមទុនបង្វិល។",
    columnsExplanationKm: [
      "• Spare Part ៖ ឈ្មោះគ្រឿងបន្លាស់",
      "• Serial Number ៖ លេខកូដគ្រឿងបន្លាស់",
      "• Stock Qty ៖ ចំនួនស្តុកសរុបក្នុងឃ្លាំង",
      "• On Hold ៖ ចំនួនដែលកំពុងកក់ទុក",
      "• Available ៖ ចំនួនស្តុកទំនេរពិតប្រាកដ (Stock Qty ដក On Hold)",
      "• Last Movement ៖ ថ្ងៃខែឆ្នាំចុងក្រោយបំផុតដែលមានការដក/ដាក់គ្រឿងបន្លាស់នេះ",
      "• Days Idle ៖ ចំនួនថ្ងៃដែលដេកស្តុកគ្មានចលនា (>90 ឬ >180 ថ្ងៃ)",
    ],
    columnsExplanationEn: [
      "• Spare Part: Part item name",
      "• Serial Number: Stock part identifier",
      "• Stock Qty: Total quantity sitting in warehouse",
      "• On Hold: Quantity currently locked for repair jobs",
      "• Available: Free uncommitted quantity (Stock Qty minus On Hold)",
      "• Last Movement: Timestamp of last recorded stock-in or stock-out",
      "• Days Idle: Consecutive days with zero movement (>90 or >180 days)",
    ],
    exampleKm: "Laser Scanner Unit 2012 សល់ ៨ គ្រាប់ ដេកស្តុកជាង ២០០ ថ្ងៃគ្មានអ្នកណាដកប្រើ ➔ ក្រុមហ៊ុនសម្រេចចិត្តលក់ឡៃឡុងបញ្ចុះតម្លៃ ៥០% ដើម្បីស្រង់ដើមទុនយកមកទិញគ្រឿងបន្លាស់ថ្មីៗវិញ។",
    exampleEn: "Laser Scanner Unit 2012 (8 units dormant for 200+ days) -> Company cleared inventory at 50% liquidation discount to recover working capital.",
    href: "/stock-dead",
    columns: [],
  },
];
