/**
 * @file components/docs/content/articlesInventory.ts
 * @description Chapter 3 - the spare-part catalogue and the stock ledger behind every repair.
 *
 * Split out of `docsData.ts` so no single file carries the whole catalogue
 * (§1: nothing over ~300 lines). `docsData.ts` assembles these back in
 * chapter order and is still the import path every consumer uses.
 */

import type { DocsSectionGroup } from "./articleTypes";

export const INVENTORY_SECTION: DocsSectionGroup = {
  id: "inventory-stock",
  titleKm: "ការគ្រប់គ្រងស្តុក & គ្រឿងបន្លាស់",
  titleEn: "Spare Parts & Stock Ledger",
  icon: "Package",
  badge: "Audited Ledger",
  articles: [
    {
      id: "spareparts-catalog",
      titleKm: "បញ្ជីគ្រឿងបន្លាស់មេ & ស្តុកបច្ចុប្បន្ន",
      titleEn: "Master Spare Parts Catalog & Live Stock",
      subtitleKm: "ការគ្រប់គ្រងកូដគ្រឿងបន្លាស់ (SKU), តម្លៃដើម, តម្លៃលក់, និងកម្រិតស្តុកសុវត្ថិភាពអប្បបរមា",
      subtitleEn: "SKU directory, pricing, stock levels, safety thresholds, and fast search",
      categoryKm: "ការគ្រប់គ្រងស្តុក & គ្រឿងបន្លាស់",
      categoryEn: "Spare Parts & Stock",
      icon: "Layers",
      route: "/spareparts",
      roles: ["Stock Keeper", "Technician", "Admin"],
      summaryKm: "ទំព័រ `/spareparts` ជាបញ្ជីមេនៃគ្រឿងបន្លាស់ទាំងអស់ក្នុងក្រុមហ៊ុន។ បង្ហាញចំនួនស្តុកជាក់ស្តែងនៅលើធ្នើរ (Current Stock), ចំនួនដែលកំពុងកក់ទុក (On Hold) និងចំនួនដែលអាចប្រើបាន (Available Stock)។",
      summaryEn: "Master catalog displaying physical on-shelf stock, reserved on-hold quantities, and real available units.",
      diagram: {
        titleKm: "លំហូរគ្រប់គ្រងបញ្ជីគ្រឿងបន្លាស់មេ (Master Parts Catalog Flow)",
        titleEn: "Master Spare Parts Catalog Pipeline",
        descriptionKm: "ការចុះឈ្មោះគ្រឿងបន្លាស់ កំណត់តម្លៃលក់ ស្តុកសុវត្ថិភាព និងការតាមដានលើធ្នើរជាក់ស្តែង",
        descriptionEn: "SKU registry workflow from creation to live shelf tracking.",
        nodes: [
          { id: "spc1", labelKm: "១. ចុះឈ្មោះកូដគ្រឿងបន្លាស់ (SKU)", labelEn: "1. Register SKU / Code", badgeKm: "Catalog", badgeEn: "Catalog", color: "violet", route: "/spareparts" },
          { id: "spc2", labelKm: "២. កំណត់តម្លៃដើម & តម្លៃលក់", labelEn: "2. Cost & Selling Price", badgeKm: "Pricing", badgeEn: "Pricing", color: "cyan" },
          { id: "spc3", labelKm: "៣. កំណត់កម្រិតសុវត្ថិភាព (Safety Stock)", labelEn: "3. Safety Threshold", badgeKm: "Threshold", badgeEn: "Threshold", color: "amber" },
          { id: "spc4", labelKm: "៤. បង្កើត Barcode សម្គាល់លើធ្នើរ", labelEn: "4. Barcode Generation", badgeKm: "Barcode", badgeEn: "Barcode", color: "indigo" },
          { id: "spc5", labelKm: "៥. តាមដានចំនួនស្តុកជាក់ស្តែង (Live Stock)", labelEn: "5. Real-Time Shelf Stock", badgeKm: "Active", badgeEn: "Active", color: "emerald", route: "/spareparts" },
        ],
      },
      steps: [
        {
          number: 1,
          titleKm: "ស្វែងរកគ្រឿងបន្លាស់តាមកូដ ឬឈ្មោះ",
          titleEn: "Search Spare Parts",
          descKm: "វាយកូដ Part Code, ឈ្មោះ ឬម៉ូដែលម៉ាស៊ីនក្នុងប្រអប់ Search ដើម្បីមើលចំនួនស្តុកភ្លាមៗ។",
          descEn: "Search by part code, description, or compatible model to inspect live inventory.",
        },
        {
          number: 2,
          titleKm: "បន្ថែម ឬកែប្រែព័ត៌មានគ្រឿងបន្លាស់",
          titleEn: "Add or Edit Parts",
          descKm: "ចុច 'Add Spare Part' ដើម្បីចុះឈ្មោះគ្រឿងបន្លាស់ថ្មី កំណត់តម្លៃលក់ និងចំនួនស្តុកសុវត្ថិភាព (Safety Stock)។",
          descEn: "Register new spare parts, configure standard selling prices, and set minimum safety thresholds.",
        },
      ],
    },
    {
      id: "sparepart-hold",
      titleKm: "គ្រឿងបន្លាស់ដែលកំពុងកក់ទុក (/sparepart-hold)",
      titleEn: "Spare Parts on Hold & Allocation Tracking",
      subtitleKm: "ការតាមដានគ្រឿងបន្លាស់ដែលត្រូវបានកក់ទុកសម្រាប់សំបុត្រជួសជុលសកម្ម ការពារការដកជាន់គ្នា",
      subtitleEn: "Tracking reserved parts allocated to open jobs to prevent double-issuance",
      categoryKm: "ការគ្រប់គ្រងស្តុក & គ្រឿងបន្លាស់",
      categoryEn: "Spare Parts & Stock",
      icon: "Lock",
      route: "/sparepart-hold",
      roles: ["Stock Keeper", "Technician", "Admin"],
      summaryKm: "ទំព័រ `/sparepart-hold` បង្ហាញគ្រឿងបន្លាស់ទាំងអស់ដែលកំពុងត្រូវបានកក់ទុក (Hold) សម្រាប់សំបុត្រដែលបានអនុម័តតម្លៃ ជួយឱ្យឃ្លាំងដឹងច្បាស់ថាគ្រឿងបន្លាស់ណាខ្លះមិនអាចយកទៅប្រើលើសំបុត្រផ្សេងទៀតបាន។",
      summaryEn: "Displays all reserved parts locked for confirmed repair jobs, safeguarding against accidental duplicate allocation.",
      diagram: {
        titleKm: "លំហូរការងារកក់ទុកគ្រឿងបន្លាស់ (Stock Hold Pipeline)",
        titleEn: "Stock Hold & Allocation Flow",
        descriptionKm: "ដំណើរការកក់ទុកគ្រឿងបន្លាស់ ការពារការដកជាន់គ្នា និងការដោះលែងមកវិញពេល Cancel",
        descriptionEn: "Reservation pipeline isolating allocated stock until physical issue or ticket cancellation.",
        nodes: [
          { id: "sph1", labelKm: "១. សំបុត្រទទួលបានការអនុម័តតម្លៃ", labelEn: "1. Quote Approved", badgeKm: "Sale Confirmed", badgeEn: "Sale Confirmed", color: "violet", route: "/confirmed-sale" },
          { id: "sph2", labelKm: "២. ប្រព័ន្ធកក់ចំនួនស្តុកស្វ័យប្រវត្តិ (Hold)", labelEn: "2. Auto-Reserve Stock", badgeKm: "Hold Qty", badgeEn: "Hold Qty", color: "amber", route: "/sparepart-hold" },
          { id: "sph3", labelKm: "៣. គណនា Available Stock = Total - Hold", labelEn: "3. Net Available Stock", badgeKm: "Real-time", badgeEn: "Real-time", color: "cyan" },
          { id: "sph4", labelKm: "៤. ដកចេញពិតប្រាកដ ឬ Release បង្វិលចូលវិញ", labelEn: "4. Physical Out or Release", badgeKm: "Audited", badgeEn: "Audited", color: "emerald", route: "/spare-request" },
        ],
      },
      steps: [
        {
          number: 1,
          titleKm: "ពិនិត្យគ្រឿងបន្លាស់ដែលកំពុងជាប់ Hold",
          titleEn: "Inspect Held Allocations",
          descKm: "ពិនិត្យមើលកូដគ្រឿងបន្លាស់ ចំនួនដែលកំពុងកក់ទុក និងលេខសំបុត្រដែលពាក់ព័ន្ធ។",
          descEn: "Review part SKU, reserved quantities, and linked service ticket numbers.",
        },
      ],
    },
    {
      id: "stock-transactions",
      titleKm: "សៀវភៅកត់ត្រាចលនាស្តុកទូទៅ (Stock Ledger)",
      titleEn: "Stock Transaction Audit Ledger",
      subtitleKm: "សៀវភៅកត់ត្រាចលនានាំចូល ដកចេញ និងកែតម្រូវគ្រប់គ្រាប់ ដោយគ្មានការលុបបំបាត់ដាន",
      subtitleEn: "Immutable audit log of all stock In, Out, and Adjustment movements",
      categoryKm: "ការគ្រប់គ្រងស្តុក & គ្រឿងបន្លាស់",
      categoryEn: "Spare Parts & Stock",
      icon: "FileSpreadsheet",
      route: "/stock-transactions",
      roles: ["Stock Keeper", "Auditor", "Admin"],
      summaryKm: "ទំព័រ `/stock-transactions` បង្ហាញរាល់ចលនាស្តុកទាំងអស់ក្នុងប្រព័ន្ធ។ រាល់ពេលមានការដក ឬបន្ថែម ប្រព័ន្ធកត់ត្រាចំនួនមុនផ្លាស់ប្តូរ (Balance Before), ចំនួនប្រែប្រួល (Qty Change), ចំនួនក្រោយផ្លាស់ប្តូរ (Balance After), និងឈ្មោះអ្នកអនុញ្ញាត។",
      summaryEn: "Full immutable movement ledger detailing exact timestamps, quantities, balance before/after, operator IDs, and linked ticket numbers.",
      diagram: {
        titleKm: "លំហូរសវនកម្មចលនាស្តុក (Double-Entry Stock Ledger Flow)",
        titleEn: "Double-Entry Stock Audit Ledger Workflow",
        descriptionKm: "ការកត់ត្រារាល់ចលនា In, Out, និង Reversal ដោយស្វ័យប្រវត្តិតាម ACID Database Transactions",
        descriptionEn: "Immutable transaction ledger flow guaranteeing 100% financial and physical stock integrity.",
        nodes: [
          { id: "st1", labelKm: "១. កើតមានចលនាស្តុក (In / Out / Adjust)", labelEn: "1. Stock Event Trigger", badgeKm: "Trigger", badgeEn: "Trigger", color: "violet" },
          { id: "st2", labelKm: "២. កត់ត្រាចំនួនស្តុកមុនប្រែប្រួល (Before)", labelEn: "2. Balance Before", badgeKm: "Pre-Count", badgeEn: "Pre-Count", color: "cyan" },
          { id: "st3", labelKm: "៣. អនុវត្តចំនួនប្រែប្រួល (Qty Delta +/-)", labelEn: "3. Apply Delta (+/-)", badgeKm: "Delta", badgeEn: "Delta", color: "amber" },
          { id: "st4", labelKm: "៤. គណនាចំនួនស្តុកចុងក្រោយ (After)", labelEn: "4. Balance After", badgeKm: "Post-Count", badgeEn: "Post-Count", color: "indigo" },
          { id: "st5", labelKm: "៥. រក្សាទុកក្នុង SparepartStockAuditLog", labelEn: "5. Save Immutable Ledger", badgeKm: "Audited", badgeEn: "Audited", color: "emerald", route: "/stock-transactions" },
        ],
      },
      steps: [
        {
          number: 1,
          titleKm: "ត្រងចលនាស្តុកតាមកាលបរិច្ឆេទ ឬទិសដៅ",
          titleEn: "Filter Ledger Transactions",
          descKm: "កំណត់ចន្លោះកាលបរិច្ឆេទ From/To និងជ្រើសរើសទិសដៅ 'In' ឬ 'Out' ដើម្បីមើលចលនាជាក់លាក់។",
          descEn: "Filter by date range, In/Out direction, or movement source (Service vs Manual).",
        },
      ],
    },
    {
      id: "stock-movement",
      titleKm: "វិភាគល្បឿនចរាចរស្តុក Fast/Slow-Moving (/stock-movement)",
      titleEn: "Stock Movement & Inventory Velocity Analytics",
      subtitleKm: "ការវិភាគចំនួនស្តុកដើមគ្រា (Opening), នាំចូល (In), ចេញ (Out), និងចុងគ្រា (Closing) រកទំនិញចរាចរលឿន",
      subtitleEn: "Opening, In, Out, and Closing stock velocity analysis to identify fast-moving components",
      categoryKm: "ការគ្រប់គ្រងស្តុក & គ្រឿងបន្លាស់",
      categoryEn: "Spare Parts & Stock",
      icon: "Activity",
      route: "/stock-movement",
      roles: ["Stock Keeper", "Purchasing", "Admin"],
      summaryKm: "ទំព័រ `/stock-movement` វិភាគល្បឿននៃការចរាចរគ្រឿងបន្លាស់ (Inventory Velocity) ជួយឱ្យដឹងថាគ្រឿងបន្លាស់ណាជាទំនិញលក់ដាច់/ប្រើច្រើន (Fast-Moving) ដើម្បីរៀបចំកន្លែងទុកដាក់ និងផែនការបញ្ជាទិញឱ្យមានប្រសិទ្ធភាព។",
      summaryEn: "Analyzes stock turnover velocity, computing opening balances, total ins, total outs, and closing positions.",
      diagram: {
        titleKm: "លំហូរវិភាគចរាចរស្តុក (Stock Velocity Analytics Flow)",
        titleEn: "Stock Movement & Velocity Pipeline",
        descriptionKm: "ការគណនាតុល្យភាពស្តុកដើមគ្រា នាំចូល ដកចេញ និងចុងគ្រា",
        descriptionEn: "Inventory turnover computation pipeline.",
        nodes: [
          { id: "sm1", labelKm: "១. ស្តុកដើមគ្រា (Opening Balance)", labelEn: "1. Opening Balance", badgeKm: "Period Start", badgeEn: "Period Start", color: "violet", route: "/stock-movement" },
          { id: "sm2", labelKm: "២. សរុបការនាំចូល (+ Total In)", labelEn: "2. Total Inflows (+)", badgeKm: "Purchases", badgeEn: "Purchases", color: "cyan" },
          { id: "sm3", labelKm: "៣. សរុបការដកចេញ (- Total Out)", labelEn: "3. Total Outflows (-)", badgeKm: "Usage", badgeEn: "Usage", color: "amber" },
          { id: "sm4", labelKm: "៤. ស្តុកចុងគ្រា (= Closing Balance)", labelEn: "4. Closing Position", badgeKm: "Period End", badgeEn: "Period End", color: "indigo" },
          { id: "sm5", labelKm: "៥. ចំណាត់ថ្នាក់ Fast-Moving vs Slow-Moving", labelEn: "5. Velocity Rating", badgeKm: "Analytics", badgeEn: "Analytics", color: "emerald" },
        ],
      },
      steps: [
        {
          number: 1,
          titleKm: "កំណត់ចន្លោះពេលវិភាគ",
          titleEn: "Select Reporting Period",
          descKm: "ជ្រើសរើសខែ ឬត្រីមាសដែលត្រូវវិភាគ ដើម្បីមើលតារាងចរាចរស្តុកសរុប។",
          descEn: "Select target monthly or quarterly period to aggregate movement velocity.",
        },
      ],
    },
    {
      id: "stock-adjustments",
      titleKm: "សវនកម្មការកែប្រែចំនួនស្តុកដោយដៃ (/stock-adjustments)",
      titleEn: "Stock Count Adjustments & Variance Audit",
      subtitleKm: "កំណត់ត្រានៃការកែប្រែចំនួនស្តុកដោយដៃ (+/- Variance) មូលហេតុ និងហត្ថលេខាអ្នកអនុញ្ញាត",
      subtitleEn: "Manual stock count adjustments log with variance justifications and manager sign-offs",
      categoryKm: "ការគ្រប់គ្រងស្តុក & គ្រឿងបន្លាស់",
      categoryEn: "Spare Parts & Stock",
      icon: "Sliders",
      route: "/stock-adjustments",
      roles: ["Stock Keeper", "Auditor", "Admin"],
      summaryKm: "ទំព័រ `/stock-adjustments` សម្រាប់ធ្វើសវនកម្មលើការកែតម្រូវចំនួនស្តុកលើធ្នើរដោយដៃ (Manual Adjustments) ដើម្បីទប់ស្កាត់ការបាត់បង់ ការខូចខាត ឬភាពមិនប្រក្រតីក្នុងឃ្លាំង។",
      summaryEn: "Forensic audit log of all manual stock adjustments, capturing +/- variances, operator justifications, and supervisor approvals.",
      diagram: {
        titleKm: "លំហូរសវនកម្មកែតម្រូវស្តុក (Stock Adjustment Audit Flow)",
        titleEn: "Stock Variance Audit Workflow",
        descriptionKm: "ដំណើរការរាប់ស្តុកជាក់ស្តែង ការកត់ត្រាចំនួនខុសគ្នា និងការអនុម័តដោយប្រធានឃ្លាំង",
        descriptionEn: "Physical count reconciliation and supervisor variance approval pipeline.",
        nodes: [
          { id: "sa1", labelKm: "១. រាប់ស្តុកជាក់ស្តែងលើធ្នើរឃ្លាំង", labelEn: "1. Physical Shelf Count", badgeKm: "Physical Count", badgeEn: "Physical Count", color: "violet", route: "/stock-adjustments" },
          { id: "sa2", labelKm: "២. រកឃើញភាពខុសគ្នា (+/- Variance)", labelEn: "2. Detect Variance", badgeKm: "Discrepancy", badgeEn: "Discrepancy", color: "amber" },
          { id: "sa3", labelKm: "៣. បញ្ចូលមូលហេតុ (Broken/Loss/Correction)", labelEn: "3. Input Justification", badgeKm: "Reason", badgeEn: "Reason", color: "cyan" },
          { id: "sa4", labelKm: "៤. Supervisor អនុម័ត និងចុះហត្ថលេខា", labelEn: "4. Supervisor Sign-Off", badgeKm: "Authorized", badgeEn: "Authorized", color: "indigo" },
          { id: "sa5", labelKm: "៥. កត់ត្រាក្នុង Audit Ledger ដោយស្វ័យប្រវត្តិ", labelEn: "5. Immutable Log Entry", badgeKm: "Audited", badgeEn: "Audited", color: "emerald", route: "/stock-transactions" },
        ],
      },
      steps: [
        {
          number: 1,
          titleKm: "កត់ត្រាការកែប្រែចំនួនស្តុក",
          titleEn: "Log Variance Adjustment",
          descKm: "ជ្រើសរើសកូដគ្រឿងបន្លាស់ បញ្ចូលចំនួនខុសគ្នា (+ ឬ -) និងសរសេរមូលហេតុច្បាស់លាស់។",
          descEn: "Select SKU, enter delta (+/-), and provide detailed justification note.",
        },
      ],
    },
    {
      id: "stock-health",
      titleKm: "សុខភាពស្តុក & ជូនដំណឹងបញ្ជាទិញ (Stock Health)",
      titleEn: "Inventory Health & Reorder Alert",
      subtitleKm: "ប្រព័ន្ធតាមដាន និងផ្តល់សញ្ញាអាសន្នលើទំនិញជិតអស់ពីស្តុក និងទំនិញមានបញ្ហា",
      subtitleEn: "Automated alerts for safety stock deficits, duplicate entries, and restocking requirements",
      categoryKm: "ការគ្រប់គ្រងស្តុក & គ្រឿងបន្លាស់",
      categoryEn: "Spare Parts & Stock",
      icon: "AlertTriangle",
      route: "/stock-health",
      roles: ["Stock Keeper", "Purchasing", "Admin"],
      summaryKm: "ទំព័រ `/stock-health` ដំណើរការក្បួនវិភាគដើម្បីស្វែងរកគ្រឿងបន្លាស់ដែលធ្លាក់ចុះក្រោមចំនួនសុវត្ថិភាពអប្បបរមា (Low Stock Alert) ជួយឱ្យផ្នែកលទ្ធកម្មអាចបញ្ជាទិញទំនិញបន្ថែមទាន់ពេលវេលា។",
      summaryEn: "Proactively audits inventory for items below safety thresholds, negative balances, and data discrepancies.",
      diagram: {
        titleKm: "លំហូរវិភាគសុខភាពស្តុក & ជូនដំណឹងបញ្ជាទិញ (Stock Health Flow)",
        titleEn: "Inventory Health & Auto-Reorder Flowchart",
        descriptionKm: "ការស្កេនរកទំនិញជិតអស់ពីស្តុក និងការបង្កើតសំណើបញ្ជាទិញដោយស្វ័យប្រវត្តិ",
        descriptionEn: "Safety threshold auditing and automated procurement alert generation.",
        nodes: [
          { id: "sh1", labelKm: "១. ស្កេនទិន្នន័យស្តុកគ្រឿងបន្លាស់", labelEn: "1. Scan Stock Database", badgeKm: "Audit", badgeEn: "Audit", color: "violet", route: "/stock-health" },
          { id: "sh2", labelKm: "២. ផ្ទៀងផ្ទាត់ជាមួយ Safety Stock", labelEn: "2. Compare Safety Limit", badgeKm: "Threshold", badgeEn: "Threshold", color: "cyan" },
          { id: "sh3", labelKm: "៣. ជូនដំណឹងកម្រិតគ្រោះថ្នាក់ (Critical)", labelEn: "3. Flag Critical Alerts", badgeKm: "Alert", badgeEn: "Alert", color: "rose" },
          { id: "sh4", labelKm: "៤. បង្កើតបញ្ជីស្នើសុំទិញបន្ថែម (Reorder)", labelEn: "4. Generate Restock Plan", badgeKm: "Requisition", badgeEn: "Requisition", color: "amber" },
          { id: "sh5", labelKm: "៥. នាំចេញ Excel ជូនផ្នែកលទ្ធកម្ម", labelEn: "5. Export Excel to Purchase", badgeKm: "Export", badgeEn: "Export", color: "emerald" },
        ],
      },
      steps: [
        {
          number: 1,
          titleKm: "ពិនិត្យបញ្ជីជូនដំណឹងកម្រិតខ្ពស់ (High Severity Alerts)",
          titleEn: "Review Critical Stock Alerts",
          descKm: "ពិនិត្យមើលគ្រឿងបន្លាស់ដែលបង្ហាញស្លាកក្រហម (Critical) ដែលមានចំនួនស្តុកសូន្យ ឬជិតអស់។",
          descEn: "Inspect items flagged as critical needing immediate purchase requisitions.",
        },
      ],
    },
    {
      id: "stock-dead",
      titleKm: "វិភាគទំនិញនៅទ្រឹងលើសពី ៩០/១៨០ ថ្ងៃ (/stock-dead)",
      titleEn: "Dead Stock & Obsolete Inventory Recovery",
      subtitleKm: "កំណត់អត្តសញ្ញាណគ្រឿងបន្លាស់ដែលគ្មានចលនាយូរខែ ដើម្បីរំដោះដើមទុនបង្វិលដែលកកស្ទះ",
      subtitleEn: "Identifying zero-movement inventory for 90+ and 180+ days to free trapped working capital",
      categoryKm: "ការគ្រប់គ្រងស្តុក & គ្រឿងបន្លាស់",
      categoryEn: "Spare Parts & Stock",
      icon: "Archive",
      route: "/stock-dead",
      roles: ["Stock Keeper", "Management", "Admin"],
      summaryKm: "ទំព័រ `/stock-dead` ជួយក្រុមហ៊ុនគ្រប់គ្រងដើមទុនបង្វិល (Working Capital) ដោយកំណត់អត្តសញ្ញាណគ្រឿងបន្លាស់ដែលគ្មានចលនានាំចូល ឬដកចេញក្នុងរយៈពេលលើសពី ៩០ ឬ ១៨០ ថ្ងៃឡើងទៅ ដើម្បីរៀបចំផែនការលក់បញ្ចុះតម្លៃ ឬទូទាត់ចោល។",
      summaryEn: "Identifies dead stock tying up operating capital, enabling strategic liquidations or inventory write-offs.",
      diagram: {
        titleKm: "លំហូរគ្រប់គ្រង & រំដោះដើមទុន Dead Stock (Dead Stock Recovery Flow)",
        titleEn: "Dead Stock Recovery Pipeline",
        descriptionKm: "ការស្វែងរកគ្រឿងបន្លាស់គ្មានចលនាយូរថ្ងៃ និងការរៀបចំយុទ្ធសាស្ត្ររំដោះដើមទុន",
        descriptionEn: "Inactive stock detection and capital recovery workflow.",
        nodes: [
          { id: "sd1", labelKm: "១. ស្កេនគ្រឿងបន្លាស់គ្មានចលនា >90/180 ថ្ងៃ", labelEn: "1. Scan Inactive SKU (>90d)", badgeKm: "Audit", badgeEn: "Audit", color: "violet", route: "/stock-dead" },
          { id: "sd2", labelKm: "២. គណនាទំហំទឹកប្រាក់កកស្ទះ ($ Capital Tied)", labelEn: "2. Compute Trapped Value", badgeKm: "Capital", badgeEn: "Capital", color: "rose" },
          { id: "sd3", labelKm: "៣. ពិគ្រោះយោបល់ជាមួយថ្នាក់ដឹកនាំ", labelEn: "3. Management Review", badgeKm: "Strategy", badgeEn: "Strategy", color: "amber" },
          { id: "sd4", labelKm: "៤. រៀបចំផែនការលក់បញ្ចុះតម្លៃ ឬ Write-off", labelEn: "4. Discount / Liquidation", badgeKm: "Recovery", badgeEn: "Recovery", color: "emerald" },
        ],
      },
      steps: [
        {
          number: 1,
          titleKm: "ពិនិត្យទំហំទឹកប្រាក់កកស្ទះ",
          titleEn: "Inspect Trapped Capital",
          descKm: "មើលបញ្ជីគ្រឿងបន្លាស់ដែលគ្មានចលនា និងចំនួនទឹកប្រាក់សរុបដែលបានកកស្ទះ។",
          descEn: "Review idle part SKUs and aggregate dollar valuation tied in dead stock.",
        },
      ],
    },
  ],
};
