/**
 * @file components/docs/content/articlesReports.ts
 * @description Chapter 4 - the 29-report suite: what each family answers and who reads it.
 *
 * Split out of `docsData.ts` so no single file carries the whole catalogue
 * (§1: nothing over ~300 lines). `docsData.ts` assembles these back in
 * chapter order and is still the import path every consumer uses.
 */

import type { DocsSectionGroup } from "./articleTypes";

export const REPORTS_SECTION: DocsSectionGroup = {
  id: "reports-hub",
  titleKm: "មជ្ឈមណ្ឌលរបាយការណ៍ទាំង ២៩",
  titleEn: "29 Enterprise Reports Hub",
  icon: "FileSpreadsheet",
  badge: "29 Reports",
  articles: [
    {
      id: "reports-overview",
      titleKm: "ទិដ្ឋភាពទូទៅនៃប្រព័ន្ធរបាយការណ៍សហគ្រាសទាំង ២៩",
      titleEn: "29 Enterprise Reports Master Overview",
      subtitleKm: "ប្រព័ន្ធរបាយការណ៍ជំនាញកម្រិតសហគ្រាស បែងចែកជា ៥ ក្រុមធំៗ គាំទ្រការនាំចេញ Excel និង A4 Print",
      subtitleEn: "Comprehensive analytics suite categorized into 5 business groups with Excel & A4 exports",
      categoryKm: "មជ្ឈមណ្ឌលរបាយការណ៍ទាំង ២៩",
      categoryEn: "Enterprise Reports",
      icon: "PieChart",
      route: "/templates-settings",
      roles: ["Manager", "Supervisor", "Sales", "Admin"],
      summaryKm: "ប្រព័ន្ធមានរបាយការណ៍ស្តង់ដារចំនួន ២៩ ដែលត្រូវបានរចនាឡើងយ៉ាងផ្ចិតផ្ចង់ ដើម្បីឆ្លើយតបរាល់សំណួរអាជីវកម្ម ចាប់ពីល្បឿនជួសជុលរបស់ជាង បន្ទុកការងាររោងជាង ការចរាចរស្តុក រហូតដល់បំពង់លក់ (Sales Pipeline) របស់ផ្នែកលក់។",
      summaryEn: "A complete suite of 29 operational and executive reports categorized into Repair Operations, Quality & Diagnostics, Technician KPIs, Sales & CRM, and Spare Parts & Stock.",
      reportTableCategory: "all",
      diagram: {
        titleKm: "រចនាសម្ព័ន្ធមែកធាងរបាយការណ៍ទាំង ២៩ (29 Reports Mindmap)",
        titleEn: "29 Enterprise Reports Mindmap Architecture",
        descriptionKm: "ការបែងចែករបាយការណ៍ទាំង ២៩ ជា ៥ សសរស្តម្ភធំៗនៃអាជីវកម្ម",
        descriptionEn: "Categorization of all 29 reports across 5 core business pillars.",
        nodes: [
          { id: "ro1", labelKm: "១. Repair Operations (១០ របាយការណ៍)", labelEn: "1. Operations (10 Reports)", badgeKm: "10 Reports", badgeEn: "10 Reports", color: "violet", route: "/daily-report" },
          { id: "ro2", labelKm: "២. Quality & Diagnostics (២ របាយការណ៍)", labelEn: "2. Diagnostics (2 Reports)", badgeKm: "2 Reports", badgeEn: "2 Reports", color: "cyan", route: "/faults-report" },
          { id: "ro3", labelKm: "៣. Technician KPIs (២ របាយការណ៍)", labelEn: "3. Tech KPIs (2 Reports)", badgeKm: "2 Reports", badgeEn: "2 Reports", color: "indigo", route: "/engineer-kpi-report" },
          { id: "ro4", labelKm: "៤. Sales & CRM (៧ របាយការណ៍)", labelEn: "4. Sales CRM (7 Reports)", badgeKm: "7 Reports", badgeEn: "7 Reports", color: "amber", route: "/customer-report" },
          { id: "ro5", labelKm: "៥. Spare Parts & Stock (៨ របាយការណ៍)", labelEn: "5. Spare Stock (8 Reports)", badgeKm: "8 Reports", badgeEn: "8 Reports", color: "emerald", route: "/sparepart-usage" },
        ],
      },
      steps: [
        {
          number: 1,
          titleKm: "ជ្រើសរើសរបាយការណ៍ពីបញ្ជី ឬរបារចំហៀង",
          titleEn: "Select Desired Report",
          descKm: "ចូលទៅកាន់ផ្នែក 'Reports' នៅលើរបារចំហៀង ឬបើកទំព័រ `/templates-settings` ដើម្បីរុករករបាយការណ៍តាមប្រភេទ។",
          descEn: "Browse reports via the sidebar menu or use the Templates Settings catalog.",
        },
        {
          number: 2,
          titleKm: "កំណត់កាលបរិច្ឆេទ និងតម្រង (Filter Bar)",
          titleEn: "Set Date Range & Filters",
          descKm: "ជ្រើសរើសចន្លោះកាលបរិច្ឆេទ From/To ឬចុច 'This month'/'Last month' រួចជ្រើសរើសតម្រងស្ថានភាព ឬប្រភេទសេវា។",
          descEn: "Select period presets (This Month / Last Month) and refine by status, service type, or location.",
        },
        {
          number: 3,
          titleKm: "អានលើអេក្រង់ ឬនាំចេញជា Excel / បោះពុម្ព A4",
          titleEn: "Read Online, Export Excel or Print A4",
          descKm: "តារាងបង្ហាញទិន្នន័យលើអេក្រង់ និងអនុញ្ញាតឱ្យចុច 'Export Excel' ដើម្បីទាញយកឯកសារដែលមានទម្រង់ស្អាតដូចគ្នា ១០០%។",
          descEn: "Review the dynamic table online and export formatted Excel workbooks with totals and formulas.",
        },
      ],
    },
    {
      id: "report-repair-operations",
      titleKm: "ក្រុមទី ១៖ របាយការណ៍ប្រតិបត្តិការជួសជុល (១០ របាយការណ៍)",
      titleEn: "Category 1: Repair Operations (10 Reports)",
      subtitleKm: "តាមដានប្រតិបត្តិការរោងជាងប្រចាំថ្ងៃ ប្រចាំខែ តារាងម៉ាទ្រីស ១២ ខែ និងសវនកម្មល្បឿនជួសជុល",
      subtitleEn: "Daily tickets, monthly aggregations, 12-month technical matrix, and turnaround audits",
      categoryKm: "មជ្ឈមណ្ឌលរបាយការណ៍ទាំង ២៩",
      categoryEn: "Enterprise Reports",
      icon: "Wrench",
      route: "/daily-report",
      reportTableCategory: "operations",
      summaryKm: "ក្រុមរបាយការណ៍ប្រតិបត្តិការជួយឱ្យអ្នកគ្រប់គ្រង និងប្រធានរោងជាងដឹងច្បាស់អំពីចំនួនការងារដែលបានទទួល កំពុងធ្វើ និងបានប្រគល់ជូន រួមទាំងរយៈពេលមធ្យមនៃការជួសជុល (Turnaround Time)។",
      summaryEn: "Operational intelligence covering daily throughput, monthly performance, annual technical trends, and turnaround time audits.",
      diagram: {
        titleKm: "លំហូរតាមដានប្រតិបត្តិការជួសជុល (Repair Operations Analytics Flow)",
        titleEn: "Repair Operations Analytics Pipeline",
        descriptionKm: "ការប្រមូលទិន្នន័យពីគ្រប់សំបុត្រជួសជុល បង្កើតជារបាយការណ៍ប្រចាំថ្ងៃ ប្រចាំខែ និងម៉ាទ្រីស ១២ ខែ",
        descriptionEn: "Data aggregation pipeline from live ticket states to annual executive matrices.",
        nodes: [
          { id: "r_op1", labelKm: "១. សំបុត្រសកម្មក្នុង Services Table", labelEn: "1. Live Services Table", badgeKm: "DB Source", badgeEn: "DB Source", color: "violet" },
          { id: "r_op2", labelKm: "២. ប្រតិបត្តិការប្រចាំថ្ងៃ (/daily-report)", labelEn: "2. Daily Operations", badgeKm: "Daily Log", badgeEn: "Daily Log", color: "cyan", route: "/daily-report" },
          { id: "r_op3", labelKm: "៣. លទ្ធផលសរុបប្រចាំខែ (/monthly-report)", labelEn: "3. Monthly Performance", badgeKm: "Monthly Agg", badgeEn: "Monthly Agg", color: "indigo", route: "/monthly-report" },
          { id: "r_op4", labelKm: "៤. តារាងម៉ាទ្រីស ១២ ខែ (/monthly-technical-matrix)", labelEn: "4. 12-Month Matrix", badgeKm: "Annual Matrix", badgeEn: "Annual Matrix", color: "amber", route: "/monthly-technical-matrix" },
          { id: "r_op5", labelKm: "៥. សវនកម្មល្បឿនជួសជុល (/repair-report)", labelEn: "5. Turnaround Audit", badgeKm: "SLA Audit", badgeEn: "SLA Audit", color: "emerald", route: "/repair-report" },
        ],
      },
      steps: [
        {
          number: 1,
          titleKm: "ឧទាហរណ៍សាមញ្ញ៖ តាមដានល្បឿនជួសជុល (Repair Performance / Turnaround Time)",
          titleEn: "Simple Example: Turnaround Speed Tracking",
          descKm: "• **សំណួរដែលចង់ដឹង៖** *«តើរោងជាងយើងជួសជុលម៉ាស៊ីនមួយគ្រឿង ចំណាយពេលមធ្យមប៉ុន្មានថ្ងៃ?»*\n• **តួលេខជាក់ស្តែងក្នុង `/repair-report`៖**\n  - សំបុត្រ #SR-001 (ធនាគារ ABA)៖ ទទួលថ្ងៃ 01/08 ➔ ចេញថ្ងៃ 03/08 ➔ ចំណាយពេល **២ ថ្ងៃ** (លឿនជាងស្តង់ដារ ៣ ថ្ងៃ) ➔ ✅ Pass SLA\n  - សំបុត្រ #SR-002 (ក្រុមហ៊ុន Chip Mong)៖ ទទួលថ្ងៃ 02/08 ➔ ចេញថ្ងៃ 09/08 ➔ ចំណាយពេល **៧ ថ្ងៃ** (យឺតដោយសាររង់ចាំគ្រឿងបន្លាស់ពីស្តុក ៥ ថ្ងៃ) ➔ ⚠️ ជួយឱ្យប្រធានរោងជាងដឹងថាកកស្ទះនៅផ្នែកស្តុក!",
          descEn: "Shows turnaround days per ticket and pinpoints bottlenecks (e.g. 5 days waiting on parts vs actual repair work).",
        },
        {
          number: 2,
          titleKm: "ឧទាហរណ៍សាមញ្ញ៖ តាមដានការងារប្រចាំថ្ងៃ និងប្រចាំខែ (Daily & Monthly Throughput)",
          titleEn: "Simple Example: Daily & Monthly Throughput",
          descKm: "• ក្នុង `/daily-report`៖ មើលឃើញភ្លាមៗថា ថ្ងៃនេះទទួលម៉ាស៊ីនបាន ៨ គ្រឿង, ជាងកំពុងជួសជុល ៥ គ្រឿង, និង QA អនុម័តចេញបាន ៦ គ្រឿង។\n• ក្នុង `/monthly-report`៖ មើលឃើញផលបូកសរុបប្រចាំខែ បែងចែកតាមក្រុមហ៊ុនអតិថិជន (ឧ. ក្រុមហ៊ុន ABA ជួសជុល ២០ គ្រឿង សរុបទឹកប្រាក់ $1,200)។",
          descEn: "Provides daily snapshot of active WIP and monthly total volume broken down by corporate client.",
        },
      ],
      callouts: [
        {
          type: "tip",
          titleKm: "គន្លឹះយល់ដឹង៖ ស្វែងរកចំណុចកកស្ទះ (Bottleneck) & តាមដាន Process Date តាមដំណាក់កាល",
          titleEn: "Bottleneck Detection & Historical Process Date Filtering",
          contentKm: "របាយការណ៍ `Stage Report (/stage-report)` ជួយឱ្យដឹងថាសំបុត្រកំពុងកកស្ទះនៅកន្លែងណា។ ពិសេសជាងនេះទៅទៀត Report នេះដំណើរការផ្អែកលើ «ចន្លោះកាលបរិច្ឆេទ ជាមួយនិង Status ដំណាក់កាល» — ដោយមិនខ្វល់ថាសំបុត្រនោះបច្ចុប្បន្នស្ថិតនៅដល់ណា ឬជួសជុលរួចរាល់ (Finished) ហើយនោះឡើយ (ឧ. ម៉ាស៊ីនចូលថ្ងៃទី ០១ ទោះឥឡូវនេះជួសជុលហើយក៏ដោយ នៅពេល Filter រកម៉ាស៊ីនចូល ឬត្រួតពិនិត្យថ្ងៃទី ០១ វានឹងទាញមកបង្ហាញទាំងអស់)។",
          contentEn: "Stage Breakdown (/stage-report) isolates operational bottlenecks. It filters tickets by historical milestone dates (Process Date) matching the selected Stage — regardless of whether the ticket is currently in-progress or already fully completed.",
        },
      ],
    },
    {
      id: "report-quality-diagnostics",
      titleKm: "ក្រុមទី ២៖ របាយការណ៍គុណភាព & វិភាគបញ្ហា (២ របាយការណ៍)",
      titleEn: "Category 2: Quality & Diagnostics (2 Reports)",
      subtitleKm: "ការវិភាគគំរូបញ្ហា Error Codes ដែលកើតឡើងដដែលៗ និងកំណត់ត្រាម៉ាស៊ីនដែលបដិសេធមិនជួសជុល",
      subtitleEn: "Recurring fault patterns, diagnostic knowledge base, and rejection reason tracking",
      categoryKm: "មជ្ឈមណ្ឌលរបាយការណ៍ទាំង ២៩",
      categoryEn: "Enterprise Reports",
      icon: "AlertCircle",
      route: "/faults-report",
      reportTableCategory: "diagnostics",
      summaryKm: "របាយការណ៍វិភាគបញ្ហាដើរតួជាបណ្ណាល័យចំណេះដឹង (Knowledge Base) សម្រាប់ជាងមើលជាគំរូដំណោះស្រាយលើម៉ាស៊ីនដែលធ្លាប់ជួសជុលពីមុន។",
      summaryEn: "Aggregates technical symptoms, root causes, and solutions into an actionable reference library for technicians.",
      diagram: {
        titleKm: "លំហូរវិភាគគុណភាព & Knowledge Base (Quality & Diagnostics Flow)",
        titleEn: "Diagnostics & Knowledge Base Flow",
        descriptionKm: "ការប្រមូលផ្តុំរោគសញ្ញាខូច មូលហេតុពិត និងដំណោះស្រាយដើម្បីបង្កើតជា Knowledge Base",
        descriptionEn: "Knowledge base pipeline transforming diagnostic logs into rapid troubleshooting guides.",
        nodes: [
          { id: "r_qd1", labelKm: "១. ទិន្នន័យ Symptom & Inspection", labelEn: "1. Diagnostic Input", badgeKm: "Data", badgeEn: "Data", color: "violet" },
          { id: "r_qd2", labelKm: "២. វិភាគគំរូបញ្ហាដែលកើតដដែលៗ", labelEn: "2. Pattern Recognition", badgeKm: "Analytics", badgeEn: "Analytics", color: "cyan" },
          { id: "r_qd3", labelKm: "៣. Knowledge Base ជាង (/faults-report)", labelEn: "3. Common Faults Library", badgeKm: "Solutions", badgeEn: "Solutions", color: "emerald", route: "/faults-report" },
          { id: "r_qd4", labelKm: "៤. កត់ត្រាមូលហេតុបដិសេធ (/rejected-report)", labelEn: "4. Rejections Log", badgeKm: "Rejects", badgeEn: "Rejects", color: "rose", route: "/rejected-report" },
        ],
      },
      steps: [
        {
          number: 1,
          titleKm: "ឧទាហរណ៍សាមញ្ញ៖ បណ្ណាល័យដោះស្រាយបញ្ហា (Faults Knowledge Base)",
          titleEn: "Simple Example: Knowledge Base Reference",
          descKm: "• **សំណួរដែលចង់ដឹង៖** *«ជាងថ្មីទើបចូលធ្វើការ ជួបម៉ាស៊ីនព្រីនចេញមកឆ្នូតខ្មៅ មិនដឹងខូចត្រង់ណា?»*\n• **ដំណោះស្រាយក្នុង `/faults-report`៖**\n  - ជាងបើកមើលម៉ូដែល `Canon imageRUNNER 2520` ➔ ឃើញស្ថិតិបង្ហាញថា ៨៥% នៃករណី 'ឆ្នូតខ្មៅ' គឺបណ្តាលមកពី **'Fuser Film Sleeve រហែក'** ហើយដំណោះស្រាយដែលធ្លាប់អនុវត្តបានជោគជ័យគឺ **'ប្តូរ Fuser Film ថ្មី'**\n  - ជាងថ្មីអាចដឹងភ្លាម និងជួសជុលបានចំគោលដៅ មិនបាច់ចំណាយពេលរាវរកខុសផ្លូវឡើយ!",
          descEn: "Technicians reference historical defect patterns to immediately diagnose common root causes such as torn fuser films.",
        },
      ],
      callouts: [
        {
          type: "tip",
          titleKm: "វិភាគមូលហេតុអតិថិជនមិនព្រមជួសជុល (Rejected Audit)",
          titleEn: "Rejection Reason Analytics",
          contentKm: "ក្នុង `/rejected-report`៖ បង្ហាញថាក្នុងខែនេះមានម៉ាស៊ីនបដិសេធ ៥ គ្រឿង (៣ គ្រឿងដោយសារថ្លៃគ្រឿងបន្លាស់ខ្ពស់ពេក និង ២ គ្រឿងដោយសារម៉ាស៊ីនចាស់លែងមានគ្រឿងបន្លាស់) ជួយឱ្យក្រុមហ៊ុនដឹងពីបញ្ហាតម្លៃ និងតម្រូវការទីផ្សារ។",
          contentEn: "Analyzes why clients declined quotes (e.g. price sensitivity vs parts obsolescence) to adjust pricing policies.",
        },
      ],
    },
    {
      id: "report-technician-kpis",
      titleKm: "ក្រុមទី ៣៖ របាយការណ៍សូចនាករ KPI ជាង (២ របាយការណ៍)",
      titleEn: "Category 3: Technician KPIs (2 Reports)",
      subtitleKm: "ការវាយតម្លៃលទ្ធផលការងារជាងម្នាក់ៗ៖ ចំនួនការងារបញ្ចប់ រយៈពេលមធ្យម អត្រាជោគជ័យ និងនិទ្ទេស",
      subtitleEn: "Technician scorecards, turnaround speed, fix success rates, active WIP, and performance grades",
      categoryKm: "មជ្ឈមណ្ឌលរបាយការណ៍ទាំង ២៩",
      categoryEn: "Enterprise Reports",
      icon: "Award",
      route: "/engineer-kpi-report",
      reportTableCategory: "kpis",
      summaryKm: "របាយការណ៍ KPI ផ្តល់ចំណាត់ថ្នាក់និទ្ទេស (Grade A+, A, B, C) ដល់ជាងបច្ចេកទេសផ្អែកលើល្បឿន និងអត្រាជោគជ័យជាក់ស្តែង ដើម្បីជាមូលដ្ឋានក្នុងការផ្តល់ការលើកទឹកចិត្ត (Incentive Bonus)។",
      summaryEn: "Evaluates individual engineer efficiency with objective grading based on turnaround speed and completion rate.",
      diagram: {
        titleKm: "លំហូរវាយតម្លៃ KPI ជាង (Technician KPI & Grading Flow)",
        titleEn: "Technician Performance Scorecard Pipeline",
        descriptionKm: "ការគណនាសូចនាករការងារជាក់ស្តែង និងការកំណត់និទ្ទេស Grade A+/A/B/C",
        descriptionEn: "Scorecard algorithm calculating speed, success rate, and performance tier.",
        nodes: [
          { id: "r_kpi1", labelKm: "១. ទាញសំបុត្រដែលបានប្រគល់ (Assigned)", labelEn: "1. Assigned Tickets", badgeKm: "WIP", badgeEn: "WIP", color: "violet", route: "/engineer-report" },
          { id: "r_kpi2", labelKm: "២. គណនារយៈពេលមធ្យម (Avg Turnaround)", labelEn: "2. Turnaround Days", badgeKm: "Speed", badgeEn: "Speed", color: "cyan" },
          { id: "r_kpi3", labelKm: "៣. គណនាអត្រាជោគជ័យ (Success Rate %)", labelEn: "3. Success Rate %", badgeKm: "Quality", badgeEn: "Quality", color: "indigo" },
          { id: "r_kpi4", labelKm: "៤. កំណត់និទ្ទេស (Grade A+/A/B/C)", labelEn: "4. Performance Grade", badgeKm: "Grading", badgeEn: "Grading", color: "amber" },
          { id: "r_kpi5", labelKm: "៥. តារាងពិន្ទុរួម (/engineer-kpi-report)", labelEn: "5. Master KPI Matrix", badgeKm: "KPI Matrix", badgeEn: "KPI Matrix", color: "emerald", route: "/engineer-kpi-report" },
        ],
      },
      steps: [
        {
          number: 1,
          titleKm: "ឧទាហរណ៍សាមញ្ញ៖ ការវាយតម្លៃនិទ្ទេស និងប្រាក់រង្វាន់លើកទឹកចិត្ត (Engineer KPI Grading)",
          titleEn: "Simple Example: Performance Scorecard & Bonus Calculation",
          descKm: "• **សំណួរដែលចង់ដឹង៖** *«តើចុងខែនេះ ជាងណាខ្លះធ្វើការបានល្អជាងគេ ដើម្បីទទួលបានប្រាក់រង្វាន់ Incentive?»*\n• **តារាងពិន្ទុជាក់ស្តែងក្នុង `/engineer-kpi-report`៖**\n  - **ជាង សុខ (Sok)៖** ទទួល ៤៥ គ្រឿង ➔ ជួសជុលរួច ៤៤ គ្រឿង ➔ អត្រាជោគជ័យ **៩៨%** ➔ រយៈពេលមធ្យម **១.២ ថ្ងៃ** ➔ ទទួលបាន **🌟 Grade A+** (ទទួលបានប្រាក់រង្វាន់ពេញលេញ)\n  - **ជាង ដារ៉ា (Dara)៖** ទទួល ៣៥ គ្រឿង ➔ ជួសជុលរួច ៣២ គ្រឿង ➔ អត្រាជោគជ័យ **៩១%** ➔ រយៈពេលមធ្យម **២.៥ ថ្ងៃ** ➔ ទទួលបាន **Grade A**\n  - **ជាង ចាន់ (Chan)៖** ទទួល ២៥ គ្រឿង ➔ ជួសជុលរួច ២០ គ្រឿង ➔ អត្រាជោគជ័យ **៨០%** ➔ រយៈពេលមធ្យម **៤.០ ថ្ងៃ** ➔ ទទួលបាន **Grade B** (ត្រូវការការបណ្តុះបណ្តាលបន្ថែម)",
          descEn: "Ranks engineers transparently with automated grading based on completed volume, fix success rate, and turnaround speed.",
        },
      ],
      callouts: [
        {
          type: "success",
          titleKm: "យុត្តិធម៌ និងតម្លាភាព ១០០%",
          titleEn: "Objective Performance Metrics",
          contentKm: "ពិន្ទុ KPI ត្រូវបានគណនាដោយស្វ័យប្រវត្តិចេញពីប្រព័ន្ធ Database ផ្ទាល់ ដោយគ្មានការលំអៀង ឬប៉ាន់ស្មានដោយអារម្មណ៍ឡើយ។",
          contentEn: "KPI scores derive directly from database timestamps and completed repair logs with zero subjective bias.",
        },
      ],
    },
    {
      id: "report-sales-crm",
      titleKm: "ក្រុមទី ៤៖ របាយការណ៍ផ្នែកលក់ & CRM (៧ របាយការណ៍)",
      titleEn: "Category 4: Sales & CRM (7 Reports)",
      subtitleKm: "បម្លែងសំបុត្រជួសជុលទៅជាបំពង់លក់៖ តាមដានសម្រង់តម្លៃ, អត្រាជោគជ័យ, ឱកាសលក់ម៉ាស៊ីនថ្មី និងកុងត្រា",
      subtitleEn: "Sales pipeline, quotation win rate, hot leads from unrepairable units, and contract renewals",
      categoryKm: "មជ្ឈមណ្ឌលរបាយការណ៍ទាំង ២៩",
      categoryEn: "Enterprise Reports",
      icon: "TrendingUp",
      route: "/sales-followup",
      reportTableCategory: "sales",
      summaryKm: "ផ្នែកលក់ទាញយកប្រយោជន៍ដោយផ្ទាល់ពីទិន្នន័យជួសជុល ដើម្បីដឹងថាអតិថិជនណាដែលកំពុងរង់ចាំការឆ្លើយតប និងអតិថិជនណាដែលម៉ាស៊ីនខូចធ្ងន់ធ្ងរត្រូវការទិញម៉ាស៊ីនថ្មីជំនួស។",
      summaryEn: "Turns technical service data into actionable sales leads, quotation aging lists, and contract renewal reminders.",
      diagram: {
        titleKm: "លំហូរការងារផ្នែកលក់ & បំពង់លក់ (Sales & CRM Pipeline Flow)",
        titleEn: "Service-to-Sales CRM Pipeline",
        descriptionKm: "ការបម្លែងទិន្នន័យសេវាកម្មទៅជាឱកាសលក់ម៉ាស៊ីនថ្មី និងកិច្ចសន្យាថែទាំប្រចាំឆ្នាំ",
        descriptionEn: "Pipeline bridging repair ticket outcomes into actionable sales opportunities and SLA renewals.",
        nodes: [
          { id: "r_crm1", labelKm: "១. តាមដានសម្រង់តម្លៃរង់ចាំយូរថ្ងៃ (/waiting-confirm)", labelEn: "1. Aging Quotations", badgeKm: "Aging", badgeEn: "Aging", color: "violet", route: "/waiting-confirm" },
          { id: "r_crm2", labelKm: "២. បញ្ជាក់ការលក់ជួសជុល (/confirmed-sale)", labelEn: "2. Confirmed Orders", badgeKm: "Billing", badgeEn: "Billing", color: "emerald", route: "/confirmed-sale" },
          { id: "r_crm3", labelKm: "៣. ឱកាសលក់ម៉ាស៊ីនថ្មី (/sales-leads-report)", labelEn: "3. Replacement Leads", badgeKm: "Hot Leads", badgeEn: "Hot Leads", color: "rose", route: "/sales-leads-report" },
          { id: "r_crm4", labelKm: "៤. ចំណាត់ថ្នាក់អតិថិជន VIP (/top-customers-report)", labelEn: "4. Top Customer Tiers", badgeKm: "VIP Accounts", badgeEn: "VIP Accounts", color: "amber", route: "/top-customers-report" },
          { id: "r_crm5", labelKm: "៥. តាមដានកុងត្រាជិតផុតកំណត់ (/contract-renewal-report)", labelEn: "5. Contract Renewals", badgeKm: "SLA Tracker", badgeEn: "SLA Tracker", color: "indigo", route: "/contract-renewal-report" },
        ],
      },
      steps: [
        {
          number: 1,
          titleKm: "ឧទាហរណ៍សាមញ្ញ៖ បម្លែងម៉ាស៊ីនខូចទៅជាការលក់ម៉ាស៊ីនថ្មី (Hot Sales Leads)",
          titleEn: "Simple Example: Turning Broken Units into New Hardware Sales",
          descKm: "• **សេណារីយ៉ូជាក់ស្តែង៖** អតិថិជនយកម៉ាស៊ីនព្រីនចាស់ឆ្នាំ 2012 មកជួសជុល ជាងពិនិត្យឃើញថាខូច Board និង Drum ដែលថ្លៃជួសជុលអស់ $180 ➔ ភ្ញៀវបដិសេធមិនជួសជុល (Customer Rejected/Unrepairable)។\n• **សកម្មភាពផ្នែកលក់ក្នុង `/sales-leads-report`៖**\n  - សំបុត្រនេះរត់ចូលទៅក្នុងបញ្ជី Hot Sales Leads ភ្លាមៗ\n  - ផ្នែកលក់ទូរស័ព្ទទៅអតិថិជន៖ *«ជម្រាបសួរលោកពូ ដោយសារម៉ាស៊ីនចាស់ថ្លៃជួសជុលខ្ពស់ ($180) ក្រុមហ៊ុនយើងខ្ញុំមានម៉ាស៊ីនម៉ូដែលថ្មីឆ្នាំ 2026 តម្លៃពិសេសត្រឹមតែ $220 មានការធានា ១ ឆ្នាំពេញ...»*\n  - អតិថិជនយល់ព្រមទិញម៉ាស៊ីនថ្មី ➔ **បម្លែងការខាតបង់ជួសជុល ទៅជាការលក់ផលិតផលថ្មីបានជោគជ័យ!**",
          descEn: "Automatically routes rejected or unrepairable tickets into the sales pipeline for replacement hardware sales.",
        },
        {
          number: 2,
          titleKm: "ឧទាហរណ៍សាមញ្ញ៖ តាមដានកុងត្រាថែទាំជិតផុតកំណត់ (Contract Renewal Pipeline)",
          titleEn: "Simple Example: Proactive Contract Renewals",
          descKm: "• ក្នុង `/contract-renewal-report`៖ ប្រព័ន្ធបង្ហាញបញ្ជីកុងត្រាថែទាំប្រចាំឆ្នាំ (Maintenance SLA) របស់ក្រុមហ៊ុនអតិថិជនដែលនៅសល់ ៣០ ថ្ងៃទៀតនឹងផុតកំណត់ ជួយឱ្យផ្នែកលក់ទាក់ទងបន្តកុងត្រាបានមុនកាលកំណត់ មិនឱ្យបាត់បង់អតិថិជន។",
          descEn: "Proactively alerts sales reps 30 days prior to maintenance agreement expiration for contract renewal.",
        },
      ],
      callouts: [
        {
          type: "tip",
          titleKm: "តាមដានសម្រង់តម្លៃរង់ចាំយូរថ្ងៃ (Aging Quotations)",
          titleEn: "Aging Quotation Management",
          contentKm: "ក្នុង `/sales-followup`៖ បង្ហាញសម្រង់តម្លៃណាដែលផ្ញើជូនភ្ញៀវលើសពី ៣ ថ្ងៃហើយមិនទាន់ឆ្លើយតប ដើម្បីឱ្យផ្នែកលក់ទូរស័ព្ទ Follow-up ភ្លាមៗ។",
          contentEn: "Flags quotes pending customer response beyond 3 days for immediate sales follow-up calls.",
        },
      ],
    },
    {
      id: "report-spare-parts-stock",
      titleKm: "ក្រុមទី ៥៖ របាយការណ៍គ្រឿងបន្លាស់ & ស្តុក (៨ របាយការណ៍)",
      titleEn: "Category 5: Spare Parts & Stock (8 Reports)",
      subtitleKm: "ការប្រើប្រាស់គ្រឿងបន្លាស់, ស្តុកកក់ទុក, សៀវភៅកត់ត្រាចលនា, ចលនាស្តុកលឿន/យឺត និងស្តុកនៅទ្រឹង",
      subtitleEn: "Spare parts consumption, hold reservations, movement ledger, velocity, and dead stock audit",
      categoryKm: "មជ្ឈមណ្ឌលរបាយការណ៍ទាំង ២៩",
      categoryEn: "Enterprise Reports",
      icon: "Package",
      route: "/sparepart-usage",
      reportTableCategory: "stock",
      summaryKm: "ក្រុមរបាយការណ៍ស្តុកទាំង ៨ ផ្តល់នូវសវនកម្មពេញលេញលើរាល់គ្រឿងបន្លាស់ក្នុងឃ្លាំង ការពារការបាត់បង់ និងជួយគ្រប់គ្រងទុនបង្វិលដោយរកឃើញទំនិញនៅទ្រឹងលើសពី ១៨០ ថ្ងៃ។",
      summaryEn: "Provides 100% financial and physical inventory visibility, preventing leakage and identifying slow-moving capital.",
      diagram: {
        titleKm: "លំហូរគ្រប់គ្រង & សវនកម្មស្តុកគ្រឿងបន្លាស់ (Stock Intelligence Flow)",
        titleEn: "Spare Parts & Stock Intelligence Flow",
        descriptionKm: "ការតាមដានការប្រើប្រាស់ ចលនាស្តុក និងការរំដោះទុនបង្វិលដែលកកស្ទះក្នុង Dead Stock",
        descriptionEn: "Complete inventory lifecycle from daily usage to dead stock capital recovery.",
        nodes: [
          { id: "r_stk1", labelKm: "១. ការប្រើប្រាស់ជាក់ស្តែង (/sparepart-usage)", labelEn: "1. Usage & Cost", badgeKm: "Consumption", badgeEn: "Consumption", color: "violet", route: "/sparepart-usage" },
          { id: "r_stk2", labelKm: "២. ស្តុកកក់ទុកសម្រាប់សំបុត្រ (/sparepart-hold)", labelEn: "2. Reserved Stock", badgeKm: "Hold Qty", badgeEn: "Hold Qty", color: "cyan", route: "/sparepart-hold" },
          { id: "r_stk3", labelKm: "៣. សៀវភៅកត់ត្រាចលនាស្តុក (/stock-transactions)", labelEn: "3. Movement Ledger", badgeKm: "Double-Entry", badgeEn: "Double-Entry", color: "indigo", route: "/stock-transactions" },
          { id: "r_stk4", labelKm: "៤. ចលនាស្តុកលឿន/យឺត (/stock-movement)", labelEn: "4. Stock Velocity", badgeKm: "Turnover", badgeEn: "Turnover", color: "amber", route: "/stock-movement" },
          { id: "r_stk5", labelKm: "៥. រំដោះទុនកកស្ទះ Dead Stock (/stock-dead)", labelEn: "5. Dead Stock Audit", badgeKm: "Working Capital", badgeEn: "Working Capital", color: "rose", route: "/stock-dead" },
        ],
      },
      steps: [
        {
          number: 1,
          titleKm: "ឧទាហរណ៍សាមញ្ញ៖ ការគណនាតារាងចលនាស្តុកជាក់ស្តែង (Stock Movement Report)",
          titleEn: "Simple Example: Real-World Stock Movement Calculations",
          descKm: "• **សំណួរដែលចង់ដឹង៖** *«តើគ្រឿងបន្លាស់នីមួយៗក្នុងខែនេះ មានចលនាទិញចូល និងដកប្រើប្រាស់យ៉ាងដូចម្តេច?»*\n• **តួលេខជាក់ស្តែងក្នុង `/stock-movement` (ដូចរូបភាពតារាងចលនាស្តុក)៖**\n  - **មុខទំនិញ Fuser Film Sleeve៖**\n    - `Opening (ស្តុកដើមគ្រា)` = **៣៨**\n    - `Stock In (ទិញចូលបន្ថែម)` = **+២២៦**\n    - `Stock Out (ដកទៅជួសជុល)` = **-៣១**\n    - `Net (បម្រែបម្រួលសុទ្ធ)` = **+១៩៥** (+226 - 31)\n    - `Closing / Current Stock (ស្តុកចុងគ្រា)` = **២៣៣** (38 + 195)\n    - `Movements (ប្រតិបត្តិការសរុប)` = **៣៤ ដង** ➔ ជាទំនិញ **Fast-Moving** ដែលមានតម្រូវការខ្ពស់ ត្រូវបញ្ជាទិញស្តុកទុកជាប្រចាំ!\n  - **មុខទំនិញ Tray2 Paper Pickup Roller (RM2-5452-000CN)៖**\n    - `Opening: 5` | `In: 6` | `Out: 11` ➔ `Closing: 0` ➔ ស្តុកសល់ **០** (Out of Stock) ប្រព័ន្ធដាស់តឿនឱ្យបញ្ជាទិញបន្ថែមបន្ទាន់!",
          descEn: "Calculates Opening + Stock In - Stock Out = Net change and Closing stock balance, highlighting fast-moving parts and stockouts.",
        },
        {
          number: 2,
          titleKm: "ឧទាហរណ៍សាមញ្ញ៖ ការរំដោះទុនដែលកកស្ទះក្នុង Dead Stock (Dead Stock Audit)",
          titleEn: "Simple Example: Reclaiming Trapped Capital from Dead Stock",
          descKm: "• ក្នុង `/stock-dead`៖ បង្ហាញគ្រឿងបន្លាស់ចាស់ៗដូចជា `Power Supply Board 2010` ចំនួន ១៥ គ្រឿង ដែលគ្មានចលនាដកប្រើប្រាស់សោះលើសពី **១៨០ ថ្ងៃ** (កកស្ទះទុនបង្វិលសរុប $650) ➔ ជួយឱ្យថ្នាក់គ្រប់គ្រងសម្រេចចិត្តលក់ឡៃឡុង ឬបង្វិលសងអ្នកផ្គត់ផ្គង់ ដើម្បីស្រង់ទុនត្រឡប់មកវិញ។",
          descEn: "Identifies parts with zero movements over 180 days, allowing management to liquidate obsolete inventory and free up trapped working capital.",
        },
      ],
      callouts: [
        {
          type: "success",
          titleKm: "សវនកម្មសុក្រឹតភាពទិន្នន័យ (Audited Double-Entry Ledger)",
          titleEn: "Audited Ledger Guarantee",
          contentKm: "រាល់ការទិញចូល (In), ដកចេញ (Out), ឬកែតម្រូវ (Adjustment) ត្រូវបានកត់ត្រាទុកក្នុង `SparepartStockAuditLog` ជាមួយកាលបរិច្ឆេទ ឈ្មោះអ្នកធ្វើ និងមូលហេតុច្បាស់លាស់ ការពារការបាត់បង់គ្រឿងបន្លាស់ ១០០%។",
          contentEn: "Every stock transaction is recorded immutably in the audit ledger with user ID, timestamp, and ticket references.",
        },
      ],
    },
  ],
};
