/**
 * @file components/docs/content/articlesGettingStarted.ts
 * @description Chapter 1 - signing in, the workspace, and how the pieces fit together. The first thing a new operator reads.
 *
 * Split out of `docsData.ts` so no single file carries the whole catalogue
 * (§1: nothing over ~300 lines). `docsData.ts` assembles these back in
 * chapter order and is still the import path every consumer uses.
 */

import type { DocsSectionGroup } from "./articleTypes";

export const GETTING_STARTED_SECTION: DocsSectionGroup = {
  id: "getting-started",
  titleKm: "ការចាប់ផ្តើម & ស្ថាបត្យកម្មប្រព័ន្ធ",
  titleEn: "Getting Started & Architecture",
  icon: "Rocket",
  badge: "Getting Started",
  articles: [
    {
      id: "getting-started-guide",
      titleKm: "មគ្គុទ្ទេសក៍ចាប់ផ្តើមរហ័សសម្រាប់អ្នកប្រើប្រាស់ដំបូង",
      titleEn: "First-Time User Onboarding Guide",
      subtitleKm: "ចំណុចសំខាន់ៗដែលអ្នកប្រើប្រាស់ដំបូងត្រូវចេះ ចាប់ពីការ Login រហូតដល់ការបញ្ចប់ការងារ និងទាញរបាយការណ៍",
      subtitleEn: "Everything a new operator needs to know: sign-in, daily workflow, parts, and reports",
      categoryKm: "ការចាប់ផ្តើម & ស្ថាបត្យកម្មប្រព័ន្ធ",
      categoryEn: "Getting Started",
      icon: "Compass",
      route: "/login",
      badge: "Essential",
      summaryKm: "សួស្តី និងសូមស្វាគមន៍មកកាន់ប្រព័ន្ធគ្រប់គ្រងសេវាកម្ម និងថែទាំបច្ចេកទេស (Service & Maintenance Portal)! ប្រសិនបើអ្នកជាអ្នកប្រើប្រាស់ថ្មី មគ្គុទ្ទេសក៍នេះនឹងណែនាំអ្នកមួយជំហានម្តងៗនូវចំណុចសំខាន់ៗដែលអ្នកត្រូវយល់ដឹង ដើម្បីបំពេញការងារបានយ៉ាងរលូន ចាប់ពីពេលចូលប្រព័ន្ធលើកដំបូង រហូតដល់ការប្រគល់ម៉ាស៊ីនជូនអតិថិជន។",
      summaryEn: "Welcome to the Service & Maintenance Portal. This complete onboarding roadmap takes new team members through authentication, daily workflows, inventory usage, and executive reporting step-by-step.",
      diagram: {
        titleKm: "ដំណើរការសិក្សា និងបំពេញការងារ ៧ ជំហាន (User Onboarding Journey)",
        titleEn: "7-Step User Onboarding Journey Flowchart",
        descriptionKm: "ផែនទីបង្ហាញផ្លូវសម្រាប់អ្នកប្រើប្រាស់ដំបូង ចាប់ពីការចូលប្រព័ន្ធរហូតដល់ការប្រគល់ការងារ",
        descriptionEn: "Complete roadmap guiding first-time users through the entire daily operational cycle.",
        nodes: [
          { id: "ob1", labelKm: "១. ចូលប្រព័ន្ធ Login (Pass/Face)", labelEn: "1. Sign In (Pass/Face)", badgeKm: "Auth", badgeEn: "Auth", color: "violet", route: "/login" },
          { id: "ob2", labelKm: "២. រៀបចំ Profile & Face ID", labelEn: "2. Setup Face ID", badgeKm: "Profile", badgeEn: "Profile", color: "cyan", route: "/profile" },
          { id: "ob3", labelKm: "៣. ចុះបញ្ជីម៉ូដែលម៉ាស៊ីនចូលថ្មី", labelEn: "3. Received Inventory", badgeKm: "Item Models", badgeEn: "Item Models", color: "indigo", route: "/received-inventory" },
          { id: "ob4", labelKm: "៤. បង្កើតសំបុត្រទទួលម៉ាស៊ីន", labelEn: "4. Receive Item", badgeKm: "Intake", badgeEn: "Intake", color: "emerald", route: "/receive-item" },
          { id: "ob5", labelKm: "៥. ត្រួតពិនិត្យ & ជួសជុល", labelEn: "5. Inspect & Repair", badgeKm: "Operations", badgeEn: "Operations", color: "amber", route: "/pending-repairs" },
          { id: "ob6", labelKm: "៦. ផ្ទៀងផ្ទាត់គុណភាព (QA)", labelEn: "6. QA Verification", badgeKm: "Quality", badgeEn: "Quality", color: "sky", route: "/approve-verify" },
          { id: "ob7", labelKm: "៧. ពិនិត្យ & នាំចេញរបាយការណ៍", labelEn: "7. Reports & Excel", badgeKm: "Analytics", badgeEn: "Analytics", color: "emerald", route: "/templates-settings" },
        ],
      },
      steps: [
        {
          number: 1,
          titleKm: "ការចូលប្រើប្រាស់ប្រព័ន្ធ (Sign In)",
          titleEn: "Step 1: Sign In to the Portal",
          descKm: "ចូលទៅកាន់ទំព័រ Login (`/login`) ដោយប្រើឈ្មោះគណនី និងពាក្យសម្ងាត់ដែលបានផ្តល់ជូន ឬប្រើការស្កេនផ្ទៃមុខ Face ID ប្រសិនបើបានចុះឈ្មោះរួច។",
          descEn: "Navigate to the Login page and authenticate using your assigned credentials, biometric Face ID, or mobile pairing.",
        },
        {
          number: 2,
          titleKm: "រៀបចំគណនីផ្ទាល់ខ្លួន & ចុះឈ្មោះផ្ទៃមុខ (Profile Setup)",
          titleEn: "Step 2: Profile & Biometric Setup",
          descKm: "ចូលទៅកាន់ `/profile` ដើម្បីពិនិត្យមើលឈ្មោះ ប្តូរពាក្យសម្ងាត់ផ្ទាល់ខ្លួន និងថតស្កេនផ្ទៃមុខ Face ID ដើម្បីអាចចូលប្រើលើកក្រោយដោយស្វ័យប្រវត្តិក្នុរយៈពេល ១ វិនាទី។",
          descEn: "Visit your Profile to change your default password and register your Face ID for instant one-second biometric sign-ins.",
        },
        {
          number: 3,
          titleKm: "ចុះបញ្ជីម៉ូដែលម៉ាស៊ីនចូលថ្មី (/received-inventory)",
          titleEn: "Step 3: Register New Item Models",
          descKm: "ប្រសិនបើអតិថិជនយកម៉ាស៊ីនដែលជាម៉ូដែលថ្មីមិនធ្លាប់មានក្នុងប្រព័ន្ធ ត្រូវចូលទៅកាន់ `/received-inventory` ដើម្បីចុះឈ្មោះ Item Name, Serial Number, និង Item Type ជាមុនសិន។",
          descEn: "If an incoming device is a new model, register it first in Received Inventory (/received-inventory) before creating the intake ticket.",
        },
        {
          number: 4,
          titleKm: "របៀបទទួលម៉ាស៊ីនបង្កើតសំបុត្រជួសជុល (/receive-item)",
          titleEn: "Step 4: Creating Repair Tickets",
          descKm: "ចូលទៅ `/receive-item` ដើម្បីជ្រើសរើសម៉ាស៊ីនដែលបានចុះបញ្ជីរួច ភ្ជាប់ជាមួយក្រុមហ៊ុនអតិថិជន កត់ត្រារោគសញ្ញាខូច រួចចុច Save ដើម្បីបោះពុម្ពប័ណ្ណបង្កាន់ដៃទទួល (Receipt Slip) ជូនអតិថិជន។",
          descEn: "Open Receive Item (/receive-item), select the registered item, link customer details and symptoms, and print the intake receipt.",
        },
        {
          number: 5,
          titleKm: "ការត្រួតពិនិត្យ និងស្នើសុំគ្រឿងបន្លាស់ (Inspection & Parts)",
          titleEn: "Step 5: Diagnostic Inspection & Parts Request",
          descKm: "សំបុត្រប្តូរទៅជា Status ID 10 (Inspecting)។ ជាងបច្ចេកទេសបើកមើលក្នុង `/inspect-item` ដើម្បីធ្វើតេស្ត កត់ត្រាលទ្ធផលពិនិត្យ (Inspection) និងជ្រើសរើសគ្រឿងបន្លាស់ដែលត្រូវប្តូរ។ បន្ទាប់មក ផ្នែកឃ្លាំងនឹងប្រគល់គ្រឿងបន្លាស់ក្នុង `/spare-request`។",
          descEn: "Technician opens Inspect Item (/inspect-item), records diagnostic findings, and requests required parts from the warehouse.",
        },
        {
          number: 6,
          titleKm: "ការបញ្ចប់ការជួសជុល និងត្រួតពិនិត្យគុណភាព (QA Sign-Off)",
          titleEn: "Step 6: Completion & QA Approval",
          descKm: "ពេលជួសជុលរួចរាល់ ជាងចុច 'Complete Repair' ដើម្បីឱ្យ Supervisor ធ្វើតេស្តផ្ទៀងផ្ទាត់គុណភាពចុងក្រោយក្នុង `/approve-verify` មុននឹងទាក់ទងអតិថិជនមកទទួលក្នុង `/completed-repairs`។",
          descEn: "Technician submits the finished job for supervisor verification. Once approved in Approve Verify, the ticket transitions to Finished.",
        },
        {
          number: 7,
          titleKm: "ការទាញយករបាយការណ៍ និងការចាកចេញ (Reports & Sign Out)",
          titleEn: "Step 7: Analytics & Safe Sign Out",
          descKm: "ពិនិត្យមើលរបាយការណ៍ការងារប្រចាំថ្ងៃ (`/daily-report`) ឬរបាយការណ៍សហគ្រាសទាំង ២៩ ក្នុង `/templates-settings`។ ពេលចប់ការងារ សូមចុចប៊ូតុង 'Sign Out' ដើម្បីសុវត្ថិភាព។",
          descEn: "Review your performance in the daily reports or explore the 29-report suite. Remember to sign out securely at the end of your shift.",
        },
      ],
      callouts: [
        {
          type: "tip",
          titleKm: "ផ្លូវកាត់ក្តារចុចសំខាន់ៗ (Keyboard Shortcuts)",
          titleEn: "Productivity Shortcuts",
          contentKm: "ចុច `Ctrl + K` ដើម្បីបើកប្រអប់ស្វែងរករហ័ស (Global Search) ឬចុច `/` នៅលើទំព័រឯកសារនេះ ដើម្បីស្វែងរកមាតិកាភ្លាមៗ។",
          contentEn: "Use Ctrl+K for global menu navigation or press / anywhere in docs to jump straight to search.",
        },
      ],
    },
    {
      id: "login-process-flow",
      titleKm: "គំនូសបំព្រួញលំហូរដំណើរការ Login គ្រប់ជម្រើស",
      titleEn: "Complete Login Process & Authentication Flowchart",
      subtitleKm: "លំហូរផ្ទៀងផ្ទាត់តាម Mobile 2FA (Face Login/PIN, Match Number, Scan QR) & ជម្រើស Sign In ផ្សេងទៀត",
      subtitleEn: "Multi-modal authentication breakdown: Mobile 2FA (Face/PIN, Match Number, Scan QR), Password, Local Face, Passkeys",
      categoryKm: "ការចាប់ផ្តើម & ស្ថាបត្យកម្មប្រព័ន្ធ",
      categoryEn: "Getting Started",
      icon: "Key",
      route: "/login",
      badge: "Auth Flow",
      summaryKm: "ប្រព័ន្ធគាំទ្រនូវយន្តការចូលប្រើប្រាស់ចម្រុះ (Multi-Modal Authentication) ដោយផ្តោតលើ Mobile 2FA តាមរយៈ App CAM ID (Face Login/PIN, Match Number, Scan QR) រួមជាមួយ Password Login, Local Face ID (Webcam) និង WebAuthn Passkeys។ រាល់ការ Login ទាំងអស់ទទួលបាន JWT Access & Refresh Token ភ្ជាប់ Role-Based Access Control (RBAC) ត្រឹមត្រូវ។",
      summaryEn: "The authentication engine seamlessly verifies identities via Mobile 2FA (Face Login/PIN, Match Number, Scan QR) alongside Password, Local Webcam Face ID, and WebAuthn Passkeys, issuing secure JWT tokens with RBAC claims.",
      diagram: {
        titleKm: "គំនូសបំព្រួញលំហូរ Login គ្រប់ជម្រើស (Complete Login Process Flow)",
        titleEn: "Complete Multi-Modal Login Process Flowchart",
        descriptionKm: "បង្ហាញលំហូរនៃការផ្ទៀងផ្ទាត់តាមជម្រើសនីមួយៗ និងការបញ្ជូនទៅកាន់ Dashboard តាម Role",
        descriptionEn: "Visual breakdown of all authentication channels, backend token resolution, and role-based routing.",
        nodes: [
          { id: "lp1", labelKm: "១. Mobile 2FA (Face Login / PIN)", labelEn: "1. Mobile Face/PIN", badgeKm: "Push Challenge", badgeEn: "Push Challenge", color: "cyan", route: "/login" },
          { id: "lp2", labelKm: "២. Match Number (ផ្គូផ្គងលេខ)", labelEn: "2. Match Number", badgeKm: "Anti-MFA Bombing", badgeEn: "Anti-MFA Bombing", color: "amber", route: "/login" },
          { id: "lp3", labelKm: "៣. ស្កេន QR (Scan QR Code)", labelEn: "3. Scan QR Code", badgeKm: "Dynamic QR", badgeEn: "Dynamic QR", color: "indigo", route: "/face-link" },
          { id: "lp4", labelKm: "៤. Password, Local Face & Passkey", labelEn: "4. Alternative Methods", badgeKm: "Other Methods", badgeEn: "Other Methods", color: "violet", route: "/login" },
          { id: "lp5", labelKm: "៥. បង្កើត JWT & Refresh Token", labelEn: "5. Issue JWT Tokens", badgeKm: ".NET 8 API", badgeEn: ".NET 8 API", color: "emerald" },
          { id: "lp6", labelKm: "៦. បែងចែកទៅ Dashboard តាម Role", labelEn: "6. Role-Based Routing", badgeKm: "RBAC Routing", badgeEn: "RBAC Routing", color: "emerald", route: "/" },
        ],
      },
      steps: [
        {
          number: 1,
          titleKm: "Mobile 2FA (ជម្រើស ១)៖ Face Login ឬ PIN (Push Notification)",
          titleEn: "Mobile 2FA Option 1: Face Login or PIN",
          descKm: "អ្នកប្រើវាយ Username រួចចុច 'ផ្ញើសំណើ Face Login ឬ PIN'។ ប្រព័ន្ធផ្ញើ Push Challenge ទៅកាន់ទូរស័ព្ទ App CAM ID -> អ្នកប្រើចុច Approve និងស្កេនផ្ទៃមុខ ឬវាយលេខ PIN ៦ខ្ទង់ -> SignalR WebSocket បាញ់ Token ចូល Desktop Login ភ្លាមៗ (សុពលភាព ៩០ វិនាទី)។",
          descEn: "User submits username and clicks Send. CAM ID App receives a push notification, prompts for face scan or 6-digit PIN, and SignalR WebSocket automatically completes login on the desktop (90s timeout).",
        },
        {
          number: 2,
          titleKm: "Mobile 2FA (ជម្រើស ២)៖ Match Number (សុវត្ថិភាពខ្ពស់ប្រឆាំង MFA Fatigue)",
          titleEn: "Mobile 2FA Option 2: Number Matching Verification",
          descKm: "អ្នកប្រើវាយ Username -> កុំព្យូទ័របង្ហាញលេខកូដផ្គូផ្គង (Match Number ឧ. 42) -> App CAM ID លើទូរស័ព្ទបង្ហាញជម្រើសលេខ -> អ្នកប្រើត្រូវចុចលេខដូចគ្នាឱ្យត្រូវទើបអាចស្កេន Face/PIN បាន។ យន្តការនេះការពារការវាយប្រហារ MFA Fatigue / Push Bombing ដោយជោគជ័យ។",
          descEn: "Computer displays a random Match Number (e.g. 42). The user must select the matching number on their CAM ID phone app before authenticating biometrically, preventing accidental approvals and MFA fatigue attacks.",
        },
        {
          number: 3,
          titleKm: "Mobile 2FA (ជម្រើស ៣)៖ ស្កេន QR (Scan QR Code)",
          titleEn: "Mobile 2FA Option 3: Dynamic QR Code Scan",
          descKm: "កុំព្យូទ័របង្កើត Dynamic Session QR (សុពលភាព ៥ នាទី) -> អ្នកប្រើបើក App CAM ID លើទូរស័ព្ទស្កេន QR លើកញ្ចក់អេក្រង់ -> ផ្ទៀងផ្ទាត់ Face/PIN លើទូរស័ព្ទ -> SignalR Handshake បញ្ជូន Token ចូលកុំព្យូទ័រដោយស្វ័យប្រវត្តិ។",
          descEn: "Desktop generates a dynamic encrypted session QR (5-minute lifetime). The operator scans the on-screen code using the CAM ID app, verifies biometrics on phone, and the desktop signs in automatically.",
        },
        {
          number: 4,
          titleKm: "ជម្រើស Sign In ផ្សេងទៀត (Password, Local Face ID & Passkeys)",
          titleEn: "Alternative Sign-In Methods",
          descKm: "• Password Login: បញ្ចូល Username & Password ស្តង់ដារ\n• Local Face ID (Webcam): ស្កេនមុខតាមកាមេរ៉ាកុំព្យូទ័រផ្ទាល់ (>90% 128D Vector Match)\n• WebAuthn Passkeys: ចូលដោយប្រើ Windows Hello, Apple Touch ID ឬ Security Key FIDO2 ដោយមិនបាច់វាយពាក្យសម្ងាត់។",
          descEn: "Standard Username/Password credentials, Local Webcam Face ID (128D vector >90% match), and WebAuthn hardware passkeys (Windows Hello, Touch ID, FIDO2).",
        },
        {
          number: 5,
          titleKm: "ការបែងចែកទំព័រស្វ័យប្រវត្តិតាមតួនាទី (Post-Login RBAC Routing)",
          titleEn: "Post-Login Role-Based Routing",
          descKm: "ពេល Login ជោគជ័យ UserManagementAPI ចេញ JWT Token + Refresh Token ភ្ជាប់ Claims & Roles៖ Admin (គ្រប់គ្រងទាំងអស់), Supervisor (QA & របាយការណ៍), Technician (ផ្ទាំងជួសជុល) និង Front Desk (ទំព័រទទួលម៉ាស៊ីន Intake)។",
          descEn: "Upon successful authentication, UserManagementAPI issues signed JWT + Refresh tokens with RBAC claims routing to Admin, Supervisor, Technician, or Front Desk workspaces.",
        },
      ],
      callouts: [
        {
          type: "tip",
          titleKm: "ការការពារសុវត្ថិភាពកម្រិតខ្ពស់តាម Match Number",
          titleEn: "Enterprise Protection via Number Matching",
          contentKm: "មុខងារ 'Match Number' ត្រូវបានរចនាឡើងដើម្បីការពារកុំឱ្យមានការច្រឡំចុច Approve ដោយអចេតនា នៅពេលមានជនខិលខូចព្យាយាម Login គណនីរបស់អ្នកពីចម្ងាយ។",
          contentEn: "Number matching ensures that the person approving the login on their mobile phone is actively looking at the corresponding desktop screen.",
        },
      ],
    },
    {
      id: "system-architecture",
      titleKm: "ស្ថាបត្យកម្មប្រព័ន្ធទូទៅ",
      titleEn: "System Architecture & Technology Stack",
      subtitleKm: "ទិដ្ឋភាពទូទៅនៃបច្ចេកវិទ្យា Microservice, Frontend Next.js 16, Backend .NET 8 និង SQL Server",
      subtitleEn: "High-level overview of Next.js 16 App Router, .NET 8 Minimal API, and SQL Server Ledger",
      categoryKm: "ការចាប់ផ្តើម & ស្ថាបត្យកម្មប្រព័ន្ធ",
      categoryEn: "Getting Started",
      icon: "Cpu",
      route: "/docs",
      summaryKm: "ប្រព័ន្ធគ្រប់គ្រងសេវាកម្ម និងថែទាំបច្ចេកទេស (Service & Maintenance Portal) ត្រូវបានបង្កើតឡើងដោយរួមបញ្ចូលគ្នានូវបច្ចេកវិទ្យាទំនើបបំផុត ដើម្បីធានាបាននូវល្បឿនលឿន សុវត្ថិភាពខ្ពស់ និងការគណនាស្តុកជាក់ស្តែង ១០០% ដោយគ្មានភាពលម្អៀង។",
      summaryEn: "The CAM ID Service & Maintenance Portal integrates a cutting-edge reactive frontend and a resilient .NET 8 microservice architecture with complete audit ledger guarantees.",
      diagram: {
        titleKm: "គំនូសបំព្រួញស្ថាបត្យកម្មប្រព័ន្ធ ៣ ជាន់ (Three-Tier Architecture)",
        titleEn: "Three-Tier System Architecture Diagram",
        descriptionKm: "Frontend ទំនាក់ទំនងជាមួយ Backend តាមរយៈ Next.js Proxy Route ប្រកបដោយសុវត្ថិភាពខ្ពស់ និងទិន្នន័យស្របគ្នាគ្រប់ពេល។",
        descriptionEn: "Frontend communicates securely via Next.js Proxy Routes to .NET 8 backend services and databases.",
        nodes: [
          { id: "fe", labelKm: "TestingReact (Next.js 16)", labelEn: "TestingReact (Next.js 16)", badgeKm: "UI / Client", badgeEn: "UI / Client", color: "violet", route: "/" },
          { id: "proxy", labelKm: "Next.js API Proxy", labelEn: "Next.js API Proxy", badgeKm: "Gateway", badgeEn: "Gateway", color: "indigo", route: "/api/proxy" },
          { id: "techApi", labelKm: "TechnicalService.API (:8000)", labelEn: "TechnicalService.API (:8000)", badgeKm: "Workflow & Stock", badgeEn: "Workflow & Stock", color: "cyan" },
          { id: "userApi", labelKm: "UserManagementAPI (:8087)", labelEn: "UserManagementAPI (:8087)", badgeKm: "Auth & Face ID", badgeEn: "Auth & Face ID", color: "sky" },
          { id: "dbTech", labelKm: "TechnicalService DB", labelEn: "TechnicalService DB", badgeKm: "SQL Server", badgeEn: "SQL Server", color: "emerald" },
          { id: "dbUser", labelKm: "UserManagement DB", labelEn: "UserManagement DB", badgeKm: "Identity DB", badgeEn: "Identity DB", color: "amber" },
        ],
      },
      steps: [
        {
          number: 1,
          titleKm: "Frontend Client (Next.js 16 & React 19)",
          titleEn: "Frontend Client (Next.js 16 & React 19)",
          descKm: "ប្រើប្រាស់ App Router ជាមួយ Tailwind CSS 4 និង ExcelJS សម្រាប់ការបង្ហាញទិន្នន័យរហ័ស គាំទ្រការនាំចេញ Excel ភ្លាមៗ និងទម្រង់បោះពុម្ព A4 យ៉ាងស្រស់ស្អាត។",
          descEn: "Next.js 16 App Router with Tailwind CSS 4 and ExcelJS engine for instant report rendering and A4 printable certificates.",
        },
        {
          number: 2,
          titleKm: "Technical Service API (.NET 8 Minimal API)",
          titleEn: "Technical Service API (.NET 8 Minimal API)",
          descKm: "គ្រប់គ្រងរាល់សកម្មភាពសំបុត្រជួសជុល (Ticket Lifecycle), ការកាត់ស្តុកគ្រឿងបន្លាស់ (Stock Ledger), ការកែតម្រូវ និងការទាញរបាយការណ៍សង្ខេបប្រចាំឆ្នាំ។",
          descEn: "Drives service ticket lifecycle, spare parts allocation, inventory movements, and annual performance matrices.",
        },
        {
          number: 3,
          titleKm: "User Management & Biometrics API (.NET 8)",
          titleEn: "User Management & Biometrics API (.NET 8)",
          descKm: "គ្រប់គ្រងសុវត្ថិភាពការចូលប្រើ (JWT Tokens), ប្រព័ន្ធសម្គាល់ផ្ទៃមុខ (Face Recognition), Passkey (WebAuthn) និង SignalR Real-time Hub សម្រាប់ភ្ជាប់ទូរស័ព្ទដៃ។",
          descEn: "Handles JWT authentication, biometric face recognition, WebAuthn Passkeys, and SignalR live mobile pairing.",
        },
      ],
      callouts: [
        {
          type: "success",
          titleKm: "ទិន្នន័យស្តុកមានសុក្រឹតភាព ១០០%",
          titleEn: "100% Stock Ledger Integrity",
          contentKm: "រាល់ការដក ឬបន្ថែមគ្រឿងបន្លាស់ត្រូវបានកត់ត្រាក្នុង `SparepartStockAuditLog` ដោយស្វ័យប្រវត្តិតាមរយៈ Database Transactions ធានាមិនឱ្យបាត់បង់ទិន្នន័យឡើយ។",
          contentEn: "Every stock movement is recorded in the SparepartStockAuditLog with full ACID transaction guarantees.",
        },
      ],
    },
    {
      id: "face-link",
      titleKm: "ការភ្ជាប់ Face ID តាមទូរស័ព្ទ (Face Link)",
      titleEn: "Mobile Face Link Pairing",
      subtitleKm: "បច្ចេកវិទ្យា Real-time SignalR សម្រាប់បញ្ជូនរូបថតស្កេនផ្ទៃមុខពីទូរស័ព្ទដៃ (គាំទ្រ Skip Face ជាមួយ Master 6-digit PIN)",
      subtitleEn: "Pair smartphone camera via SignalR WebSocket bridge with biometric face scan or Master 6-digit PIN skip",
      categoryKm: "ការចាប់ផ្តើម & ស្ថាបត្យកម្មប្រព័ន្ធ",
      categoryEn: "Getting Started",
      icon: "Smartphone",
      route: "/face-link",
      summaryKm: "ក្នុងករណីកុំព្យូទ័រលើតុ (Desktop PC) គ្មានកាមេរ៉ា អ្នកប្រើប្រាស់អាចប្រើទូរស័ព្ទដៃស្កេន QR Code ដើម្បីប្រើកាមេរ៉ាទូរស័ព្ទស្កេនមុខ ហើយបញ្ជូនទិន្នន័យចូលកុំព្យូទ័រភ្លាមៗ។ សម្រាប់ការភ្ជាប់នេះ អ្នកប្រើប្រាស់ក៏អាច Skip Face សិនបានដែរ ដោយតម្រូវឱ្យបញ្ចូល Master 6-digit PIN ដើម្បីការពារសុវត្ថិភាព។",
      summaryEn: "If your workstation lacks a webcam, scan the on-screen QR code with your phone to use the mobile camera as an instant wireless biometric scanner, or use Master 6-digit PIN to safely skip face scan.",
      diagram: {
        titleKm: "លំហូរការងារ Face Link តាមទូរស័ព្ទ (Mobile Face Link Flow)",
        titleEn: "Mobile Face Link Pairing Pipeline",
        descriptionKm: "ដំណើរការភ្ជាប់ SignalR Real-time WebSocket រវាងកុំព្យូទ័រ និងទូរស័ព្ទដៃ",
        descriptionEn: "Live biometric bridge architecture connecting PC and smartphone via SignalR.",
        nodes: [
          { id: "fl1", labelKm: "១. កុំព្យូទ័របង្កើត QR Code", labelEn: "1. Desktop Generates QR", badgeKm: "Session ID", badgeEn: "Session ID", color: "violet", route: "/face-link" },
          { id: "fl2", labelKm: "២. ទូរស័ព្ទស្កេន QR ភ្ជាប់ Session", labelEn: "2. Mobile Scans QR", badgeKm: "Pairing", badgeEn: "Pairing", color: "cyan" },
          { id: "fl3", labelKm: "៣. ស្កេនមុខ ឬ Skip ជាមួយ Master PIN", labelEn: "3. Face / Master PIN", badgeKm: "Master PIN", badgeEn: "Master PIN", color: "indigo" },
          { id: "fl4", labelKm: "៤. SignalR បញ្ជូន Signal Success", labelEn: "4. SignalR WebSocket Event", badgeKm: "Real-time", badgeEn: "Real-time", color: "amber" },
          { id: "fl5", labelKm: "៥. កុំព្យូទ័រ Login ដោយស្វ័យប្រវត្តិ", labelEn: "5. Desktop Auto Sign-In", badgeKm: "Done", badgeEn: "Done", color: "emerald", route: "/" },
        ],
      },
      steps: [
        {
          number: 1,
          titleKm: "បើកផ្ទាំង Face Link លើកុំព្យូទ័រ",
          titleEn: "Open Face Link on Desktop",
          descKm: "នៅលើអេក្រង់ Login ចុចយក 'Pair with Mobile Phone' ឬចូលទៅ `/face-link` ដើម្បីបង្ហាញ QR Code។",
          descEn: "Click Pair with Mobile Phone on the login screen to display the secure session QR code.",
        },
        {
          number: 2,
          titleKm: "ស្កេន QR Code ដោយទូរស័ព្ទដៃ",
          titleEn: "Scan QR Code on Phone",
          descKm: "ប្រើកាមេរ៉ាទូរស័ព្ទដៃស្កេន QR Code ដើម្បីបើកទំព័រស្កេនមុខនៅលើទូរស័ព្ទ។",
          descEn: "Scan the QR code with your phone camera to open the mobile biometric capture interface.",
        },
        {
          number: 3,
          titleKm: "ស្កេនមុខ ឬ Skip សិនដោយវាយ Master 6-digit PIN",
          titleEn: "Capture Face or Skip via Master 6-digit PIN",
          descKm: "នៅលើទូរស័ព្ទដៃ អ្នកប្រើប្រាស់អាចថតស្កេនផ្ទៃមុខជាក់ស្តែង។ ប៉ុន្តែប្រសិនបើមិនទាន់ចង់ស្កេនមុខ ឬកាមេរ៉ាមានបញ្ហា អ្នកប្រើ **អាចចុច Skip Face សិនបាន ដោយទាល់តែបញ្ចូល Master 6-digit PIN ត្រឹមត្រូវ** ដើម្បីការពារសុវត្ថិភាព និងផ្ទៀងផ្ទាត់សិទ្ធិម្ចាស់គណនី។",
          descEn: "User can capture facial biometrics on mobile, or choose to skip face scan by entering the secure Master 6-digit PIN to ensure zero security compromise.",
        },
        {
          number: 4,
          titleKm: "SignalR Handshake & ចូលប្រើស្វ័យប្រវត្តិ",
          titleEn: "SignalR Handshake & Auto Sign-In",
          descKm: "ពេលទូរស័ព្ទផ្ទៀងផ្ទាត់មុខ ឬ Master PIN ជោគជ័យ ប្រព័ន្ធ SignalR នឹងបញ្ជូន Token ទៅកាន់កុំព្យូទ័រ ហើយកុំព្យូទ័រនឹងចូលប្រើប្រព័ន្ធភ្លាមៗដោយស្វ័យប្រវត្តិ។",
          descEn: "Once authenticated on the mobile device via face or Master PIN, SignalR securely transmits the session token to your desktop, signing you in instantly.",
        },
      ],
      callouts: [
        {
          type: "tip",
          titleKm: "ជម្រើស Skip Face ជាមួយ Master 6-digit PIN",
          titleEn: "Master 6-digit PIN Fallback Protection",
          contentKm: "មុខងារ Skip Face ត្រូវបានការពារយ៉ាងតឹងរ៉ឹង៖ ប្រព័ន្ធមិនអនុញ្ញាតឱ្យរំលងដោយសេរីឡើយ គឺត្រូវតែវាយបញ្ចូល Master 6-digit PIN ឱ្យបានត្រឹមត្រូវ ទើបប្រព័ន្ធអនុញ្ញាតឱ្យបញ្ជូន Token ចូលកុំព្យូទ័រ។",
          contentEn: "Skipping face verification strictly mandates entering the authorized Master 6-digit PIN, safeguarding against unauthorized device access.",
        },
      ],
    },
    {
      id: "mobile-barcode-scanner",
      titleKm: "ការភ្ជាប់ទូរស័ព្ទធ្វើជា Barcode Scanner (Phone Link & CAM ID App)",
      titleEn: "Mobile Companion Barcode Scanner (Phone Link & CAM ID App)",
      subtitleKm: "បច្ចេកវិទ្យា Server-Sent Events (SSE) បម្លែងទូរស័ព្ទដៃទៅជាម៉ាស៊ីនស្កេន Barcode / Serial Number ឥតខ្សែ ទាំងលើ Web Browser និងកម្មវិធី CAM ID App",
      subtitleEn: "Transform any smartphone into an ultra-fast wireless barcode scanner for desktop inputs via Web and CAM ID App",
      categoryKm: "ការចាប់ផ្តើម & ស្ថាបត្យកម្មប្រព័ន្ធ",
      categoryEn: "Getting Started",
      icon: "QrCode",
      route: "/scanner",
      summaryKm: "មុខងារ Mobile Companion Barcode Scanner (Phone Link) អនុញ្ញាតឱ្យអ្នកប្រើប្រាស់បម្លែងទូរស័ព្ទដៃ (iPhone ឬ Android) ទៅជាម៉ាស៊ីនស្កេន Barcode & QR Code ឥតខ្សែល្បឿនលឿន ដោយមិនបាច់ទិញម៉ាស៊ីនស្កេនថ្លៃៗ ឬដោតខ្សែ USB ឡើយ។ អាចប្រើបានទាំងលើ Web Browser ធម្មតា និងកម្មវិធី CAM ID Mobile App។ ពេលទូរស័ព្ទស្កេនបាន Barcode ឬ Serial Number វានឹងរត់ចូលទៅបំពេញក្នុងប្រអប់ Cursor លើកុំព្យូទ័រដោយស្វ័យប្រវត្តិ (Instant Auto-Fill) ក្នុងរយៈពេលត្រឹមតែ ០.១ វិនាទី!",
      summaryEn: "The Mobile Companion Barcode Scanner transforms your smartphone into a high-precision wireless laser scanner via Web Browser or CAM ID App. Scanned barcodes and serial numbers instantly auto-fill into whichever desktop field your cursor is focused on.",
      diagram: {
        titleKm: "លំហូរការងារភ្ជាប់ទូរស័ព្ទស្កេន Barcode (Mobile Scanner Bridge Architecture)",
        titleEn: "Mobile Companion Barcode Scanner Pipeline",
        descriptionKm: "ការតភ្ជាប់ Real-time Server-Sent Events (SSE) រវាងកុំព្យូទ័រ និងទូរស័ព្ទដៃ ជាមួយ Multi-Tab Broadcast",
        descriptionEn: "High-speed SSE and BroadcastChannel bridge syncing scanned barcodes directly to active desktop inputs.",
        nodes: [
          { id: "ms1", labelKm: "១. ចុចប៊ូតុង '📱 តភ្ជាប់ទូរស័ព្ទ' លើ Header", labelEn: "1. Click 'Connect Phone'", badgeKm: "Desktop Header", badgeEn: "Desktop Header", color: "violet", route: "/" },
          { id: "ms2", labelKm: "២. ស្កេន QR លើអេក្រង់តាម Phone / CAM ID App", labelEn: "2. Scan Session QR", badgeKm: "Session Bridge", badgeEn: "Session Bridge", color: "cyan", route: "/scanner" },
          { id: "ms3", labelKm: "៣. ភ្ជាប់ជោគជ័យ (Permanent Pairing)", labelEn: "3. Paired & Ready", badgeKm: "Phone Connected", badgeEn: "Phone Connected", color: "indigo" },
          { id: "ms4", labelKm: "៤. ស្កេន Barcode តាមកាមេរ៉ា/រូបថត/វាយដៃ", labelEn: "4. Live Scan / Gallery / PIN", badgeKm: "ZXing Engine", badgeEn: "ZXing Engine", color: "amber" },
          { id: "ms5", labelKm: "៥. បំពេញទិន្នន័យស្វ័យប្រវត្តិចូលកុំព្យូទ័រ (Auto-Fill)", labelEn: "5. Instant Auto-Fill", badgeKm: "0.1s Real-time", badgeEn: "0.1s Real-time", color: "emerald" },
        ],
      },
      steps: [
        {
          number: 1,
          titleKm: "របៀបភ្ជាប់ទូរស័ព្ទដៃជាមួយកុំព្យូទ័រ (Step 1: Phone Pairing)",
          titleEn: "Pair Phone with Desktop",
          descKm: "• នៅលើកុំព្យូទ័រ៖ ចុចប៊ូតុង **'📱 តភ្ជាប់ទូរស័ព្ទ' (Connect Phone)** នៅលើ Header ខាងលើ ដើម្បីបើកផ្ទាំង QR Code តភ្ជាប់។\n• នៅលើទូរស័ព្ទដៃ៖\n  - **វិធីទី ១ (កាមេរ៉ាទូរស័ព្ទ / Web):** បើក Camera លើទូរស័ព្ទ (iOS / Android) ស្កេន QR Code លើកញ្ចក់អេក្រង់កុំព្យូទ័រ វានឹងបើកទំព័រ `/scanner` ក្នុង Safari ឬ Chrome ភ្លាមៗ។\n  - **វិធីទី ២ (កម្មវិធី CAM ID Mobile App):** បើក CAM ID App ចុចយក Menu **'Scanner'** ឬស្កេន QR ដើម្បីភ្ជាប់។\n• ប្រព័ន្ធនឹងបង្ហាញស្ថានភាពពណ៌បៃតង `🟢 ទូរស័ព្ទបានភ្ជាប់ជោគជ័យ (Phone Connected)`។ ការភ្ជាប់នេះជា **Permanent Pairing** គឺរក្សាជាប់រហូត មិនបាច់ស្កេនតភ្ជាប់ម្តងទៀតរាល់ពេលប្រើឡើយ!",
          descEn: "Click 'Connect Phone' on the desktop header. Scan the QR code using your phone camera (Web mode) or via the CAM ID mobile app. Desktop will display 'Phone Connected' with permanent pairing.",
        },
        {
          number: 2,
          titleKm: "មុខងារស្កេនលើទូរស័ព្ទដៃ (Step 2: Scanning Capabilities)",
          titleEn: "Mobile Scanning Modes & Tools",
          descKm: "ផ្ទាំង Mobile Scanner គាំទ្រជម្រើសស្កេនសម្បូរបែប៖\n• **Live Camera Stream:** ស្កេន Barcode 1D/2D គ្រប់ប្រភេទ (Code 128, Code 39, QR Code, EAN-13, DataMatrix) យ៉ាងរហ័ស ជាមួយសំឡេង Beep បញ្ជាក់។\n• **Flashlight / Torch (ពិល):** បើកពិលទូរស័ព្ទសម្រាប់ស្កេននៅកន្លែងខ្វះពន្លឺ ឬក្នុងឃ្លាំងងងឹត។\n• **Upload រូបថត (Gallery / Photo):** ករណី Barcode ព្រិលខ្លាំង ឬបាក់បែក អាចចុចថតរូបភាពច្បាស់ ឬរើសរូបភាពពី Gallery ដើម្បីឱ្យប្រព័ន្ធ AI អានទិន្នន័យ។\n• **វាយលេខកូដដោយដៃ (Manual Input):** បើ Barcode រលុប អាចវាយលេខផ្ទាល់លើទូរស័ព្ទ រួចចុច Send ចូលកុំព្យូទ័រ។",
          descEn: "Supports high-speed live camera scanning (ZXing multi-format), torch toggle for dark environments, photo gallery image upload for damaged barcodes, and manual code keypad entry.",
        },
        {
          number: 3,
          titleKm: "ការបំពេញទិន្នន័យស្វ័យប្រវត្តិចូលកុំព្យូទ័រ (Step 3: Instant Auto-Fill)",
          titleEn: "Desktop Auto-Fill & Cursor Injection",
          descKm: "នៅលើកុំព្យូទ័រ អ្នកប្រើប្រាស់មិនបាច់ Copy/Paste ឡើយ៖\n• គ្រាន់តែចុច Cursor ដាក់ក្នុងប្រអប់ដែលចង់បញ្ចូល (ឧទាហរណ៍៖ ប្រអប់ **Serial Number** ក្នុង `/received-inventory` ឬ `/receive-item`, ឬប្រអប់ **Part Barcode** ក្នុង `/spareparts` និង `/spare-request`)។\n• ពេលទូរស័ព្ទស្កេន Barcode បានជោគជ័យ ទិន្នន័យនឹង **រត់ចូលទៅវាយបំពេញក្នុងប្រអប់នោះដោយស្វ័យប្រវត្តិ** អមដោយសំឡេង Beep លើកុំព្យូទ័រ!\n• បើមិនបានដាក់ Cursor ក្នុងប្រអប់ណាទេ Barcode នឹងរត់ចូលទៅកាន់ **Global Search Bar** ដើម្បីស្វែងរកសំបុត្រ ឬសម្ភារៈទូទាំងប្រព័ន្ធភ្លាមៗ។",
          descEn: "Focus any desktop input field (Serial Number in /received-inventory or /receive-item, Barcode in /spareparts). The scanned code is instantly typed into the active input with an audible confirmation chime.",
        },
        {
          number: 4,
          titleKm: "ការចែករំលែកគ្រប់ Tab & ផ្តាច់ការតភ្ជាប់ (Multi-Tab & Security)",
          titleEn: "Multi-Tab Synchronization & Unlinking",
          descKm: "• ប្រព័ន្ធប្រើប្រាស់ **BroadcastChannel (`bis_companion_scanner_bus`)** ដូច្នេះទោះបីជាអ្នកបើកកុំព្យូទ័រច្រើន Tab (ឧទាហរណ៍ Tab មួយបើកទទួលម៉ាស៊ីន Tab មួយទៀតបើកឆែកស្តុក) ក៏ទូរស័ព្ទអាចស្កេនបញ្ជូនទិន្នន័យចូល Tab ដែលកំពុងប្រើប្រាស់បានយ៉ាងរលូន។\n• ពេលឈប់ប្រើ ឬចង់ប្តូរទូរស័ព្ទ គ្រាន់តែចុចប៊ូតុង **'Disconnect Phone'** ក្នុងផ្ទាំងតភ្ជាប់ ឬចុច Logout ចេញពីប្រព័ន្ធ។",
          descEn: "Uses BroadcastChannel to synchronize across multiple open browser tabs simultaneously. Click 'Disconnect Phone' or sign out to invalidate the session securely.",
        },
      ],
      callouts: [
        {
          type: "tip",
          titleKm: "ងាយស្រួល មិនបាច់ដោតខ្សែ និងចំណេញថវិកា",
          titleEn: "Zero Hardware Cost & Cable-Free Mobility",
          contentKm: "អ្នកបច្ចេកទេស និងបុគ្គលិកឃ្លាំងអាចដើរស្កេនម៉ាស៊ីន ឬគ្រឿងបន្លាស់លើធ្នើរឃ្លាំងពីចម្ងាយដោយសេរី ដោយប្រើត្រឹមតែទូរស័ព្ទដៃផ្ទាល់ខ្លួន ហើយទិន្នន័យនឹងរត់ចូលកុំព្យូទ័រលើតុដោយស្វ័យប្រវត្តិ។",
          contentEn: "Warehouse keepers and technicians can roam freely around storage racks, scanning equipment directly into their desktop workstation wirelessly.",
        },
      ],
    },
  ],
};
