/**
 * @file components/docs/content/articlesWorkflowIntake.ts
 * @description The first half of the repair chain - the machine arrives, is diagnosed, quoted, and the customer answers.
 *
 * Ordered as a ticket travels. `articlesWorkflow.ts` spreads this back
 * into the chapter — see its header for why no title states its own
 * stage number.
 */

import type { DocsArticle } from "./articleTypes";

export const WORKFLOW_INTAKE_ARTICLES: DocsArticle[] = [
  {
    id: "workflow-lifecycle",
    titleKm: "Company Services Workflow & តារាង ServiceStatuses ទាំង ១២",
    titleEn: "Company Services 3-Department Workflow & 12 Status Matrix",
    subtitleKm: "លំហូរការងាររវាងផ្នែកបច្ចេកទេស (A) ↔ ផ្នែកស្តុក (B) ↔ ផ្នែកលក់ (C) និងតារាង Status ទាំង ១២ ក្នុង SQL Server",
    subtitleEn: "Cross-departmental service workflow: Technical (A) <-> Stock (B) <-> Sales (C) & SQL Statuses",
    categoryKm: "លំហូរការងារជួសជុល & ដំណាក់កាលទាំង ១១",
    categoryEn: "Repair Workflow",
    icon: "GitFork",
    route: "/receive-item",
    summaryKm: "ដំណើរការសេវាកម្មរបស់ក្រុមហ៊ុន (Company Services) ត្រូវបានរៀបចំឡើងជា ៣ ជួរធំៗ (Swimlanes) រវាងផ្នែកបច្ចេកទេស ផ្នែកស្តុក និងផ្នែកលក់ ភ្ជាប់ជាមួយតារាង SQL Server ServiceStatuses ចំនួន ១២ ស្ថានភាពច្បាស់លាស់។ ម៉ាស៊ីនចូលថ្មីត្រូវចុះបញ្ជីក្នុង Received Inventory ជាមុនសិន មុននឹងបង្កើតសំបុត្រទទួលក្នុង Receive Items។ ក្រោយពេលវិនិច្ឆ័យ ប្រព័ន្ធបែងចែកជា ៤ លំហូរឆ្លាតវៃ (បើមានដោះដូរ ➔ ស្តុក | បើគ្មាន ➔ រំលងទៅទីផ្សារ ឬជួសជុលផ្ទាល់)។",
    summaryEn: "The Company Services operational blueprint coordinates Technical, Stock, and Sales departments across 12 discrete database states with 4-branch smart dispatching.",
    diagram: {
      titleKm: "លំហូរដំណាក់កាលសំបុត្រជួសជុល (Ticket Lifecycle Pipeline)",
      titleEn: "Ticket Lifecycle Pipeline Flowchart",
      descriptionKm: "លំហូរផ្លូវការបង្ហាញពីការផ្លាស់ប្តូរស្ថានភាពពីដំណាក់កាលមួយទៅមួយ",
      descriptionEn: "Official state diagram showing transitions across standard and exception branches.",
      nodes: [
        { id: "s1", labelKm: "១. /received-inventory (ចុះបញ្ជីម៉ូដែល)", labelEn: "1. Register Item Model", badgeKm: "Item Models", badgeEn: "Item Models", color: "indigo", route: "/received-inventory" },
        { id: "s2", labelKm: "២. /receive-item (បង្កើតសំបុត្រ)", labelEn: "2. Receive Item Ticket", badgeKm: "Intake", badgeEn: "Intake", color: "violet", route: "/receive-item" },
        { id: "s3", labelKm: "៣. /inspect-item (វិនិច្ឆ័យ)", labelEn: "3. Inspection Finding", badgeKm: "Diagnostics", badgeEn: "Diagnostics", color: "cyan", route: "/inspect-item" },
        { id: "s4", labelKm: "៤. /waiting-confirm (សម្រង់តម្លៃ)", labelEn: "4. Awaiting Confirm", badgeKm: "Sales Followup", badgeEn: "Sales Followup", color: "amber", route: "/waiting-confirm" },
        { id: "s5", labelKm: "៥. /confirmed-sale (យល់ព្រម)", labelEn: "5. Sale Confirmed", badgeKm: "Approved", badgeEn: "Approved", color: "emerald", route: "/confirmed-sale" },
        { id: "s6", labelKm: "៦. /spare-request (ដកគ្រឿងបន្លាស់)", labelEn: "6. Spare Request", badgeKm: "Warehouse", badgeEn: "Warehouse", color: "indigo", route: "/spare-request" },
        { id: "s7", labelKm: "៧. /pending-repairs (ជួសជុល)", labelEn: "7. Repairing", badgeKm: "Technician", badgeEn: "Technician", color: "violet", route: "/pending-repairs" },
        { id: "s8", labelKm: "៨. /approve-repair (ស្នើសុំ QA)", labelEn: "8. Approve Repair", badgeKm: "Pre-QA", badgeEn: "Pre-QA", color: "sky", route: "/approve-repair" },
        { id: "s9", labelKm: "៩. /approve-verify (QA អនុម័ត)", labelEn: "9. Approve Verify", badgeKm: "Supervisor", badgeEn: "Supervisor", color: "emerald", route: "/approve-verify" },
        { id: "s10", labelKm: "១០. /completed-repairs (ប្រគល់ជូន)", labelEn: "10. Completed", badgeKm: "Finished", badgeEn: "Finished", color: "emerald", route: "/completed-repairs" },
        { id: "ex1", labelKm: "/rejected & /unrepairable", labelEn: "Hot Sales Leads", badgeKm: "Sales Lead", badgeEn: "Sales Lead", color: "rose", route: "/rejected" },
        { id: "ex2", labelKm: "/third-party-repairs", labelEn: "Third-Party Repair", badgeKm: "Outsource", badgeEn: "Outsource", color: "amber", route: "/third-party-repairs" },
      ],
    },
    steps: [
      {
        number: 1,
        titleKm: "ផ្នែកបច្ចេកទេស (Technical Department - A)",
        titleEn: "A. Technical Department Workflow",
        descKm: "ម៉ាស៊ីនចូលថ្មីចុះក្នុង /received-inventory (Node 1) ➔ បង្កើតសំបុត្រទទួល /receive-item (Node 2, Status ID: 1) ➔ កំពុងវិនិច្ឆ័យ (Node 3, Status ID: 10) ➔ វិនិច្ឆ័យរួចរាល់ /inspect-item (Node 4, Status ID: 2) ➔ បញ្ជូនតាមលក្ខខណ្ឌគ្រឿងបន្លាស់។",
        descEn: "New item registered in /received-inventory -> Item Received in /receive-item (Status 1) -> Inspecting (Status 10) -> Inspection Done in /inspect-item (Status 2) -> Conditional dispatching.",
      },
      {
        number: 2,
        titleKm: "ផ្នែកស្តុកគ្រឿងបន្លាស់ (Stock Department - B)",
        titleEn: "B. Stock / Inventory Department Workflow",
        descKm: "ឆែកគ្រឿងបន្លាស់ (Node 5, Status ID: 4) ➔ ស្ថានភាពស្តុក ៤ ជម្រើស (Node 6: 6.1 មានស្តុក, 6.2 ដោះពីម៉ាស៊ីន, 6.3 ស្តុកក្នុងស្រុក, 6.4 រង់ចាំ ៦-៨ សប្តាហ៍) ➔ បញ្ជូនទៅផ្នែកលក់ ➔ ពេលលក់យល់ព្រម ធ្វើការបញ្ជូនគ្រឿងបន្លាស់ទៅជាង (Node 12, Status ID: 12)។",
        descEn: "Check parts (Status 4) -> 4 Sourcing Channels (6.1 In stock, 6.2 Harvest, 6.3 Local market, 6.4 Order 6-8 weeks) -> Sent Spareparts (Status 12).",
      },
      {
        number: 3,
        titleKm: "ផ្នែកលក់ & អតិថិជន (Sales Department - C)",
        titleEn: "C. Sales & Customer Confirmation Workflow",
        descKm: "ដាក់សម្រង់តម្លៃ Quote អោយអតិថិជន (Node 7, Status ID: 3) ➔ រង់ចាំការយល់ព្រម (Node 8) ➔ អតិថិជនយល់ព្រម / អាចជួសជុលបាន (Node 9, Status ID: 11) ឬ មិនជួសជុល / បដិសេធ (Node 9.1, Status ID: 7 & 8)។",
        descEn: "Issue quote to customer (Status 3) -> Awaiting confirm -> Customer approves (Status 11) vs Customer rejects (Status 7/8).",
      },
      {
        number: 4,
        titleKm: "ការជួសជុល និងប្រគល់ជូន (Execution & Handover)",
        titleEn: "Execution & Handover",
        descKm: "ជាងទទួលគ្រឿងបន្លាស់ ធ្វើការជួសជុលជាក់ស្តែងក្នុង /pending-repairs (Status ID: 5) ➔ Supervisor ធ្វើតេស្តគុណភាពក្នុង /approve-verify ➔ ជួសជុលរួចរាល់ Finished (Status ID: 6) ក្នុង /completed-repairs។",
        descEn: "Technicians execute repair in /pending-repairs (Status 5) -> Supervisor audits in /approve-verify -> Handover in /completed-repairs (Status 6).",
      },
    ],
  },
  {
    id: "received-inventory",
    titleKm: "ដំណាក់កាលត្រៀម៖ បញ្ជីម៉ូដែលម៉ាស៊ីន & Serial Number Inventory",
    titleEn: "Preparation Stage: Item Models & Serial Number Inventory",
    subtitleKm: "កត់ត្រាម៉ូដែលម៉ាស៊ីនថ្មី (Item Name, Serial Number, Item Type) ដែលមិនទាន់មានក្នុងប្រព័ន្ធ មុនពេលបង្កើតសំបុត្រទទួល",
    subtitleEn: "Master catalog of equipment models and serial numbers registered before ticket creation",
    categoryKm: "លំហូរការងារជួសជុល & ដំណាក់កាលទាំង ១១",
    categoryEn: "Repair Workflow",
    icon: "Boxes",
    route: "/received-inventory",
    roles: ["Front Desk", "Stock Keeper", "Supervisor", "Admin"],
    summaryKm: "ទំព័រ `/received-inventory` គឺកើតឡើងមុនគេបំផុត សម្រាប់គ្រប់គ្រងបញ្ជីម៉ូដែលម៉ាស៊ីន (Item Models Inventory)។ ប្រសិនបើអតិថិជនយកម៉ាស៊ីនដែលជាម៉ូដែលថ្មី ឬមិនទាន់មានក្នុងប្រព័ន្ធ ត្រូវបញ្ចូលឈ្មោះម៉ាស៊ីន (Item Name), លេខ Serial Number, និងប្រភេទសម្ភារៈ (Item Type: Printer, Scanner, UPS...) ក្នុងទំព័រនេះជាមុនសិន ទើបអាចជ្រើសរើសទៅបង្កើតសំបុត្រក្នុង `/receive-item` បាន។",
    summaryEn: "Pre-intake inventory where new machine models and serial numbers are registered before creating official repair tickets in Receive Items.",
    diagram: {
      titleKm: "លំហូរចុះបញ្ជីម៉ូដែលម៉ាស៊ីនចូលថ្មី (New Item Registration Flow)",
      titleEn: "New Item Model Registration Pipeline",
      descriptionKm: "ដំណើរការចុះឈ្មោះម៉ូដែល និងលេខ Serial ថ្មី រួចបញ្ជូនបន្តទៅកាន់ទំព័រទទួលម៉ាស៊ីន /receive-item",
      descriptionEn: "New hardware model registration pipeline feeding into the ticket intake module.",
      nodes: [
        { id: "ri_q1", labelKm: "១. ម៉ាស៊ីនចូលថ្មី (ម៉ូដែលមិនទាន់មានក្នុងប្រព័ន្ធ)", labelEn: "1. New Incoming Hardware", badgeKm: "New Inbound", badgeEn: "New Inbound", color: "violet" },
        { id: "ri_q2", labelKm: "២. បើក /received-inventory ចុច Add Item", labelEn: "2. Open /received-inventory", badgeKm: "Item Models", badgeEn: "Item Models", color: "cyan", route: "/received-inventory" },
        { id: "ri_q3", labelKm: "៣. បញ្ចូល Item Name, Serial No, Item Type", labelEn: "3. Input Specs & Serial", badgeKm: "Catalog Entry", badgeEn: "Catalog Entry", color: "indigo" },
        { id: "ri_q4", labelKm: "៤. រក្សាទុកក្នុង Inventory Database", labelEn: "4. Save to Inventory DB", badgeKm: "Saved", badgeEn: "Saved", color: "amber" },
        { id: "ri_q5", labelKm: "៥. ផ្លាស់ទីទៅ /receive-item ដើម្បីបង្កើតសំបុត្រ", labelEn: "5. Route to /receive-item", badgeKm: "Intake Ticket", badgeEn: "Intake Ticket", color: "emerald", route: "/receive-item" },
      ],
    },
    steps: [
      {
        number: 1,
        titleKm: "ពិនិត្យមើលថាតើម៉ាស៊ីនមានក្នុងបញ្ជីហើយឬនៅ",
        titleEn: "Search Existing Item Model",
        descKm: "ចូលទៅ `/received-inventory` វាយឈ្មោះម៉ាស៊ីន ឬលេខ Serial No ដើម្បីពិនិត្យមើល។ ប្រសិនបើមានរួចហើយ អាចទៅបង្កើតសំបុត្រក្នុង `/receive-item` បានភ្លាម។",
        descEn: "Search by model name or serial number. If already cataloged, proceed directly to /receive-item.",
      },
      {
        number: 2,
        titleKm: "ចុះឈ្មោះម៉ូដែល ឬ Serial Number ថ្មី (គាំទ្រ Mobile Barcode Scanner)",
        titleEn: "Add New Equipment Model (Mobile Scanner Support)",
        descKm: "ប្រសិនបើជាម៉ាស៊ីនថ្មី ចុចប៊ូតុង '+ Add Item Model' បញ្ចូលឈ្មោះ Item Name (ឧ. Canon imageRUNNER 2520), លេខ Serial Number (អាចប្រើទូរស័ព្ទដៃស្កេន Barcode តាម Phone Link ចូលប្រអប់នេះផ្ទាល់) និងជ្រើសរើសប្រភេទ (Printer / Scanner / UPS / Computer) រួចចុច Save។",
        descEn: "Click + Add Item Model, enter Item Name, Serial Number (use Phone Link mobile barcode scanner to auto-fill), and select Item Type, then click Save.",
      },
    ],
  },
  {
    id: "receive-item",
    titleKm: "ទទួលម៉ាស៊ីនចូល & ចេញប័ណ្ណបង្កាន់ដៃ",
    titleEn: "Receive Item & Intake Ticket Creation",
    subtitleKm: "ជ្រើសរើសម៉ាស៊ីនពី Inventory ភ្ជាប់ជាមួយ Profile អតិថិជន កត់ត្រារោគសញ្ញា ចេញប័ណ្ណទទួល និងបញ្ជូនទៅ Inspecting",
    subtitleEn: "Customer intake, selecting item model, logging defect symptoms, receipt printing, and dispatching to Inspecting",
    categoryKm: "លំហូរការងារជួសជុល & ដំណាក់កាលទាំង ១១",
    categoryEn: "Repair Workflow",
    icon: "Inbox",
    route: "/receive-item",

    status: "Item Recieved",
    roles: ["Front Desk", "Technician", "Admin"],
    summaryKm: "ទំព័រ `/receive-item` ជាកន្លែងបង្កើតសំបុត្រជួសជុលផ្លូវការ (Status ID: 1 Item Recieved)។ បុគ្គលិកទទួលម៉ាស៊ីនជ្រើសរើសម៉ាស៊ីនពី Inventory, ភ្ជាប់ជាមួយក្រុមហ៊ុនអតិថិជន, កត់ត្រារោគសញ្ញាខូច និងបោះពុម្ពប័ណ្ណបង្កាន់ដៃទទួល (Receipt Slip) ជូនអតិថិជន។ បន្ទាប់ពីទទួលរួច សំបុត្រប្តូរទៅជា Status ID: 10 (Inspecting) ហើយបញ្ជូនបន្តទៅកាន់ `/inspect-item` ដើម្បីឱ្យជាងបច្ចេកទេសធ្វើតេស្តវិភាគ។",
    summaryEn: "Official ticket creation portal (Status 1: Item Recieved). Links customer accounts, logs symptoms, prints intake slips, and routes tickets to Inspecting (Status 10) /inspect-item.",
    diagram: {
      titleKm: "លំហូរការងារទទួលម៉ាស៊ីន (Receive Intake Flow)",
      titleEn: "Item Intake & Ticket Creation Flow",
      descriptionKm: "ដំណើរការទទួលម៉ាស៊ីនពីអតិថិជន បោះពុម្ពប័ណ្ណបង្កាន់ដៃ និងបញ្ជូនបន្តទៅកាន់ការវិនិច្ឆ័យ (Inspecting)",
      descriptionEn: "Step-by-step intake workflow from customer arrival to diagnostic inspection dispatch.",
      nodes: [
        { id: "ri1", labelKm: "១. អតិថិជនយកម៉ាស៊ីនមកដល់", labelEn: "1. Customer Arrives", badgeKm: "Front Desk", badgeEn: "Front Desk", color: "violet" },
        { id: "ri2", labelKm: "២. ជ្រើសរើស/បង្កើត Profile អតិថិជន", labelEn: "2. Customer Account", badgeKm: "Company", badgeEn: "Company", color: "cyan" },
        { id: "ri3", labelKm: "៣. ជ្រើសរើសម៉ាស៊ីនពី Inventory & ស្កេន Serial", labelEn: "3. Pick Item from Inventory", badgeKm: "Item Models", badgeEn: "Item Models", color: "indigo", route: "/received-inventory" },
        { id: "ri4", labelKm: "៤. កត់ត្រារោគសញ្ញា & ប្រភេទសេវា (Free/Charge)", labelEn: "4. Symptoms / Type", badgeKm: "Free/Charge", badgeEn: "Free/Charge", color: "amber" },
        { id: "ri5", labelKm: "៥. បោះពុម្ពប័ណ្ណទទួល (Receipt Slip) [Status: 1]", labelEn: "5. Print Receipt Slip", badgeKm: "Status: 1", badgeEn: "Status: 1", color: "emerald", route: "/receive-item" },
        { id: "ri6", labelKm: "៦. ផ្លាស់ទៅ Inspecting [Status: 10] ➔ /inspect-item", labelEn: "6. Route to /inspect-item", badgeKm: "Inspecting", badgeEn: "Inspecting", color: "cyan", route: "/inspect-item" },
      ],
    },
    steps: [
      {
        number: 1,
        titleKm: "ជ្រើសរើស ឬបញ្ចូលឈ្មោះក្រុមហ៊ុន/អតិថិជន",
        titleEn: "Select or Create Customer",
        descKm: "វាយបញ្ចូលឈ្មោះក្រុមហ៊ុន ឬជ្រើសរើសពីបញ្ជីដែលមានស្រាប់។ ប្រព័ន្ធនឹងទាញយកលេខទូរស័ព្ទ និងអាសយដ្ឋានដោយស្វ័យប្រវត្តិ។",
        descEn: "Type company name to select from existing accounts or create a new profile.",
      },
      {
        number: 2,
        titleKm: "ជ្រើសរើសម៉ាស៊ីន និងស្កេនលេខ Serial Number (Mobile Scanner)",
        titleEn: "Select Machine & Scan Serial via Mobile Scanner",
        descKm: "ជ្រើសរើសម៉ូដែលម៉ាស៊ីនដែលបានចុះក្នុង Inventory រួចហើយ និងស្កេនលេខ Serial Number តាមរយៈ **Mobile Barcode Scanner (Phone Link)** ដោយប្រើកាមេរ៉ាទូរស័ព្ទ ឬកម្មវិធី CAM ID App ដើម្បីបំពេញទិន្នន័យស្វ័យប្រវត្តិ។",
        descEn: "Pick registered machine model from inventory dropdown and scan serial number wirelessly using Phone Link or the CAM ID mobile app.",
      },
      {
        number: 3,
        titleKm: "កត់ត្រារោគសញ្ញាខូច & បោះពុម្ពប័ណ្ណទទួល (Receipt Slip)",
        titleEn: "Log Symptoms & Print Receipt",
        descKm: "សរសេរបរិយាយរោគសញ្ញាខូច រួចចុច Save។ ប្រព័ន្ធនឹងចេញលេខសំបុត្រ និងបោះពុម្ពប័ណ្ណបង្កាន់ដៃទទួល (Receipt Slip) ជូនអតិថិជន ព្រមទាំងប្តូរស្ថានភាពទៅជា Status ID 10 (Inspecting) ត្រៀមបញ្ជូនទៅ /inspect-item។",
        descEn: "Record customer symptom description, save ticket, print receipt slip, and advance ticket state to Inspecting (Status 10).",
      },
    ],
    callouts: [
      {
        type: "tip",
        titleKm: "ការស្កេន Barcode / QR Code តាមទូរស័ព្ទដៃ (Phone Link)",
        titleEn: "Wireless Mobile Barcode Scanner Support",
        contentKm: "អ្នកអាចចុចប៊ូតុង '📱 តភ្ជាប់ទូរស័ព្ទ' នៅលើ Header ខាងលើ រួចប្រើទូរស័ព្ទដៃស្កេន QR Code ដើម្បីបម្លែងទូរស័ព្ទទៅជា Barcode Scanner ឥតខ្សែ។ រាល់ពេលស្កេនលេខ Serial Number លើតួម៉ាស៊ីន វានឹងរត់ចូលមកបំពេញក្នុងប្រអប់ Serial Number លើកុំព្យូទ័រដោយស្វ័យប្រវត្តិ!",
        contentEn: "Click 'Connect Phone' on the header, scan the QR code to activate the wireless mobile scanner. Scanned serial numbers will instantly auto-fill into the desktop intake form.",
      },
    ],
  },
  {
    id: "inspect-item",
    titleKm: "ត្រួតពិនិត្យ & វិភាគបញ្ហាជាក់ស្តែង",
    titleEn: "Technical Diagnostic & Parts Selection",
    subtitleKm: "ជាងបច្ចេកទេសទទួលសំបុត្រពី /receive-item (Status: 10) ធ្វើតេស្តវិភាគរកមូលហេតុពិត និងជ្រើសរើសគ្រឿងបន្លាស់",
    subtitleEn: "Technical inspection, root-cause diagnosis, and spare parts requirement specification",
    categoryKm: "លំហូរការងារជួសជុល & ដំណាក់កាលទាំង ១១",
    categoryEn: "Repair Workflow",
    icon: "Search",
    route: "/inspect-item",

    status: "Inspecting",
    roles: ["Technician", "Supervisor", "Admin"],
    summaryKm: "ទំព័រ `/inspect-item` ទទួលសំបុត្រដែលទើបតែទទួលបានពី `/receive-item` (Status ID: 10 Inspecting)។ ជាងបច្ចេកទេសធ្វើតេស្តម៉ាស៊ីន កត់ត្រាលទ្ធផលពិនិត្យជាក់ស្តែង (Status ID: 2 Inspection) និងជ្រើសរើសគ្រឿងបន្លាស់ដែលត្រូវប្តូរចេញពីស្តុក រួចបញ្ជូនតាម ៤ លំហូរឆ្លាតវៃ (បើមានដោះដូរ ➔ បញ្ជូនទៅស្តុក | បើគ្មាន ➔ រំលងទៅទីផ្សារ ឬជួសជុល)។",
    summaryEn: "Technicians receive tickets from /receive-item (Status 10), conduct physical testing, record inspection findings (Status 2), and select required spare parts.",
    diagram: {
      titleKm: "លំហូរការងារត្រួតពិនិត្យ & វិភាគបញ្ហា (Inspection Flow)",
      titleEn: "Diagnostic Inspection Workflow",
      descriptionKm: "ដំណើរការធ្វើតេស្តវិភាគរកមូលហេតុពិត និងការកំណត់គ្រឿងបន្លាស់ដែលត្រូវប្តូរ",
      descriptionEn: "Diagnostic testing procedure from intake queue to parts requisition.",
      nodes: [
        { id: "ii1", labelKm: "១. ទទួលសំបុត្រពី Received Item ដែលបញ្ជូនមកវិនិច្ឆ័យ Inspecting", labelEn: "1. Intake Ticket from Received Item dispatched to Inspecting", badgeKm: "Inspecting", badgeEn: "Inspecting", color: "violet", route: "/receive-item" },
        { id: "ii2", labelKm: "២. ធ្វើតេស្ត Hardware & វិភាគរោគសញ្ញា", labelEn: "2. Hardware Test", badgeKm: "Diagnostics", badgeEn: "Diagnostics", color: "cyan" },
        { id: "ii3", labelKm: "៣. កត់ត្រាមូលហេតុពិត [Status: 2 Inspection]", labelEn: "3. Root Cause Finding", badgeKm: "Status: 2", badgeEn: "Status: 2", color: "indigo" },
        { id: "ii4", labelKm: "៤. ជ្រើសរើសគ្រឿងបន្លាស់ត្រូវប្តូរពីស្តុក", labelEn: "4. Select Spare Parts", badgeKm: "Parts SKU", badgeEn: "Parts SKU", color: "amber", route: "/spareparts" },
        { id: "ii5", labelKm: "៥. បញ្ជូនទៅផ្នែកស្តុក & ផ្នែកលក់ធ្វើ Quote", labelEn: "5. Forward to Stock & Quote", badgeKm: "Quotation", badgeEn: "Quotation", color: "emerald", route: "/waiting-confirm" },
      ],
    },
    steps: [
      {
        number: 1,
        titleKm: "កត់ត្រាលទ្ធផលពិនិត្យ (Inspection Finding)",
        titleEn: "Enter Inspection Findings",
        descKm: "សរសេរបរិយាយលម្អិតអំពីអ្វីដែលបានរកឃើញជាក់ស្តែង (ឧ. 'Board Power ខូច Capacitor C12')។ ស្ថានភាពនឹងប្តូរទៅជា `Inspection` (Status ID: 2)។",
        descEn: "Document the technical diagnostic conclusion clearly in the Inspection field (Status ID: 2).",
      },
      {
        number: 2,
        titleKm: "ជ្រើសរើសគ្រឿងបន្លាស់ និងកំណត់ Condition (Fix / Replace / Free)",
        titleEn: "Specify Parts & Condition (Fix / Replace / Free)",
        descKm: "ជ្រើសរើសគ្រឿងបន្លាស់ពីបញ្ជីស្តុក និងកំណត់លក្ខខណ្ឌ៖ 'Fix' (ជួសជុលមិនកាត់ស្តុក) ឬ 'Replace / Free' (ដោះដូរប្តូរគ្រឿងថ្មីដែលត្រូវកាត់ស្តុក)។",
        descEn: "Select parts from catalog and set condition: Fix (no stock deduct) vs Replace/Free (stock deduct).",
      },
      {
        number: 3,
        titleKm: "លំហូរបញ្ជូនសំបុត្រឆ្លាតវៃតាម ៤ ករណី (Smart Dispatch Logic)",
        titleEn: "4-Branch Smart Dispatch Routing",
        descKm: "• ករណី ១ (Charge មាន Sparepart)៖ ➔ បញ្ជូនទៅស្តុក ➔ ទីផ្សារ Quote ➔ Sale Confirmed ➔ បញ្ជូនគ្រឿងបន្លាស់ (Status: 12) ➔ អនុម័តជួសជុល\n• ករណី ២ (Charge គ្មាន Sparepart/Fix ទាំងអស់)៖ ➔ ទីផ្សារ Quote ➔ Sale Confirmed ➔ អនុម័តជួសជុល (រំលងស្តុក)\n• ករណី ៣ (Free មាន Sparepart)៖ ➔ បញ្ជូនទៅស្តុក ➔ បញ្ជូនគ្រឿងបន្លាស់ (Status: 12) ➔ អនុម័តជួសជុល (រំលងទីផ្សារ)\n• ករណី ៤ (Free គ្មាន Sparepart)៖ ➔ វិនិច្ឆ័យរួច ➔ អនុម័តជួសជុល Direct Fast-Track (រំលងទាំងស្តុក និងទីផ្សារ)",
        descEn: "Intelligent routing across 4 distinct operational branches based on Charge/Free status and Sparepart requirements.",
      },
    ],
    callouts: [
      {
        type: "tip",
        titleKm: "ច្បាប់កាត់ស្តុកតាម Sparepart Condition",
        titleEn: "Sparepart Condition Inventory Deduction Rules",
        contentKm: "• Fix = ជួសជុលមិនកាត់ស្តុក (បើជ្រើស Fix ទាំងអស់ គឺមិនបញ្ជូនទៅស្តុកទេ ➔ បញ្ជូនទៅទីផ្សារ/ជួសជុល Direct)\n• Replace & Free = កាត់ស្តុក (បើមាន Replace ឬ Free យ៉ាងហោចមួយ ត្រូវតែបញ្ជូនទៅផ្នែកស្តុកជាមុនសិន)។",
        contentEn: "Fix condition never deducts inventory. Replace and Free conditions always require warehouse stock reservation and audited deduction.",
      },
    ],
  },
  {
    id: "inspection",
    titleKm: "កំណត់ត្រាការវិនិច្ឆ័យ (Inspection Records)",
    titleEn: "Inspection Records & Stage Tabs",
    subtitleKm: "បញ្ជីការងារដែលបានវិនិច្ឆ័យរួច ព្រមទាំងផ្ទាំងតាមដានដំណាក់កាលបន្ទាប់នៅកន្លែងតែមួយ",
    subtitleEn: "Every diagnosed job in one list, with tabs that follow it through the stages that come next",
    categoryKm: "លំហូរការងារជួសជុល & ដំណាក់កាលទាំង ១១",
    categoryEn: "Repair Workflow",
    icon: "Layers",
    route: "/inspection",
    status: "Inspection",
    roles: ["Technician", "Supervisor", "Admin"],
    summaryKm: "ពេលជាងរក្សាទុកលទ្ធផលវិនិច្ឆ័យរួច សំបុត្រនឹងចុះមកទំព័រ `/inspection`។ ទំព័រនេះមិនត្រឹមតែបង្ហាញអ្វីដែលបានវិនិច្ឆ័យរួចទេ — ផ្ទាំងខាងលើរបស់វាក៏អនុញ្ញាតឱ្យអ្នកតាមដានការងារតែមួយឆ្លងកាត់ដំណាក់កាលបន្ទាប់ៗ ដោយមិនចាំបាច់ចេញពីទំព័រនេះឡើយ។",
    summaryEn: "Once a technician saves their findings the ticket lands here. Beyond listing what has been diagnosed, the tabs across the top follow a single job through the stages that come after it — so you can answer \"where is this job now?\" without leaving the page.",
    steps: [
      {
        number: 1,
        titleKm: "បើកបញ្ជីការងារដែលបានវិនិច្ឆ័យ",
        titleEn: "Open the Diagnosed Queue",
        descKm: "ចូលទៅ `/inspection` ដើម្បីមើលរាល់សំបុត្រដែលមានលទ្ធផលវិនិច្ឆ័យរក្សាទុករួច។",
        descEn: "Navigate to Inspection to see every ticket whose diagnosis has been saved.",
      },
      {
        number: 2,
        titleKm: "ប្រើផ្ទាំងតាមដានដំណាក់កាល",
        titleEn: "Follow a Job Through the Tabs",
        descKm: "ផ្ទាំងខាងលើ — Inspection, Awaiting Sparepart, Awaiting Customer Confirm, Sale Confirmed, Sent Spareparts — អនុញ្ញាតឱ្យអ្នកតាមដានការងារបន្តទៅមុខ ដោយមិនចាំបាច់ប្តូរទំព័រ។",
        descEn: "Use the tabs — Inspection, Awaiting Sparepart, Awaiting Customer Confirm, Sale Confirmed, Sent Spareparts — to follow a job past this point without switching pages.",
      },
      {
        number: 3,
        titleKm: "បើកជួរដើម្បីអានកំណត់ត្រាពេញលេញ",
        titleEn: "Open a Row for the Full Record",
        descKm: "បើកជួរណាមួយដើម្បីអានការវិនិច្ឆ័យពេញលេញ គ្រឿងបន្លាស់ដែលបានស្នើ និងកំណត់ត្រាថានរណាធ្វើអ្វី នៅពេលណា។",
        descEn: "Open any row to read the full diagnosis, the quoted parts, and the audit trail of who did what and when.",
      },
    ],
    callouts: [
      {
        type: "info",
        titleKm: "ការរក្សាទុកឡើងវិញ មិនបង្កើតជួរស្ទួនទេ",
        titleEn: "Re-saving Reconciles, It Does Not Duplicate",
        contentKm: "ការរក្សាទុកការវិនិច្ឆ័យម្តងទៀតនឹងផ្ទៀងផ្ទាត់បញ្ជីគ្រឿងបន្លាស់ជាមួយអ្វីដែលរក្សាទុករួច ដូច្នេះការលុបជួរមួយចេញ គឺលុបពិត មិនមែនបន្ថែមស្ទួនទេ។",
        contentEn: "Re-saving an inspection reconciles the parts list against what was stored, so removing a line here really removes it rather than adding a duplicate.",
      },
    ],
  },
  {
    id: "spare-request",
    titleKm: "ស្នើសុំ & ដកគ្រឿងបន្លាស់ពីស្តុក",
    titleEn: "Spare Part Allocation & Stock-Out",
    subtitleKm: "ការគ្រប់គ្រងការកក់ទុក (Hold) និងការដកគ្រឿងបន្លាស់ពិតប្រាកដចេញពីឃ្លាំង",
    subtitleEn: "Reserving held stock and executing audited warehouse stock-outs for repair jobs",
    categoryKm: "លំហូរការងារជួសជុល & ដំណាក់កាលទាំង ១១",
    categoryEn: "Repair Workflow",
    icon: "PackageCheck",
    route: "/spare-request",

    status: "Awaiting Sparepart",
    roles: ["Stock Keeper", "Technician", "Admin"],
    summaryKm: "ទំព័រ `/spare-request` អនុញ្ញាតឱ្យផ្នែកឃ្លាំងពិនិត្យមើលគ្រឿងបន្លាស់ដែលជាងបានស្នើសុំ និងធ្វើការប្រគល់គ្រឿងបន្លាស់ជាក់ស្តែងទៅឱ្យជាង (Status ID: 12 Sent Spareparts)។",
    summaryEn: "Warehouse personnel review requested spare parts, verify shelf availability, and issue the components directly into the technician's custody.",
    diagram: {
      titleKm: "លំហូរការងារដកគ្រឿងបន្លាស់ពីឃ្លាំង (Parts Allocation Flow)",
      titleEn: "Warehouse Parts Allocation Workflow",
      descriptionKm: "ដំណើរការផ្ទៀងផ្ទាត់ស្តុកជាក់ស្តែង ការកក់ទុក និងការកាត់ចេញពីសៀវភៅស្តុក",
      descriptionEn: "Parts verification, reservation, and audited physical stock-out procedure.",
      nodes: [
        { id: "sr1", labelKm: "១. ទទួលសំណើគ្រឿងបន្លាស់ពីការវិនិច្ឆ័យ", labelEn: "1. Diagnostic Parts Request", badgeKm: "Inspection", badgeEn: "Inspection", color: "violet", route: "/inspect-item" },
        { id: "sr2", labelKm: "២. ពិនិត្យចំនួនស្តុកលើធ្នើរឃ្លាំង (Status: 4)", labelEn: "2. Check Shelf Stock", badgeKm: "Live Stock", badgeEn: "Live Stock", color: "cyan", route: "/spareparts" },
        { id: "sr3", labelKm: "៣. កក់ទុកគ្រឿងបន្លាស់ (Stock on Hold)", labelEn: "3. Quarantine / Hold", badgeKm: "Hold Qty", badgeEn: "Hold Qty", color: "amber", route: "/sparepart-hold" },
        { id: "sr4", labelKm: "៤. ផ្ញើតម្លៃ & ETA ទៅផ្នែកលក់ធ្វើ Quote", labelEn: "4. Send Cost & ETA to Sales", badgeKm: "Quotation", badgeEn: "Quotation", color: "indigo", route: "/waiting-confirm" },
        { id: "sr5", labelKm: "៥. ប្រគល់គ្រឿងបន្លាស់ជូនជាង (Status: 12)", labelEn: "5. Issue Parts to Tech", badgeKm: "Custody", badgeEn: "Custody", color: "emerald", route: "/spare-request" },
      ],
    },
    steps: [
      {
        number: 1,
        titleKm: "ផ្ទៀងផ្ទាត់ចំនួនស្តុក & ប្រគល់គ្រឿងបន្លាស់",
        titleEn: "Issue Parts from Warehouse",
        descKm: "ពិនិត្យគ្រឿងបន្លាស់ក្នុងឃ្លាំង រួចចុច 'Issue Parts'។ ប្រព័ន្ធនឹងកត់ត្រាក្នុង `SparepartStockAuditLog` ភ្លាមៗ។",
        descEn: "Verify physical stock and confirm issue. The system logs an audited Out transaction automatically.",
      },
    ],
  },
  {
    id: "waiting-confirm",
    titleKm: "សម្រង់តម្លៃ & រង់ចាំការយល់ព្រមពីភ្ញៀវ",
    titleEn: "Quotation & Customer Confirmation",
    subtitleKm: "សម្រាប់សេវាគិតថ្លៃ (Charge)៖ តាមដានការសម្រង់តម្លៃ និងរង់ចាំការឆ្លើយតបពីអតិថិជន",
    subtitleEn: "Sales pipeline tracking for customer quotation approvals and aging days",
    categoryKm: "លំហូរការងារជួសជុល & ដំណាក់កាលទាំង ១១",
    categoryEn: "Repair Workflow",
    icon: "Clock",
    route: "/waiting-confirm",

    status: "Awaiting Customer Confirm",
    roles: ["Sales", "Supervisor", "Admin"],
    summaryKm: "ទំព័រ `/waiting-confirm` បង្ហាញសម្រង់តម្លៃទាំងអស់ដែលបានផ្ញើជូនអតិថិជនរួច និងកំពុងរង់ចាំការយល់ព្រម (Status ID: 3)។ ប្រព័ន្ធបង្ហាញចំនួនថ្ងៃរង់ចាំ (Aging Days) ដើម្បីឱ្យផ្នែកលក់ទូរស័ព្ទទៅ Follow-up បានទាន់ពេល។",
    summaryEn: "Tracks all pending quotations awaiting customer confirmation. Highlights aging days so sales reps can follow up promptly.",
    diagram: {
      titleKm: "លំហូរការងារសម្រង់តម្លៃ & ការសម្រេចចិត្ត (Quotation Approval Flow)",
      titleEn: "Quotation Pipeline & Customer Decision Flow",
      descriptionKm: "ការតាមដានសម្រង់តម្លៃ និងការបែងចែកទៅកាន់ Confirmed Sale ឬ Rejected Sales Lead",
      descriptionEn: "Pipeline tracking pending quotes, follow-up aging, and customer decisions.",
      nodes: [
        { id: "wc1", labelKm: "១. បញ្ជូនសម្រង់តម្លៃ (Quote Sent)", labelEn: "1. Quotation Issued", badgeKm: "Sales", badgeEn: "Sales", color: "violet", route: "/waiting-confirm" },
        { id: "wc2", labelKm: "២. តាមដានចំនួនថ្ងៃរង់ចាំ (Aging Days)", labelEn: "2. Monitor Aging Days", badgeKm: "Follow-up", badgeEn: "Follow-up", color: "cyan" },
        { id: "wc3", labelKm: "៣. អតិថិជនយល់ព្រម (Confirm Sale)", labelEn: "3. Customer Approved", badgeKm: "Advance", badgeEn: "Advance", color: "emerald", route: "/confirmed-sale" },
        { id: "wc4", labelKm: "៤. អតិថិជនបដិសេធ (Rejected)", labelEn: "4. Customer Rejected", badgeKm: "Lead", badgeEn: "Lead", color: "rose", route: "/rejected" },
        { id: "wc5", labelKm: "៥. បម្លែងជាឱកាសលក់ម៉ាស៊ីនថ្មី", labelEn: "5. New Machine Sales Lead", badgeKm: "Hot Lead", badgeEn: "Hot Lead", color: "amber", route: "/sales-leads-report" },
      ],
    },
    steps: [
      {
        number: 1,
        titleKm: "ករណីអតិថិជនយល់ព្រម (Approve)",
        titleEn: "Customer Approves Quotation",
        descKm: "ចុចប៊ូតុង 'Confirm Sale' ដើម្បីប្តូរស្ថានភាពទៅ `Sale Confirmed` ត្រៀមកាត់ស្តុក និងជួសជុល។",
        descEn: "Click Confirm Sale to advance the ticket to Sale Confirmed for warehouse part allocation.",
      },
      {
        number: 2,
        titleKm: "ករណីអតិថិជនបដិសេធ (Reject)",
        titleEn: "Customer Rejects Quotation",
        descKm: "ចុចប៊ូតុង 'Reject' និងកត់ត្រាមូលហេតុដែលអតិថិជនមិនព្រមជួសជុល។ សំបុត្រនេះនឹងក្លាយជា Sales Lead សម្រាប់លក់ម៉ាស៊ីនថ្មី។",
        descEn: "Click Reject and record the reason. The ticket automatically routes to the New Machine Sales Leads report.",
      },
    ],
  },
  {
    id: "confirmed-sale",
    titleKm: "បញ្ជាក់ការលក់ & ត្រៀមកាត់ស្តុក",
    titleEn: "Confirmed Repair Orders & Billing Ready",
    subtitleKm: "សំបុត្រដែលអតិថិជនបានឯកភាពលើតម្លៃរួចរាល់ ត្រៀមបញ្ជូនទៅដកគ្រឿងបន្លាស់ និងចេញវិក្កយបត្រ",
    subtitleEn: "Approved repair work orders ready for warehouse parts issuance and billing",
    categoryKm: "លំហូរការងារជួសជុល & ដំណាក់កាលទាំង ១១",
    categoryEn: "Repair Workflow",
    icon: "CheckSquare",
    route: "/confirmed-sale",

    status: "Sale Confirmed → Sent Spareparts",
    roles: ["Sales", "Accounting", "Stock Keeper", "Admin"],
    summaryKm: "ទំព័រ `/confirmed-sale` បង្ហាញសំបុត្រទាំងអស់ដែលមានស្ថានភាព `Sale Confirmed` (Status ID: 11) ដែលអតិថិជនបានយល់ព្រមលើសម្រង់តម្លៃរួចរាល់ ត្រៀមបញ្ជូនទៅកាន់ផ្នែកស្តុកដើម្បីដកគ្រឿងបន្លាស់។",
    summaryEn: "Repository of confirmed repair sales ready for warehouse allocation and finance invoicing.",
    diagram: {
      titleKm: "លំហូរការងារបញ្ជាក់ការលក់ (Confirmed Sales Flow)",
      titleEn: "Confirmed Sales Order Pipeline",
      descriptionKm: "ដំណើរការបញ្ជាក់ការលក់ និងការបញ្ជូនសំបុត្រទៅកាន់ផ្នែកស្តុកដើម្បីកាត់គ្រឿងបន្លាស់",
      descriptionEn: "Order confirmation to warehouse fulfillment dispatch pipeline.",
      nodes: [
        { id: "cs1", labelKm: "១. ទទួលការយល់ព្រមពីអតិថិជន", labelEn: "1. Customer Approval", badgeKm: "Status: 11", badgeEn: "Status: 11", color: "violet", route: "/confirmed-sale" },
        { id: "cs2", labelKm: "២. បង្កើត Order សំបុត្រជួសជុលផ្លូវការ", labelEn: "2. Lock Quote Amount", badgeKm: "Accounting", badgeEn: "Accounting", color: "cyan" },
        { id: "cs3", labelKm: "៣. បញ្ជូនសំណើគ្រឿងបន្លាស់ទៅឃ្លាំង", labelEn: "3. Request Parts from Stock", badgeKm: "Dispatch", badgeEn: "Dispatch", color: "indigo", route: "/spare-request" },
        { id: "cs4", labelKm: "៤. កត់ត្រាក្នុងបញ្ជី Confirmed Sales", labelEn: "4. Ledger Confirmed Order", badgeKm: "Revenue", badgeEn: "Revenue", color: "emerald" },
      ],
    },
    steps: [
      {
        number: 1,
        titleKm: "ពិនិត្យសំបុត្រដែលបានអនុម័ត",
        titleEn: "Inspect Approved Orders",
        descKm: "ផ្ទៀងផ្ទាត់ចំនួនទឹកប្រាក់ដែលបានព្រមព្រៀង និងបញ្ជីគ្រឿងបន្លាស់ដែលត្រូវដកចេញពីឃ្លាំង។",
        descEn: "Verify approved amount and requested replacement part list.",
      },
      {
        number: 2,
        titleKm: "បញ្ជូនទៅផ្នែកស្តុក (/spare-request)",
        titleEn: "Forward to Warehouse",
        descKm: "ចុចបញ្ជូនសំណើដើម្បីឱ្យផ្នែកឃ្លាំងរៀបចំគ្រឿងបន្លាស់ និងប្រគល់ជូនជាងបច្ចេកទេស។",
        descEn: "Dispatch parts requisition to the warehouse fulfillment desk.",
      },
    ],
  },
];
