// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechnicalService.Infrastructure;

#nullable disable

namespace TechnicalService.Infrastructure.Migrations
{
    [DbContext(typeof(TechnicalServiceContext))]
    partial class TechnicalServiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechnicalService.Domain.AggregatesModel.RentalAggregate.RentalItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Location")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("RentalItems", (string)null);
                });

            modelBuilder.Entity("TechnicalService.Domain.AggregatesModel.RentalAggregate.RentalService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RentalItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RentalItemId");

                    b.ToTable("RentalServices", (string)null);
                });

            modelBuilder.Entity("TechnicalService.Domain.AggregatesModel.RentalAggregate.RentalSparepart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("RentalServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SparepartId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RentalServiceId");

                    b.ToTable("RentalSpareparts", (string)null);
                });

            modelBuilder.Entity("TechnicalService.Domain.AggregatesModel.TechnicalAggregate.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items", (string)null);
                });

            modelBuilder.Entity("TechnicalService.Domain.AggregatesModel.TechnicalAggregate.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AwaitingCustomerConfirmDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AwaitingSparepartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CustomerRejectedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerRequest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinishedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasContract")
                        .HasColumnType("bit");

                    b.Property<Guid?>("InspectBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("InspectDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Inspection")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RepairBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("RepairDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServiceLocation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("SetAwaitingCustomerConfirmBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SetAwaitingSparepartBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SetCustomerRejectedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SetUnrepairableBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Solution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ThirdPartyRepairBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ThirdPartyRepairDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UnrepairableDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("VerifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("_servicePriorityId")
                        .HasColumnType("int")
                        .HasColumnName("ServicePriorityId");

                    b.Property<int>("_serviceStatusId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceStatusId");

                    b.Property<int>("_serviceTypeId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceTypeId");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("_servicePriorityId");

                    b.HasIndex("_serviceStatusId");

                    b.HasIndex("_serviceTypeId");

                    b.ToTable("Services", (string)null);
                });

            modelBuilder.Entity("TechnicalService.Domain.AggregatesModel.TechnicalAggregate.ServicePriority", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("ServicePriorities", (string)null);
                });

            modelBuilder.Entity("TechnicalService.Domain.AggregatesModel.TechnicalAggregate.ServiceStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("ServiceStatuses", (string)null);
                });

            modelBuilder.Entity("TechnicalService.Domain.AggregatesModel.TechnicalAggregate.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes", (string)null);
                });

            modelBuilder.Entity("TechnicalService.Domain.AggregatesModel.TechnicalAggregate.Sparepart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LinkItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserFor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Spareparts", (string)null);
                });

            modelBuilder.Entity("TechnicalService.Domain.AggregatesModel.TechnicalAggregate.SparepartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("RepairServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SparepartId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("SparepartItems", (string)null);
                });

            modelBuilder.Entity("TechnicalService.Domain.AggregatesModel.RentalAggregate.RentalService", b =>
                {
                    b.HasOne("TechnicalService.Domain.AggregatesModel.RentalAggregate.RentalItem", "RentalItem")
                        .WithMany()
                        .HasForeignKey("RentalItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RentalItem");
                });

            modelBuilder.Entity("TechnicalService.Domain.AggregatesModel.RentalAggregate.RentalSparepart", b =>
                {
                    b.HasOne("TechnicalService.Domain.AggregatesModel.RentalAggregate.RentalService", null)
                        .WithMany("Spareparts")
                        .HasForeignKey("RentalServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechnicalService.Domain.AggregatesModel.TechnicalAggregate.Item", b =>
                {
                    b.OwnsOne("TechnicalService.Domain.AggregatesModel.TechnicalAggregate.ItemType", "ItemType", b1 =>
                        {
                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Type")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ItemId");

                            b1.ToTable("Items");

                            b1.WithOwner()
                                .HasForeignKey("ItemId");
                        });

                    b.Navigation("ItemType")
                        .IsRequired();
                });

            modelBuilder.Entity("TechnicalService.Domain.AggregatesModel.TechnicalAggregate.Service", b =>
                {
                    b.HasOne("TechnicalService.Domain.AggregatesModel.TechnicalAggregate.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.HasOne("TechnicalService.Domain.AggregatesModel.TechnicalAggregate.ServicePriority", "ServicePriority")
                        .WithMany()
                        .HasForeignKey("_servicePriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnicalService.Domain.AggregatesModel.TechnicalAggregate.ServiceStatus", "Status")
                        .WithMany()
                        .HasForeignKey("_serviceStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechnicalService.Domain.AggregatesModel.TechnicalAggregate.ServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("_serviceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("ServicePriority");

                    b.Navigation("ServiceType");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TechnicalService.Domain.AggregatesModel.TechnicalAggregate.SparepartItem", b =>
                {
                    b.HasOne("TechnicalService.Domain.AggregatesModel.TechnicalAggregate.Service", null)
                        .WithMany("SparepartItems")
                        .HasForeignKey("ServiceId");
                });

            modelBuilder.Entity("TechnicalService.Domain.AggregatesModel.RentalAggregate.RentalService", b =>
                {
                    b.Navigation("Spareparts");
                });

            modelBuilder.Entity("TechnicalService.Domain.AggregatesModel.TechnicalAggregate.Service", b =>
                {
                    b.Navigation("SparepartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
