/**
 * @file widgetRegistry.ts
 * @description Catalog and default presets for QuickBooks-style dashboard widgets.
 */

import {
  DashboardWidgetId,
  DashboardWidgetConfig,
  DashboardViewMode,
  WidgetCategory,
  WidgetMeta,
  WidgetColSpan,
} from "./types";

export const CATEGORIES_META: Record<
  WidgetCategory,
  { label: string; labelKm: string }
> = {
  workflow: { label: "Workflow & Operations", labelKm: "ដំណើរការការងារ & ប្រតិបត្តិការ" },
  analytics: { label: "KPIs & Analytics", labelKm: "ស្ថិតិ & ការវិភាគ" },
  operations: { label: "Action & Tasks", labelKm: "សកម្មភាព & កិច្ចការបន្ទាន់" },
  inventory: { label: "Spare Parts & Stock", labelKm: "គ្រឿងបន្លាស់ & ស្តុក" },
  team: { label: "Team & Audit", labelKm: "ក្រុមការងារ & កំណត់ហេតុ" },
};

export const WIDGET_REGISTRY: Record<DashboardWidgetId, WidgetMeta> = {
  quick_actions: {
    id: "quick_actions",
    title: "Quick Action Shortcuts",
    titleKm: "ផ្លូវកាត់សកម្មភាពរហ័ស",
    description: "Instant triggers for machine reception, new tickets, QR scanner, and spare part inventory.",
    descriptionKm: "ផ្លូវកាត់សម្រាប់ទទួលម៉ាស៊ីន បង្កើតសំបុត្រថ្មី ស្កេន QR និងពិនិត្យគ្រឿងបន្លាស់។",
    category: "workflow",
    defaultColSpan: 4,
    minColSpan: 2,
    maxColSpan: 4,
    badge: "Fast Track",
    badgeKm: "រហ័ស",
  },
  kpi_cards: {
    id: "kpi_cards",
    title: "Key Metrics & Counters",
    titleKm: "សូចនាករគន្លឹះ & ចំនួនសរុប",
    description: "Authoritative counters for Today, Received, Waiting Customer, and Finished tickets.",
    descriptionKm: "ស្ថិតិសរុបប្រចាំថ្ងៃ ម៉ាស៊ីនទទួលបាន កំពុងរង់ចាំអតិថិជន និងជួសជុលរួចរាល់។",
    category: "analytics",
    defaultColSpan: 4,
    minColSpan: 2,
    maxColSpan: 4,
  },
  workflow_funnel: {
    id: "workflow_funnel",
    title: "Repair Process Funnel",
    titleKm: "ដំណាក់កាលជួសជុលទាំង ៦",
    description: "Visual 6-stage repair cycle tracking from Reception to AMC/Delivery.",
    descriptionKm: "តាមដានវដ្តជួសជុល ៦ ដំណាក់កាលពីទទួលម៉ាស៊ីនរហូតដល់ប្រគល់ជូន។",
    category: "workflow",
    defaultColSpan: 4,
    minColSpan: 2,
    maxColSpan: 4,
    badge: "Interactive",
    badgeKm: "អន្តរកម្ម",
  },
  ticket_chart: {
    id: "ticket_chart",
    title: "Ticket Intake Trends",
    titleKm: "និន្នាការសំបុត្រជួសជុល",
    description: "Volume analysis across 1H, 24H, 7D, and 30D intervals with peak diagnostics.",
    descriptionKm: "ការវិភាគបរិមាណសំបុត្រតាមចន្លោះពេល 1H, 24H, 7D និង 30D។",
    category: "analytics",
    defaultColSpan: 2,
    minColSpan: 2,
    maxColSpan: 4,
  },
  urgent_tickets: {
    id: "urgent_tickets",
    title: "Urgent & Overdue Queue",
    titleKm: "ជួសជុលបន្ទាន់ & ហួសកំណត់",
    description: "High-priority repairs and machines waiting over 3 days without progress.",
    descriptionKm: "សំបុត្រអាទិភាពបន្ទាន់ និងម៉ាស៊ីនរង់ចាំលើសពី ៣ ថ្ងៃដែលមិនទាន់ដំណើរការ។",
    category: "operations",
    defaultColSpan: 2,
    minColSpan: 1,
    maxColSpan: 4,
    badge: "Priority",
    badgeKm: "អាទិភាព",
  },
  service_table: {
    id: "service_table",
    title: "Service Tickets Master View",
    titleKm: "តារាងបញ្ជីសំបុត្រជួសជុល",
    description: "Comprehensive ticket directory with status filters, inline updates, and print actions.",
    descriptionKm: "បញ្ជីលម្អិតនៃសំបុត្រទាំងអស់ ជាមួយការច្រោះ និងការផ្លាស់ប្តូរស្ថានភាពរហ័ស។",
    category: "workflow",
    defaultColSpan: 4,
    minColSpan: 4,
    maxColSpan: 4,
  },
  low_stock: {
    id: "low_stock",
    title: "Low Spare Part Alerts",
    titleKm: "ការជូនដំណឹងគ្រឿងបន្លាស់ជិតអស់",
    description: "Inventory warnings for critical parts with zero or low quantity.",
    descriptionKm: "ការព្រមានស្តុកគ្រឿងបន្លាស់សំខាន់ៗដែលជិតអស់ ឬអស់ពីស្តុក។",
    category: "inventory",
    defaultColSpan: 2,
    minColSpan: 1,
    maxColSpan: 4,
    badge: "Stock",
    badgeKm: "ស្តុក",
  },
  engineer_workload: {
    id: "engineer_workload",
    title: "Technician Workload",
    titleKm: "បន្ទុកការងារជាងជួសជុល",
    description: "Active ticket capacity and assigned distribution per technician.",
    descriptionKm: "ការបែងចែកចំនួនម៉ាស៊ីន និងបន្ទុកការងារជាក់ស្តែងតាមជាងនីមួយៗ។",
    category: "team",
    defaultColSpan: 2,
    minColSpan: 2,
    maxColSpan: 4,
  },
  live_stream: {
    id: "live_stream",
    title: "Live Activity & Audit Feed",
    titleKm: "សកម្មភាពជាក់ស្តែង & កំណត់ហេតុ",
    description: "Real-time updates broadcasted over Server-Sent Events (SSE).",
    descriptionKm: "ការផ្សាយបន្តផ្ទាល់តាម SSE រាល់ពេលមានការកែប្រែ ឬបង្កើតសំបុត្រថ្មី។",
    category: "team",
    defaultColSpan: 4,
    minColSpan: 2,
    maxColSpan: 4,
    badge: "Live SSE",
    badgeKm: "បន្តផ្ទាល់",
  },
  kanban_board: {
    id: "kanban_board",
    title: "Kanban Pipeline Board",
    titleKm: "ក្ដារ Kanban តាមដំណាក់កាល",
    description: "Interactive visual columns for dragging tickets across lifecycle stages.",
    descriptionKm: "ទិដ្ឋភាពជួរឈរតាមដំណាក់កាល ងាយស្រួលតាមដាន និងផ្លាស់ប្តូរ។",
    category: "workflow",
    defaultColSpan: 4,
    minColSpan: 4,
    maxColSpan: 4,
    badge: "Board",
    badgeKm: "ក្ដារ",
  },
  stock_movement_live: {
    id: "stock_movement_live",
    title: "Live Stock In/Out Ledger",
    titleKm: "ចរន្តស្តុកគ្រឿងបន្លាស់ Real-Time",
    description: "Real-time spare part movements showing part images, part numbers, in/out count, and current stock balance.",
    descriptionKm: "តារាងចរន្តស្តុកគ្រឿងបន្លាស់ជាក់ស្តែងជាមួយរូបភាព លេខកូដគ្រឿង ចំនួននាំចូល/ដកចេញ និងស្តុកនៅសល់។",
    category: "inventory",
    defaultColSpan: 2,
    minColSpan: 2,
    maxColSpan: 4,
    badge: "Live Ledger",
    badgeKm: "ចរន្តស្តុក",
  },
  stock_spare_requests: {
    id: "stock_spare_requests",
    title: "Technician Spare Part Requests",
    titleKm: "គ្រឿងបន្លាស់ស្នើសុំដោយជាង",
    description: "Tickets waiting for spare parts or where parts were dispatched to bench.",
    descriptionKm: "ម៉ាស៊ីនកំពុងរង់ចាំគ្រឿងបន្លាស់ ឬទើបបានបញ្ជូនគ្រឿងទៅឱ្យជាងជួសជុល។",
    category: "inventory",
    defaultColSpan: 2,
    minColSpan: 2,
    maxColSpan: 4,
    badge: "Parts Queue",
    badgeKm: "តម្រូវការគ្រឿង",
  },
  technician_active_queue: {
    id: "technician_active_queue",
    title: "Active Diagnosis & Repair Queue",
    titleKm: "ជួរការងារជាងកំពុងដំណើរការ",
    description: "Active machines currently in technical inspection or repairing stage.",
    descriptionKm: "ម៉ាស៊ីនស្ថិតក្នុងដំណាក់កាល កំពុងពិនិត្យ និងកំពុងជួសជុលជាក់ស្តែងក្នុងរោងជាង។",
    category: "operations",
    defaultColSpan: 2,
    minColSpan: 2,
    maxColSpan: 4,
    badge: "Active",
    badgeKm: "កំពុងដំណើរការ",
  },
  sales_quotation_followup: {
    id: "sales_quotation_followup",
    title: "Quotation Follow-up Queue",
    titleKm: "តាមដានសម្រង់តម្លៃ",
    description: "Repair quotes waiting for customer confirmation, sorted by waiting duration.",
    descriptionKm: "សម្រង់តម្លៃកំពុងរង់ចាំអតិថិជនយល់ព្រមជួសជុល ជាមួយការដាស់តឿនលើស ៣ ថ្ងៃ។",
    category: "workflow",
    defaultColSpan: 2,
    minColSpan: 2,
    maxColSpan: 4,
    badge: "Sales",
    badgeKm: "សម្រង់តម្លៃ",
  },
  sales_kpis: {
    id: "sales_kpis",
    title: "Sales & Quote Performance",
    titleKm: "សមត្ថភាពផ្នែកលក់ & សម្រង់តម្លៃ",
    description: "Key metrics for pending quotes, confirmed sales, and conversion win rate.",
    descriptionKm: "ស្ថិតិសម្រង់តម្លៃរង់ចាំ ការលក់សម្រេច និងអត្រាជោគជ័យបំប្លែងការលក់។",
    category: "analytics",
    defaultColSpan: 2,
    minColSpan: 2,
    maxColSpan: 4,
    badge: "Win Rate",
    badgeKm: "អត្រាជោគជ័យ",
  },
  engineer_kpi: {
    id: "engineer_kpi",
    title: "Technician KPI Scorecard",
    titleKm: "សមិទ្ធផល & KPI ជាងជួសជុល",
    description: "Monthly scorecard ranking engineers by jobs completed, MTTR speed, and success rate.",
    descriptionKm: "ចំណាត់ថ្នាក់សមិទ្ធផលជាងប្រចាំខែ ល្បឿនជួសជុល និងអត្រាជោគជ័យ។",
    category: "team",
    defaultColSpan: 2,
    minColSpan: 2,
    maxColSpan: 4,
    badge: "KPIs",
    badgeKm: "សមិទ្ធផល",
  },
  tech_parts_ready: {
    id: "tech_parts_ready",
    title: "Parts Ready on Bench",
    titleKm: "គ្រឿងបន្លាស់មកដល់តុជាង",
    description: "Spare parts dispatched from stock to technician, ready for immediate installation.",
    descriptionKm: "គ្រឿងបន្លាស់ដែលបានបញ្ជូនមកដល់តុជាងរួចរាល់ អាចចាប់ផ្តើមជួសជុលភ្លាមៗ។",
    category: "operations",
    defaultColSpan: 2,
    minColSpan: 2,
    maxColSpan: 4,
    badge: "Ready",
    badgeKm: "រួចរាល់",
  },
  financial_revenue: {
    id: "financial_revenue",
    title: "Financial Revenue & Pipeline",
    titleKm: "ទិដ្ឋភាពហិរញ្ញវត្ថុ & ចំណូលសម្រេច",
    description: "Approved repair revenue and quotes in negotiation.",
    descriptionKm: "តម្លៃការងារជួសជុលសម្រេច និងទំហំសម្រង់តម្លៃក្នុង Pipeline។",
    category: "analytics",
    defaultColSpan: 2,
    minColSpan: 2,
    maxColSpan: 4,
    badge: "Revenue",
    badgeKm: "ចំណូល",
  },
  contract_renewals: {
    id: "contract_renewals",
    title: "Service Contract Renewals",
    titleKm: "កិច្ចសន្យាថែទាំ & បន្តកុងត្រា (AMC)",
    description: "Corporate accounts with maintenance SLA or recurring repairs.",
    descriptionKm: "អតិថិជនសាជីវកម្មមានកិច្ចសន្យា ឬមកជួសជុលញឹកញាប់។",
    category: "workflow",
    defaultColSpan: 2,
    minColSpan: 2,
    maxColSpan: 4,
    badge: "AMC",
    badgeKm: "កិច្ចសន្យា",
  },
};

export const VIEW_MODES_CONFIG: Record<
  DashboardViewMode,
  { label: string; labelKm: string; description: string; descriptionKm: string }
> = {
  overview: {
    label: "General & Accounts",
    labelKm: "ទូទៅ & គណនី",
    description: "Executive and financial pulse with KPIs, intake trends, workflow funnel, and main ticket table.",
    descriptionKm: "ទិដ្ឋភាពទូទៅប្រតិបត្តិ និងគណនី រួមមាន ស្ថិតិ និន្នាការ ដំណាក់កាល និងតារាងសំបុត្រ។",
  },
  technician: {
    label: "Technician Work",
    labelKm: "ការងារជាង",
    description: "Focused on urgent repairs, technician workload distribution, and live events.",
    descriptionKm: "ផ្តោតលើការងារជួសជុលជាក់ស្តែង កិច្ចការបន្ទាន់ បន្ទុកការងារជាង និងសកម្មភាពបន្តផ្ទាល់។",
  },
  inventory: {
    label: "Stock & Inventory",
    labelKm: "ការងារស្តុក",
    description: "Stock shortage alerts, active parts movement, and repair ticket inventory requirements.",
    descriptionKm: "ការគ្រប់គ្រងស្តុកគ្រឿងបន្លាស់ ការព្រមានអស់ស្តុក និងចរន្តស្តុកជាក់ស្តែង។",
  },
  sales: {
    label: "Sales & CRM Hub",
    labelKm: "ការងារផ្នែកលក់",
    description: "Quotation follow-ups, pending customer confirmations, conversion metrics, and confirmed sales.",
    descriptionKm: "ការតាមដានសម្រង់តម្លៃ ម៉ាស៊ីនរង់ចាំអតិថិជនយល់ព្រម អត្រាសម្រេចការលក់ និងសំបុត្រដែលបានយល់ព្រមជួសជុល។",
  },
  kanban: {
    label: "Kanban Board",
    labelKm: "ក្ដា kanban",
    description: "Full-width Kanban board for visual stage tracking from Received to Finished.",
    descriptionKm: "ក្ដារជួរឈរតាមដានដំណាក់កាលជួសជុលម៉ាស៊ីនពេញអេក្រង់។",
  },
};

export const DEFAULT_VIEW_PRESETS: Record<DashboardViewMode, DashboardWidgetConfig[]> = {
  overview: [
    { id: "kpi_cards", visible: true, colSpan: 4, order: 0 },
    { id: "urgent_tickets", visible: true, colSpan: 2, order: 1 },
    { id: "stock_movement_live", visible: true, colSpan: 2, order: 2 },
    { id: "service_table", visible: true, colSpan: 4, order: 3 },
    { id: "financial_revenue", visible: false, colSpan: 2, order: 4 },
    { id: "workflow_funnel", visible: false, colSpan: 4, order: 5 },
    { id: "ticket_chart", visible: false, colSpan: 2, order: 6 },
    { id: "quick_actions", visible: false, colSpan: 4, order: 7 },
    { id: "low_stock", visible: false, colSpan: 2, order: 8 },
    { id: "engineer_workload", visible: false, colSpan: 2, order: 9 },
    { id: "live_stream", visible: false, colSpan: 4, order: 10 },
    { id: "kanban_board", visible: false, colSpan: 4, order: 11 },
    { id: "stock_spare_requests", visible: false, colSpan: 2, order: 12 },
    { id: "technician_active_queue", visible: false, colSpan: 2, order: 13 },
    { id: "sales_quotation_followup", visible: false, colSpan: 2, order: 14 },
    { id: "sales_kpis", visible: false, colSpan: 2, order: 15 },
    { id: "engineer_kpi", visible: false, colSpan: 2, order: 16 },
    { id: "tech_parts_ready", visible: false, colSpan: 2, order: 17 },
    { id: "contract_renewals", visible: false, colSpan: 2, order: 18 },
  ],
  technician: [
    { id: "technician_active_queue", visible: true, colSpan: 2, order: 0 },
    { id: "tech_parts_ready", visible: true, colSpan: 2, order: 1 },
    { id: "engineer_kpi", visible: true, colSpan: 2, order: 2 },
    { id: "engineer_workload", visible: true, colSpan: 2, order: 3 },
    { id: "live_stream", visible: true, colSpan: 4, order: 4 },
    { id: "urgent_tickets", visible: false, colSpan: 2, order: 5 },
    { id: "workflow_funnel", visible: false, colSpan: 2, order: 6 },
    { id: "service_table", visible: false, colSpan: 4, order: 7 },
    { id: "quick_actions", visible: false, colSpan: 4, order: 8 },
    { id: "kpi_cards", visible: false, colSpan: 4, order: 9 },
    { id: "ticket_chart", visible: false, colSpan: 2, order: 10 },
    { id: "low_stock", visible: false, colSpan: 2, order: 11 },
    { id: "stock_movement_live", visible: false, colSpan: 4, order: 12 },
    { id: "stock_spare_requests", visible: false, colSpan: 2, order: 13 },
    { id: "kanban_board", visible: false, colSpan: 4, order: 14 },
    { id: "sales_quotation_followup", visible: false, colSpan: 2, order: 15 },
    { id: "sales_kpis", visible: false, colSpan: 2, order: 16 },
    { id: "financial_revenue", visible: false, colSpan: 2, order: 17 },
    { id: "contract_renewals", visible: false, colSpan: 2, order: 18 },
  ],
  inventory: [
    { id: "low_stock", visible: true, colSpan: 2, order: 0 },
    { id: "stock_spare_requests", visible: true, colSpan: 2, order: 1 },
    { id: "stock_movement_live", visible: true, colSpan: 4, order: 2 },
    { id: "urgent_tickets", visible: false, colSpan: 2, order: 3 },
    { id: "workflow_funnel", visible: false, colSpan: 4, order: 4 },
    { id: "service_table", visible: false, colSpan: 4, order: 5 },
    { id: "quick_actions", visible: false, colSpan: 4, order: 6 },
    { id: "kpi_cards", visible: false, colSpan: 4, order: 7 },
    { id: "ticket_chart", visible: false, colSpan: 2, order: 8 },
    { id: "engineer_workload", visible: false, colSpan: 2, order: 9 },
    { id: "live_stream", visible: false, colSpan: 4, order: 10 },
    { id: "kanban_board", visible: false, colSpan: 4, order: 11 },
    { id: "technician_active_queue", visible: false, colSpan: 2, order: 12 },
    { id: "sales_quotation_followup", visible: false, colSpan: 2, order: 13 },
    { id: "sales_kpis", visible: false, colSpan: 2, order: 14 },
    { id: "engineer_kpi", visible: false, colSpan: 2, order: 15 },
    { id: "tech_parts_ready", visible: false, colSpan: 2, order: 16 },
    { id: "financial_revenue", visible: false, colSpan: 2, order: 17 },
    { id: "contract_renewals", visible: false, colSpan: 2, order: 18 },
  ],
  sales: [
    { id: "sales_kpis", visible: true, colSpan: 2, order: 0 },
    { id: "sales_quotation_followup", visible: true, colSpan: 2, order: 1 },
    { id: "contract_renewals", visible: true, colSpan: 2, order: 2 },
    { id: "workflow_funnel", visible: true, colSpan: 2, order: 3 },
    { id: "service_table", visible: false, colSpan: 4, order: 4 },
    { id: "kpi_cards", visible: false, colSpan: 4, order: 5 },
    { id: "urgent_tickets", visible: false, colSpan: 2, order: 6 },
    { id: "live_stream", visible: false, colSpan: 4, order: 7 },
    { id: "quick_actions", visible: false, colSpan: 4, order: 8 },
    { id: "ticket_chart", visible: false, colSpan: 2, order: 9 },
    { id: "low_stock", visible: false, colSpan: 2, order: 10 },
    { id: "engineer_workload", visible: false, colSpan: 2, order: 11 },
    { id: "stock_movement_live", visible: false, colSpan: 4, order: 12 },
    { id: "stock_spare_requests", visible: false, colSpan: 2, order: 13 },
    { id: "technician_active_queue", visible: false, colSpan: 2, order: 14 },
    { id: "kanban_board", visible: false, colSpan: 4, order: 15 },
    { id: "engineer_kpi", visible: false, colSpan: 2, order: 16 },
    { id: "tech_parts_ready", visible: false, colSpan: 2, order: 17 },
    { id: "financial_revenue", visible: false, colSpan: 2, order: 18 },
  ],
  kanban: [
    { id: "kanban_board", visible: true, colSpan: 4, order: 0 },
    { id: "workflow_funnel", visible: true, colSpan: 4, order: 1 },
    { id: "quick_actions", visible: false, colSpan: 4, order: 2 },
    { id: "urgent_tickets", visible: false, colSpan: 2, order: 3 },
    { id: "kpi_cards", visible: false, colSpan: 4, order: 4 },
    { id: "ticket_chart", visible: false, colSpan: 2, order: 5 },
    { id: "service_table", visible: false, colSpan: 4, order: 6 },
    { id: "low_stock", visible: false, colSpan: 2, order: 7 },
    { id: "engineer_workload", visible: false, colSpan: 2, order: 8 },
    { id: "stock_movement_live", visible: false, colSpan: 4, order: 9 },
    { id: "stock_spare_requests", visible: false, colSpan: 2, order: 10 },
    { id: "technician_active_queue", visible: false, colSpan: 2, order: 11 },
    { id: "sales_quotation_followup", visible: false, colSpan: 2, order: 12 },
    { id: "sales_kpis", visible: false, colSpan: 2, order: 13 },
    { id: "engineer_kpi", visible: false, colSpan: 2, order: 14 },
    { id: "tech_parts_ready", visible: false, colSpan: 2, order: 15 },
    { id: "financial_revenue", visible: false, colSpan: 2, order: 16 },
    { id: "contract_renewals", visible: false, colSpan: 2, order: 17 },
    { id: "live_stream", visible: false, colSpan: 4, order: 18 },
  ],
};

export function getWidgetMeta(id: DashboardWidgetId): WidgetMeta {
  return (
    WIDGET_REGISTRY[id] ?? {
      id,
      title: id,
      titleKm: id,
      description: "",
      descriptionKm: "",
      category: "workflow",
      defaultColSpan: 4,
      minColSpan: 1,
      maxColSpan: 4,
    }
  );
}

export function getDefaultConfig(id: DashboardWidgetId, order: number): DashboardWidgetConfig {
  const meta = getWidgetMeta(id);
  return {
    id,
    visible: true,
    colSpan: meta.defaultColSpan,
    order,
  };
}
