/**
 * @file report-layout/css.ts
 * @description The one stylesheet for the printed Technical Service Report.
 *
 * See `types.ts` for why this folder has no framework imports.
 *
 * ── WHY EVERY DESIGN TOKEN IS CONVERTED TO MILLIMETRES ────────────────────
 * The template stores sizes in px because that is what the designer canvas
 * manipulates. px is a *device* unit, and the two rasterizers that print this
 * document do not agree on it: a browser lays out at 96 CSS px per inch,
 * while the WebView expo-print rasterises into a 595pt-wide A4 page maps CSS
 * px to roughly 72 per inch. A `padding: 32px` therefore prints 8.5mm on the
 * desktop and 11.3mm on the phone — the two outputs drift apart even though
 * they ran the same code.
 *
 * CSS defines `1mm` as exactly `96/25.4` px, so converting once here
 * (`mm()`) is lossless on the web — 32px is still 32px on screen — and pins
 * the phone to the same physical geometry. Font sizes are already in pt, a
 * physical unit, and need no conversion.
 *
 * ── AND WHY @page CARRIES NO MARGIN ───────────────────────────────────────
 * The page box is the full A4 sheet and all whitespace is the sheet's own
 * padding. That is what makes the print identical to the preview: the same
 * `.rpt-sheet` box, with the same padding, is what you see on screen and what
 * lands on paper — the margins are even on all four edges because one
 * declaration sets them. Splitting the whitespace between an `@page margin`
 * and a sheet padding is what previously made the printed page sit
 * top-left with a wide band down the right.
 */

import { cssNumber, resolveReportFontFamily, REPORT_MONO_FAMILY } from "./format";
import type { ReportTemplateSettings } from "./types";

/** px (at the CSS-standard 96dpi) → mm, rounded to a sane precision. */
export function pxToMm(px: number): string {
  // Coerced because these come from the unvalidated stored template; a
  // non-finite value would otherwise emit `NaNmm` into the stylesheet.
  return `${Number(((cssNumber(px, 0, -1e4, 1e4) * 25.4) / 96).toFixed(4))}mm`;
}

const A4_WIDTH_MM = 210;
const A4_HEIGHT_MM = 297;

/**
 * A4's width in CSS pixels, which CSS fixes at exactly `96/25.4` px per mm.
 *
 * Exported so a caller can work out the zoom that fits the sheet to a narrow
 * screen — the phone's WebView is ~412px wide against this 794 — instead of
 * hardcoding the number at the call site.
 */
export const A4_WIDTH_PX = Math.round((A4_WIDTH_MM * 96) / 25.4);

export interface ReportCssOptions {
  /**
   * Screen chrome around the sheet. The standalone document mobile prints
   * passes `false` so the sheet is the whole page.
   */
  includeViewportChrome?: boolean;
}

/**
 * Builds the complete stylesheet for one set of template settings.
 *
 * The output is used verbatim by the web preview, the web print path and the
 * mobile WebView/PDF — there is no per-platform branch anywhere in it.
 */
export function buildReportCss(
  s: ReportTemplateSettings,
  options: ReportCssOptions = {},
): string {
  const { includeViewportChrome = true } = options;

  const bodyFont = resolveReportFontFamily(s.fontFamily);
  const baseFontPt = cssNumber(s.baseFontPt, 10, 4, 72);
  const smallFontPt = Math.max(6, baseFontPt - 0.5);
  const pagePad = pxToMm(s.pageMarginPx);
  const border = `${pxToMm(s.tableBorderWidthPx)} solid #000`;
  const cellPadY = pxToMm(s.tableCellPaddingPx);

  const rightBoxPercent = Math.max(20, 97 - cssNumber(s.headerLeftBoxPercent, 57, 5, 95));

  return `
/* ─────────────────────────────────────────────────────────────────────────
   Technical Service Report — generated by src/report-layout/css.ts.
   Do not hand-edit a copy of this; change the generator.
   ───────────────────────────────────────────────────────────────────────── */

/* The sheet itself is in this selector, not only its descendants. Without it
   the print rule below (\`width: 100%\` plus the page padding) makes the sheet
   exactly two paddings wider than the page box — 64px at the shipped 32px
   margin — and the right edge of every line runs off the paper. */
.rpt-sheet,
.rpt-sheet *,
.rpt-sheet *::before,
.rpt-sheet *::after { box-sizing: border-box; }

@page {
  size: A4 portrait;
  margin: 0;
}

${includeViewportChrome ? `
/* The clean desk the sheet sits on. Screen only — print never sees it. */
@media screen {
  .rpt-viewport {
    display: flex;
    justify-content: center;
    align-items: flex-start;
    padding: 16px 8px 32px;
    background: #0f172a;
    min-height: 100%;
    overflow: auto;
  }
  /* Preview zoom. Declared inside @media screen ON PURPOSE: a zoom that
     leaks into the print render is what shrank the printed page to 85% and
     pinned it to the top-left corner. Print cannot see this rule at all. */
  .rpt-zoom { zoom: var(--rpt-zoom, 1); }
  /* The off-screen copy that exists only to be printed. */
  .rpt-print-only { display: none !important; }
}
` : ""}

.rpt-sheet {
  width: ${A4_WIDTH_MM}mm;
  min-height: ${A4_HEIGHT_MM}mm;
  padding: ${pagePad};
  background: #ffffff;
  color: #000000;
  font-family: ${bodyFont};
  font-size: ${cssNumber(s.baseFontPt, 10, 4, 72)}pt;
  line-height: ${cssNumber(s.lineHeight, 1.3, 0.5, 5)};
  /* Khmer builds a syllable from a base consonant plus stacked sub-consonants
     (coeng) and vowel signs. Letter-spacing is a Latin device and pulls those
     stacks apart, and the shaping features have to be on or the coeng lands in
     the wrong place. The web app used to get this from a globals.css rule keyed
     to the report's element id; it lives here now so the phone's WebView — which
     has no globals.css — shapes Khmer identically. */
  letter-spacing: normal;
  font-feature-settings: "kern" 1, "liga" 1, "calt" 1, "clig" 1;
  text-rendering: optimizeLegibility;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  position: relative;
}

@media screen {
  .rpt-sheet {
    box-shadow: 0 8px 28px -4px rgba(0, 0, 0, 0.45);
    border: none;
    overflow: visible;
  }
}

.rpt-sheet-top { flex: 1 1 auto; display: flex; flex-direction: column; }

/* ── Header: logo left, title right ── */
.rpt-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-bottom: ${pxToMm(12)};
}
/* ── Why the header slots are declared, and not left to flex defaults ──────
   The Logo Height slider was doing nothing above ~80px, for two compounding
   reasons. The shipped Cam logo is 2870x700 (aspect 4.10), so at the default
   96px it needs 394px of the 730px content width.

   1. max-width: 45% capped it at 328px, forcing the height back to 80px.
   2. More importantly, the slot holding it is a flex item and flex items
      default to flex-shrink: 1 — so it was shrunk to 228px regardless, and
      object-fit: contain then letterboxed the image inside that short box.
      The element reported height: 96px while the visible mark was far smaller,
      which is why the slider looked broken rather than clamped.

   The logo slot no longer shrinks; the title slot absorbs the remainder and
   may wrap. The cap stays, generously, so a pathological logo still cannot
   crowd the title out entirely. */
.rpt-logo-slot { flex: 0 0 auto; min-width: 0; }
.rpt-title-slot { flex: 1 1 auto; min-width: 0; }
.rpt-logo {
  height: ${pxToMm(s.logoHeightPx)};
  width: auto;
  max-width: 100%;
  object-fit: contain;
  display: block;
}
.rpt-title {
  font-family: 'Times New Roman', Times, serif;
  font-size: ${cssNumber(s.titleFontPt, 12, 4, 96)}pt;
  font-weight: 700;
  font-style: italic;
  letter-spacing: 0.025em;
  text-transform: uppercase;
  text-align: right;
  padding: 0 ${pxToMm(4)};
  color: #1e293b;
}

/* ── The two bordered header boxes ── */
.rpt-headerboxes {
  display: flex;
  align-items: stretch;
  justify-content: space-between;
  gap: ${pxToMm(8)};
  margin-bottom: ${pxToMm(12)};
  font-size: ${smallFontPt}pt;
  font-family: Arial, sans-serif;
}
.rpt-headerbox {
  border: ${pxToMm(1)} solid #000000;
  padding: ${pxToMm(8)};
  line-height: 1.375;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
}
.rpt-headerbox--left { width: ${cssNumber(s.headerLeftBoxPercent, 57, 5, 95)}%; }
.rpt-headerbox--right { width: ${rightBoxPercent}%; }
.rpt-box-row { display: flex; align-items: center; justify-content: center; width: 100%; }
.rpt-box-label {
  font-weight: 700;
  text-align: right;
  padding-right: ${pxToMm(6)};
  padding-left: ${pxToMm(4)};
  flex-shrink: 0;
  white-space: nowrap;
}
.rpt-headerbox--left .rpt-box-label { width: ${pxToMm(145)}; }
.rpt-headerbox--right .rpt-box-label { width: ${pxToMm(100)}; }
.rpt-box-value {
  text-align: left;
  flex-shrink: 0;
  white-space: nowrap;
  padding: 0 ${pxToMm(4)};
  font-weight: 400;
}
.rpt-headerbox--left .rpt-box-value { width: ${pxToMm(140)}; }
.rpt-headerbox--right .rpt-box-value { width: ${pxToMm(140)}; }
.rpt-box-value--bold { font-weight: 700; }
.rpt-box-status { width: 100%; text-align: center; font-weight: 700; white-space: nowrap; padding: 0 ${pxToMm(4)}; }

/* ── Numbered sections ── */
.rpt-section { margin-bottom: ${pxToMm(s.sectionGapPx)}; }
.rpt-section-heading {
  font-weight: 700;
  text-decoration: underline;
  color: #000000;
  margin-bottom: ${pxToMm(4)};
  font-size: inherit;
}
.rpt-inforows { color: #000000; }
.rpt-inforow {
  display: flex;
  align-items: flex-start;
  padding: ${pxToMm(2)} ${pxToMm(4)};
}
.rpt-inforow + .rpt-inforow { margin-top: ${pxToMm(4)}; }
.rpt-inforow-label {
  width: ${pxToMm(s.labelColWidthPx)};
  flex-shrink: 0;
  white-space: nowrap;
  font-weight: 700;
  text-align: right;
  padding-left: ${pxToMm(4)};
  padding-right: ${pxToMm(8)};
}
.rpt-inforow-value {
  flex: 1 1 auto;
  font-weight: 400;
  color: #000000;
  padding: 0 ${pxToMm(6)};
  line-height: 1.35;
  overflow-wrap: anywhere;
}
.rpt-body {
  color: #000000;
  line-height: 1.375;
  padding-left: ${pxToMm(s.contentIndentPx)};
  padding-right: ${pxToMm(4)};
  white-space: pre-wrap;
  overflow-wrap: anywhere;
}
.rpt-body--solution { margin-bottom: 0; }
.rpt-section--table {
  margin-top: 0;
  margin-bottom: ${pxToMm(s.sectionGapPx)};
}
.rpt-section--table .rpt-table {
  margin-top: 0;
}

/* ── Spare-parts table ── */
.rpt-table {
  width: 100%;
  border-collapse: collapse;
  margin-top: ${pxToMm(6)};
  color: #000000;
  font-size: ${cssNumber(s.tableFontPt, 9.5, 4, 72)}pt;
  border: ${border};
  table-layout: fixed;
}
.rpt-table th,
.rpt-table td {
  padding-top: ${cellPadY};
  padding-bottom: ${cellPadY};
  vertical-align: top;
  overflow-wrap: anywhere;
}
.rpt-table th { font-weight: 700; text-align: center; background: #ffffff; }
.rpt-table thead tr { border-bottom: ${border}; }
.rpt-table tbody tr { border-bottom: ${border}; }
.rpt-table .rpt-cell-divider { border-right: ${border}; }
.rpt-pad-1 { padding-left: ${pxToMm(4)}; padding-right: ${pxToMm(4)}; }
.rpt-pad-2 { padding-left: ${pxToMm(8)}; padding-right: ${pxToMm(8)}; }
.rpt-align-left { text-align: left; }
.rpt-align-center { text-align: center; }
.rpt-align-right { text-align: right; }
.rpt-mono { font-family: ${REPORT_MONO_FAMILY}; white-space: nowrap; }
.rpt-bold { font-weight: 700; }
.rpt-row-empty { height: ${pxToMm(s.emptyTableHeightPx)}; }

/* ── Signatures ── */
.rpt-signatures {
  margin-top: auto;
  padding-top: ${pxToMm(24)};
  display: grid;
  gap: ${pxToMm(16)};
  text-align: center;
  color: #000000;
  flex-shrink: 0;
  padding-left: ${pxToMm(8)};
  padding-right: ${pxToMm(8)};
}
.rpt-sig {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: ${pxToMm(6)};
}
.rpt-sig-rule {
  width: 80%;
  border-top: ${pxToMm(1)} solid #000000;
  margin-bottom: ${pxToMm(6)};
}
.rpt-sig-km { font-weight: 700; padding: 0 ${pxToMm(4)}; }
.rpt-sig-en {
  font-family: Arial, sans-serif;
  font-size: ${smallFontPt}pt;
  padding: 0 ${pxToMm(4)};
  color: #1f2937;
}
.rpt-sig-name { font-weight: 700; padding: 0 ${pxToMm(4)}; }
.rpt-sig-phone { font-size: ${smallFontPt}pt; padding: 0 ${pxToMm(4)}; }

/* ── Print ──────────────────────────────────────────────────────────────
   The sheet becomes the page box exactly. Width is 100% rather than a hard
   210mm so the phone's PDF page (which expo-print sizes itself) is filled
   edge to edge too, instead of overflowing by the fraction of a millimetre
   that 210mm exceeds 595pt. */
@media print {
  html, body {
    margin: 0 !important;
    padding: 0 !important;
    background: #ffffff !important;
    width: auto !important;
    height: auto !important;
    -webkit-print-color-adjust: exact !important;
    print-color-adjust: exact !important;
  }
  .rpt-screen-only { display: none !important; }
  .rpt-print-only { display: block !important; }
  .rpt-viewport {
    display: block !important;
    padding: 0 !important;
    margin: 0 !important;
    background: #ffffff !important;
    overflow: visible !important;
    min-height: 0 !important;
  }
  .rpt-zoom {
    zoom: 1 !important;
    transform: none !important;
  }
  .rpt-sheet {
    width: 100% !important;
    max-width: none !important;
    min-height: ${A4_HEIGHT_MM}mm !important;
    margin: 0 !important;
    padding: 4mm 6mm !important;
    border: none !important;
    box-shadow: none !important;
    background: #ffffff !important;
    overflow: visible !important;
    break-inside: avoid;
    page-break-inside: avoid;
  }
  .rpt-table { break-inside: auto; page-break-inside: auto; }
  .rpt-table tr { break-inside: avoid; page-break-inside: avoid; }
  .rpt-no-print,
  .rpt-parts-tfoot,
  .rpt-parts-tfoot *,
  .rpt-col-action,
  [data-rpt-add-row] {
    display: none !important;
    height: 0 !important;
    max-height: 0 !important;
    border: none !important;
    border-top: none !important;
    border-bottom: none !important;
    padding: 0 !important;
    margin: 0 !important;
    line-height: 0 !important;
    font-size: 0 !important;
    visibility: hidden !important;
  }
}
`.trim();
}

/**
 * The `<style>` text that isolates the report when it is printed from inside
 * the full web app, where the rest of the page is still in the DOM.
 *
 * Kept apart from `buildReportCss` because the standalone document the phone
 * prints has nothing to hide — including these rules there would be dead CSS.
 * `display: none` rather than `visibility: hidden`: a hidden element still
 * occupies its box and still contributes to page breaks, which is why the old
 * print output reserved space for the app chrome it had just made invisible.
 */
export function buildWebPrintIsolationCss(): string {
  return `
@media print {
  body > *:not(.rpt-print-root) { display: none !important; }
  /* The root is portalled to <body> so that no ancestor can reposition or
     clip it. That matters more than it sounds: the app shell carries
     'transform: translateZ(0)', which makes it the containing block for
     every fixed and absolutely positioned descendant — a report rendered
     inside it printed anchored to the content stage rather than the page,
     inset from the top-left with a blank band down the right edge. It also
     carries 'overflow: hidden', which cropped the signature block off the
     bottom of the sheet. */
  .rpt-print-root,
  .rpt-print-passthrough {
    display: block !important;
    position: static !important;
    inset: auto !important;
    width: auto !important;
    height: auto !important;
    min-height: 0 !important;
    max-width: none !important;
    max-height: none !important;
    overflow: visible !important;
    background: #ffffff !important;
    border: none !important;
    box-shadow: none !important;
    margin: 0 !important;
    padding: 0 !important;
    transform: none !important;
    filter: none !important;
    backdrop-filter: none !important;
    z-index: auto !important;
    opacity: 1 !important;
  }
}
`.trim();
}

